--[[
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN/``.-:/+shdmNNNNMNNMMMMMMMNNMMMNmmNNNmmNmmmmmmmmmmmmmdhhhhhddmNNMMMMMMMMMMMMMMMMMMMMMMMMMNNNNmmmmmmm
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmNNNNNNNMMMMMMMNNMMMMMMMNNNMMNmmmmNNNNNmdhyyyhyssyo/--:://oydNMMMMMMNNNNNNNNNNNNNNNNNNNmmmmmmmmmmm
MNMNMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNMMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmMMMMMMMNNNMMNmmmdhyso+/://///+++os+---:/++oymNMMMMNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmm
NNNNNMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNmmmmmmmNMMMMMMNNNNNNMMMMMMMMMMMMMMMMMMMMMMMNmdhysoooooooosyyhddmNNNMMMNMMMMMNNNNNhNMMMMMMNmNNNmhso++///////:---::::+s+::://:+smNMMMMNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmm
NNNNNNNNMMMMMMMMMMMMMMNNNNNNNmmNmmmmmmmmmdmmNMMMMMNNNNNNNNNNNMMMMMMMMMMMNmhyo+:-````             ````.-/sdNNNmNNNNNNNNmNNMMMNNNmdhyyyyyyssosoo+++//:::-.-//---:::/omNMMMMNNNNNNNNmNmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNMMMMMMMMMMMMMMMNNNNNNNmmmmddhhyyyyyymNMMMMNmNNNNNNNNNNNNNNmdyo/-.``                            `.:ddmddmNNNNNNmNNNNNmmdhhysooo++++++/+//+++/:--.....----//omNNMMNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNMMMMMMMMMMMMNNNNNNNNNNNNNmmmdddhhyydNMMMMMmNNNNNNNNNdyo/-``                                   `.+mmNmdNNNNNNmmNNmdhyyysoo+++++/:///+//:-...........----//odNNNMNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNMMMMMMMMMMNNNNNNNNNNNNNNNNmmmmmmmmNNMMMMMNNNNmmho/-``                                        .-sNNNNmNNNNNNmmdhyyyo++/////://++/:-..``````.........---:/odmNNNMNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNNMMMMMMMMMNNNNNNNNNNNNNNNmmmmmmmmmNNMMMMMNdy+-.`                                            `.:dNNNNmNNNNmdhhyss+::::----..--..``````````...........-::/+hmNNNMNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNNNMMMMMMMMNNNNNNNNNNNmNmmmmmmmmmmmNNNNmho-`                                                 `-+NNNNNmNmdhyysso+-..-:-....```` ````````````..........--::+ymNNNMNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNNNNNMMMMMMNNNNNNNNNNNNNmmmmmmmmmmmmhs:.`                                                 ` `.:sNNNNNmhyyysso+:.``.--.```    ````````````````.........-::/smNNNMNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNNNNNMMMMMMNNNNNNNNNNNNNmNmmmmmmdy+-`                                                       `.:dMNNmhsosyso/-.```````       ` `````````````````.......-://odNNNMNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNNNNNNMMMMMNNNNNNNNNNNNmNmmmmdy/.`                                                       `  `./mNdhso++o+:..``````     ` ` `   ``````````````````...---::/+hmNNMNNNmmmmmmmmmmmmmmNmNNNNNNNNNMMM
NNNNNNNNNNNNNNNNNMMMMNNNNNNNNNNNmmmdy+-`                                                            ``-omdoso++/-.```````````` `     `  ``````````````````....--::/+yNNNMMNNNNNNNNNNNMNNMMMMMMMMMMMMMMMM
NNNNNNNNNNNNNNNNNMMMMNNNNNNNNNNNmh+-`````                                                    ``  `  `.-dNyoooo:..`````````````````` `````````` ````````````...--:/+oyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MNNNNNNNNNNNNNNNMMMMMNNNNNNNNmdo-`````````                                                       ````.:Ndo/++:-..``````````````````````````````````````````...-:/oydNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMNds/.``` `  ``                                                       ``````.+Ny/:+:-.```````````````````````````   `````````````..::+shmNNdddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNmho/.`````` ``  ````                                                `````.``..-oyhoo/-`````````````````````````````       ```````.-:/syhhhdhyyyhdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MNNMMMNNMMMNMMMMMMNmho/-.``````````````` ``                                           `  ```````..`--:--hh+.```````````````````````````        ``````..-:/+osoooossssyhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMNMMMNNNMMNds/-......``````````````  ``                                       `  `` ```````.-`.:/--/+```````````` `````````````````   ````````..-:/++oooooosssssyhhdmNMMMMMMMMMMMMMMMMMMMMMMMMNMMMM
MMMMMMMMMMMMNds/.........````````````````  ``                                         ``````````--..:/:/:```````````````````````````````````````...-:/+++++ooooooossssssyhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMmy/-.....-......```````````````` ```                                         ``````...--:::/:......`````````````````````````````...--::///+++++++++++ooo+++oosymNNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMNMMdo:-----------.....``````````` ``` ````                                   ```..---:://+osyhdyo:-....--..............``````````.-:////++/::::://///++++++++++oshdNNmNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMd+:--------------....``````` ```` ``` ````                            ```.--:::///////+++oosyhmds:------------......```````....:+o++////////:::://///++++++++oshhdhhhdNMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMm+-------------------...`````     ``  `` `````                    ```......---:::://////++++oooosydh+/:------------..``````...--+so++oossyyyyysssssoo+++++++++ossyhhhhhhmMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMNs/:--:::--------------..``````     ``  ```````               ``...........-----::::://///++++++oooshhsso+++////::-:::---....`./sssoosysoo++++ooososooo++//++++syhddhhdddmMMMNMNNNNNMMMMMMMMMMMMMMMMM
MMMMNdy/:::::-------------.-.`````     `````````````       `..-----.-.............---::::///+++++++++oosyhddhsysso+++//++:::-..`.:osyssso++///::///++++++++++//+oshdmmNmhhmNmMMNNNNNNMMMMMMMMMMMMMMMMMMM
MMMMMNNms/:::::----------.-.-.````````````````````    `.:++//:::----.-.-........-----::::////++++++++ooossyoymNdyyssooo++////+++ssoosyo+//////++ooossssooooo++//oydsdmmmhydmmNMNNMNNMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMms:::::--------..-.....```````````````````-/+ysso+/::::::------..---------..--::::///+++++++ooooymNMMMNdysssssooshdddyssssoss++++++ososyhyyyyysssssoo++oshyyyyyyyhddmNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMNs/:/:::------------......``````````:+syyyysso+/:::::::::--.--:://+++++/::---::::::////+++++oosdMMMMNhyssoyNMMMMNNmhyssssoo++++osyhmNdmy//oso//+oosooosyhhhyyyyyhhdmMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMms//::::----:::----......````.:oydmmddhhyso//:::::::::--://///:://///+++ooo+//:::::::://+++ooyNMMMmoosyysdNNMNNNmhysssso+///+oyyyhdddsosssso+oosssooossydhhhhhhhhdMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMms+/::--::///::----....-/ohmdmdmmddhhys+/:::::/://::::::--..........::/+o+/++:----:::////++odMMMmoso//shdNNNNNmdhyssoo+////++++++/+++ooooo+oosossoooosydhyyhhhhdNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNh+/+++/++//::---:+ydmNmmdmmddddyyso/::::://////::---...............--//////------:::///+oymMMNos+//+osydNNNmdyyysso+//////////+++ooo++++oooosssssssshhyyyyhhhNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMNdysoo+++///+shmNNmmmdhhdddhyyso+/:::::://///::--.........--------....----------:://+oydmmNMMhs///:+ssydNNmhysssso++///////++o+o++++++/+osssyyysssssyyssyyhdNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNNdyssosydNNNNmmmddhddhddhhys+//:::::::///::-......--::///++//:---........---:::/+osydmNmMMNs+++::+s+odNmhyyyyso++///////////+++++///oyyssyyso+/oosyyssyhdNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMNdddNNNNNmmNmdddmdddddhyys++/::/:::////:-...-.-:://+///++oso/:---.......-:///+ooosssymNMMdso+o++s+/smmmhyyyyso++/+////:::::::///++sssoooss+/:+ooysssyhmMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmNNNNNmmmdddddhhhssso//::://////:-....--://++os+-``.:/+/---....`..-/++o++///+osdNMMMhooso++o++hmmdhhhyysoo+++/////::::://+++osssssyyyoosshhysyydNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNmmdddhhdyssso+////////::-.....--:/:sddhdy-..-::/-.........-/so+///+ossydMMMMMmyo+////+ymmddhhhhssoo++++++++///+++++//+oooooosssyhddhyyydNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNMNNNmmdddyhhysoso/////////:---.---::://oyyyhs-.-://:...-------:/ooooo/+shdhmMMMMMMMmhso+//odmmddhhhyssoo++oo++++++++o+/////+++++++oshhhddyhmMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMmdyysydmNmmddhyhhyysso+////////::----------::---://////++/:::::::::::/+sdmds::ohdNNMMMMMMMMNNmhyshmNmddhhhysooo+ooo++++++++//++////++++oosyhdddyhNMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMNh++/++///osyhdyydhysso++///////:::-----------...----::///+/::::::::::::/+sooooosyhNMMMMMMMMMMMMmhyymNNmddhhysso++osooo++o+++++++++ooooosssyhdmmdydMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMh/::///::/::+yhsyddhsoo++////::/:::--:::------.....---:::/::::::::::---::/+o+++++shNNNNNNNNNNNMMNmhydmNmmdhhhyso+++osoo++++++oosssyyyyyyyyhdddmdhhNMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMm/--:++:-./+::+++syddyoo+////://::::--------------------:::::::::::::---:::/+o++++ohNNNMMMMMMMMMMMmdhhmmmmdhhyyyso+//oo++/+++syyhhhyyyyyyhhhhhdmdhmMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMh:-:+o+/:////-::/+osyyo++//:////:::--------......---------------:-::::::::::/+oo++osNMMMMMMMMMMMMMNmdhhdmddhhyyysoo+/+o++//++ooosssssssssysyyhddmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMm/:/so/:----/://:/+osoo+//////////:------...........--------------::::///::::/++o++smMMMMMMMMMMMMMMmddhhddddhhyyyss+++++++/++ooo+++oooossssyyhhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMo/os/---:--///---:ooo+++/////+//+:---........``....---------...-//+///:::---::/+o+ohNNNNNNNNNNNNMMNmdhhhdddhhyyyyssooooo+++oooo+++++++ossyyyyhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMm+ss:::---:/+-.-.-/os++//////+//:---.-.......````....------...-//////:--.....-:/+++smNNNNmmNNNNNMMNmdhhyyhddhyyyyyssoooooooooooo+++++oossssyhhddMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMs+s///:---://:...-+so+/////////::--.......```````....-----...-//::--..--::---:/+/+omNNNNNNMMMMMMMNmdhyysyyhhhhyyyssssoooossoooo+++ooooosssyyhdmNNNNNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMmo+/:::///::/o-.../so+/////////::--.........``````....--------//:---:::/++///++///omNNNMMMMMMMMMNNNdhhyssssyyhhhyyssssoossssooooooooooosssyyhddyyyhhhhdmNMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMms/:::::-------..:oso////////::----.........``````....--------::::----/+++so/://+sNMMMMMMMMMMMMNNmdhhyssoosssyyhhhyssssssssssssssoooosssssyhmhyysyyyssyyhdNMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdo/::--......--:oso+//::::::::----...........```....--------------::oo/+s+/::/odMMMMMMMMMMMMNmmmdhyysssoooooosyyyyyyyyyssssyssssoosssssyhdhssyyssyyyyhhhhdmNMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmyo/:-......-:+so++//::::::------.............`....--..----------:/oo+oo+:/+hMMMMMMMMMMMMNmddddhyysooooo+o++ooossyyyhyyyysyssssssyyyyhhysssyhhhhyyssoossooymMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmdyo+:--...:+sso+//:::::/-------.--...................---------:/+s+os+/+hNNMMMMMMMMMMNmdhdhhhhysoooo+++++++++oooosyyhhyyyyyyyhhhhhsshhhhsooso+o++/+ooo+++ymMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdyso+///:--+sso+//::::---------...-...............```..--.----:/+ooos//sMMMMMMMMMMMMNmdhhyysyhysooo++++++++++++osoooosyyhddddmNyosys+++o+++oo/++////+o++/++dMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhyo/:--:+++sss++/::::----------..----........---.```.....---:/+oosss/oNMMMMMMNMMMMNmhhyyysssyysooo++++++++++++ooooooossyhhyhmNo/++////++/++o+/+///:/+o+///+dMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhys+/:--/o+osso+//::----:------------------------.......-:/++oosyyy/+hMMMMMMMNmhyddhyysssssssssoo+++++++/++++oooooooossyhyyhdh//+//:://+++o+o//+//:::/o+///oNMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhyso/:::/o++ooo+//::----------------------------:::://+osoo+:/++yho:sNMMMMNy+//sddhyssoooooooooo+++++///++++++oooooossyyyssyh/:///::::///+o+oo/++//:::/oo+osdMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdsso+/:::+o+++o+/::-----------------------------:/+ossooooooyhhhhs//dMMMMms:--..-//+oooooooo+++o++//////++++++oossssssssoo++::://::::::///+++oo+ooosyhhyshyssdMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhssoo//::++///++/::-----------------------------:/osoooooooooosyys/sMMMMm+:---....`.`.-://++++++////////++++++++oossso+/:---::/:/::::::://+syhhhdhhy+::::/+o+oNMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhsooo+/::////////:::-----------------------------:+sssooooooooooosydNMdo+/::-.......```````...--::::::::///////:/::--...-----::::::::/oyhhhss+/+oooo+/--:::/osdMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhyooso/::///::::/::--------------------------------:ossssooooooooosshy///::--.......``````````````````````..............-----:::::+shhs/://////:/++oso/:-:::/syMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhssooo//::/::-::::---.--:------------------.---------:/ossooooosssssyh+:::--.......````````..```````````````..........-------::oyys+::::::////////+++os+:--::++MMMMM
NNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMNysssoo+//:::----:------.....---------------------------://+oossyyyyyso/::----............./h:````....````.............-----/oyyo/::-:::::://::://://++ooo/:-:/+NMMMM
MMNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMNhssso+//:::----------:/.......---------....---.-----------:/+oyhddyo/:::-----------/////+++:-.-......................-:/oyys+:::-------::::::::://:::/++os+:::+mMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdysss+//::-----.-------........---------------------:-----::/+syhhs//::-----:+oooo+/--...........................-/osyso/:----------------::::::::::::+shhhyshyhMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmhsss+//::----....---.............-------------------::::://+ossys/:::-:+oss+/:--........```.................-/syyo/:----------------------:::::::/+shyo+/+osso+hMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmddyso+//:::---.....---............------------------::://++ossss/::/osso+:-..........`````````...........-/oyyo/--......--------------------:::/oyhy+/:::::/+oosymMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmdhdhso+///:::--......----.--..........---------------::::/+ossssooss+/:-........```````..```````.......:+syo/-........--..-----------------::+shyo/::::::::::+o++osdM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmdhyydyo+///::---.......-:-------.......------......-----:://++oso+/:-----.........````````````````..-/sys+:-............-..---------------:oyys+/::----:::::::/+++++sd
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhyysyhho+///:::--........-::::::--------------....--------::///oso:-----............````````````.-/osso:-....................-----------/oyys/:---::----::::::::/++//+o
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdyyysyyhs+///::---.........--:::////:::-----------....-----:/+//+o+-..................````..`.-:osso:-.......................--------:+syyo/:-------:---::::::::::/+++++
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmyssyssyyyo+//::--....-......---:://++++/:::--------...----:///::/+-......................-/+osso/-.```````.................-------/oyys/:-----------:---::::::::::/+hhyh
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhsssyssssys+//::--...........------:::::/+++//::::::-----::///////-...```.``....```..-/osss+/:-.....``````````..............---:+syy+/------------------:::::////oyhysooy
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdyssyyssssss+//::--..........--------------://+oooo++///////++++/:.....````````...-/oyys/-.`````......````````````..........-/oyys/:---------------------:::://oyhyo+//+sm
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNdhysssssooooso+/:---.........-------------------::/+sdmmdddhhhy+-.........````.-+syyo/-.````````````````...``````````....-:+sys+:-....-----------:-------::::+yhyo+/////++y
MMMMMMMNNNNNNNNNNNNNNNNNNNNmdhyyssssooo+ooo+/:---.........-----:::---..-----:::/ohNNNNdhs+:...```.......-:+yho:....```````````````````````````````.-/oyyo/-.........----------:--::-:::/shhs+/////+/+++o
MMMMMMNNmmmmmmmmmmmmmmmmmmmmdhyyssoooo+++o+/::---........-----:::::--.---::::/+ssdmmdd+:--....````````:syso/.````...```````````````````````````.-+sys/-..........-------------::::-:/oyhs+::/:////++++++
MMMMMNNmmmmmmmmmmmNmmmmmmmmmmmddhhyyssoo+o+/::---.......-----::://:------:::/+osymmmddd+--.-..````````/+-`....````....`````````````````````.-:oyyo:-............--------------:::/oyhs+:::::://///+++++/
MMMMNNNNNNNNmmmmmmmmddddmmmmmddddddddddhhhysso/::---....-----::///:-----::://osshmmmmdddo---...``````````..`...`````...`````````````````.:+sys/-.`..............-.------------/oyhs+::::::::::////+/+++/
MMNNNNNNNNNmmmmmmmdmmddhdmmmmmmddddddddddddhhhhhhhysoo+/::--:::///::--:::///+syyddmmmmddd+---..```````````````...````...````````````.-/syy+:.``````..............----------:+yhy+::::::::::::////++//+/+
MMNNNNNNNmmmmmmmmmmmmmdddhddmmmmdmdddddddddhhhhhhhhhhhhhhhysooo+++//////++osyhdddddmmmdddd+..--.``````````````````````....``````.-/oyyo:.````````````............-------:+yhy+::::::::::::://///+++/+oyd
MNNNNNmmmmmmmmmmmmddddddddhhhmmmmdddddddddddddhhhhhhhhhhhhhhhhhhhhhhhhhhhddddddddmddmmmdddh/..--..`````````````````````.-..`..:oyyo/.````````````````.............---:+shy+:--::::::::::::://///++oyhhs/
MNNNNmmmmmmmmmmmdmdddddddddddddhhhhhhhhdddddmmmddddhhhhhhhhhdhhhhhddddddddddddddddddddmddmdh:...--.```````````````.`````.-:+yyo/.````````````````````............--+yhy+:---:::::::::///////////ohhs////
NNNNmmmmmmmmmmmmddddddddhhhhhhhhhhhhhhhhhhhhddddmmddddhhhhhhhhhhhhdddddddddddddddddddddmddddh-.``.--.``````````````..``.:ods:.````````````````````````.`.......:+yhs/-------::::::::::///////+shyo/::///
NNNmmmmmmmmmmmddddhhhhhhhhhhhhhhhyyyyyyyyhyyhhhhhhdddddddddhhhhdddddddddddddddddddddddddmdmmdy-..-:/o/..`...``..-:/+h+ohho:--..`````````````````````````....:ohhs/-----------::::::::://///+ydy+///::://
NNmdmmmmmmmmddddhhhhhhhhhhhhhhhyhyyyyyyyyyhhhhhhyhhhhhhdddddddddddddddddddddddddddddddddmdmmdddyyss+//-/syyyosyys+/:-`......-..`````````````````````.``..:shyo:......-------::::::::::://+yds+/////::::/
Nmdmmmmmmmddddhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyhhhhyyhhhhhhhhhhhhhhhdhddhddddddddddddddddddmmmmmd+...`````-:-....`````````.....-...``````````````````..-+yhs/-........--------::-:::::://+yds////////::://
mdmmmmmmdddddhhhhhhhyhhhyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhyhhhhdddddddddddddhddddddddddddddddddmdmmd/..``.````.-.....```````......--..``````````````.-/shy+-............---------::--:::/+hds////////+/::://
]]--

PROFILER_ENABLED=false PROFILER_DATA={["numbers"]={},["functions"]={}}function Profiler_Toggle()if(PROFILER_ENABLED==true)then PROFILER_ENABLED=false else PROFILER_ENABLED=true end end
function Profiler_FunctionGetId(functionName)for i,profile in ipairs(PROFILER_DATA["functions"])do if(profile["name"]==functionName)then if(profile["request_reset"]==true)then Profiler_ResetFunction(i,functionName)end return i end end local newIndex=#PROFILER_DATA["functions"]+1 Profiler_ResetFunction(newIndex,functionName)return#PROFILER_DATA["functions"]end function Profiler_ResetFunction(index,functionName)local default_table={["name"]=functionName,["count"]=0,["time"]=0,["start_time"]=0,["updated"]=false,["last_change"]=World_GetGameTime(),["request_reset"]=false}PROFILER_DATA["functions"][index]=default_table end
function Profiler_StartFunction(functionName)if(PROFILER_ENABLED==false)then return end local index=Profiler_FunctionGetId(functionName)local startTime=Game_CurrentSystemTime()PROFILER_DATA["functions"][index]["start_time"]=startTime PROFILER_DATA["functions"][index]["updated"]=true PROFILER_DATA["functions"][index]["last_change"]=World_GetGameTime()end function Profiler_EndFunction(functionName)if(PROFILER_ENABLED==false)then return end local index=Profiler_FunctionGetId(functionName)local endTime=Game_CurrentSystemTime()if(PROFILER_DATA["functions"][index]~=nil)then local duration=(endTime-PROFILER_DATA["functions"][index]["start_time"])*1000 PROFILER_DATA["functions"][index]["count"]=PROFILER_DATA["functions"][index]["count"]+1 PROFILER_DATA["functions"][index]["time"]=PROFILER_DATA["functions"][index]["time"]+duration end end
function Profiler_NumberGetId(name)for i,profile in ipairs(PROFILER_DATA["numbers"])do if(profile["name"]==name)then return i end end local default_table={["name"]=name,["count"]=0,["updated"]=false,["last_change"]=World_GetGameTime(),}PROFILER_DATA["numbers"][#PROFILER_DATA["numbers"]+1]=default_table return#PROFILER_DATA["numbers"]end
function Profiler_Number(name,number)if(PROFILER_ENABLED==false)then return end local index=Profiler_NumberGetId(name)PROFILER_DATA["numbers"][index]["count"]=number PROFILER_DATA["numbers"][index]["updated"]=true PROFILER_DATA["numbers"][index]["last_change"]=World_GetGameTime()end function Profiler_NumberReset(name)if(PROFILER_ENABLED==false)then return end local index=Profiler_NumberGetId(name)PROFILER_DATA["numbers"][index]["count"]=0 PROFILER_DATA["numbers"][index]["updated"]=true PROFILER_DATA["numbers"][index]["last_change"]=World_GetGameTime()end function Profiler_NumberAdd(name,number)if(PROFILER_ENABLED==false)then return end local index=Profiler_NumberGetId(name)PROFILER_DATA["numbers"][index]["count"]=PROFILER_DATA["numbers"][index]["count"]+number PROFILER_DATA["numbers"][index]["updated"]=true PROFILER_DATA["numbers"][index]["last_change"]=World_GetGameTime()end function Profiler_NumberInc(name)if(PROFILER_ENABLED==false)then return end Profiler_NumberAdd(name,1)end
lastShowTime=0 function Profiler_ShowData()if(PROFILER_ENABLED==false)then return end local gameTime=World_GetGameTime()local line=0 for index,profile in ipairs(PROFILER_DATA["numbers"])do line=line+1 local profileName=profile["name"]local profileCount=profile["count"]local profileTime=profile["time"]local profileUpdated=profile["updated"]local profileLastChange=profile["last_change"]if(profileUpdated==true)then PROFILER_DATA["numbers"][index]["updated"]=false Util_ShowTextOnScreen("profilerNumber"..index,0.02,0.2+0.015*line,profileName,100,200,100,0,nil)if(profileCount~=nil)then Util_ShowTextOnScreen("profilerNumber"..index.."count",0.15,0.2+0.015*line,profileCount,100,200,100,0,nil)end if(profileTime~=nil)then Util_ShowTextOnScreen("profilerNumber"..index.."time",0.16,0.2+0.015*line,profileTime,100,200,100,0,nil)end end if(profileUpdated==false and gameTime-profileLastChange>10)then PROFILER_DATA["numbers"][index]["updated"]=nil if(profileCount~=nil)then Util_ShowTextOnScreen("profilerNumber"..index.."count",0.15,0.2+0.015*line,"-",100,200,100,0,nil)end end end line=line+1 for index,profile in ipairs(PROFILER_DATA["functions"])do line=line+1 local functionName=profile["name"]local functionCount=profile["count"]local functionTime=profile["time"]local functionUpdated=profile["updated"]local functionLastChange=profile["last_change"]if(functionUpdated==true)then PROFILER_DATA["functions"][index]["updated"]=false Util_ShowTextOnScreen("profilerFunction"..index,0.02,0.2+0.015*line,functionName,100,200,100,0,nil)if(functionCount~=nil)then Util_ShowTextOnScreen("profilerFunction"..index.."count",0.15,0.2+0.015*line,functionCount,100,200,100,0,nil)end if(functionTime~=nil)then Util_ShowTextOnScreen("profilerFunction"..index.."time",0.16,0.2+0.015*line,round(functionTime,3),100,200,100,0,nil)end end if(functionUpdated==false and gameTime-functionLastChange>10)then PROFILER_DATA["functions"][index]["updated"]=nil if(functionCount~=nil)then Util_ShowTextOnScreen("profilerFunction"..index.."count",0.15,0.2+0.015*line,"-",100,200,100,0,nil)end if(functionTime~=nil)then Util_ShowTextOnScreen("profilerFunction"..index.."time",0.16,0.2+0.015*line,"-",100,200,100,0,nil)end end PROFILER_DATA["functions"][index]["request_reset"]=true end timePassed=Game_CurrentSystemTime()-lastShowTime Util_ShowTextOnScreen("profilerTime",0.02,0.2+0.015*(line+2),timePassed,100,200,100,0,nil)lastShowTime=Game_CurrentSystemTime()end