--[[
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN/``.-:/+shdmNNNNMNNMMMMMMMNNMMMNmmNNNmmNmmmmmmmmmmmmmdhhhhhddmNNMMMMMMMMMMMMMMMMMMMMMMMMMNNNNmmmmmmm
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmNNNNNNNMMMMMMMNNMMMMMMMNNNMMNmmmmNNNNNmdhyyyhyssyo/--:://oydNMMMMMMNNNNNNNNNNNNNNNNNNNmmmmmmmmmmm
MNMNMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNMMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmMMMMMMMNNNMMNmmmdhyso+/://///+++os+---:/++oymNMMMMNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmm
NNNNNMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNmmmmmmmNMMMMMMNNNNNNMMMMMMMMMMMMMMMMMMMMMMMNmdhysoooooooosyyhddmNNNMMMNMMMMMNNNNNhNMMMMMMNmNNNmhso++///////:---::::+s+::://:+smNMMMMNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmm
NNNNNNNNMMMMMMMMMMMMMMNNNNNNNmmNmmmmmmmmmdmmNMMMMMNNNNNNNNNNNMMMMMMMMMMMNmhyo+:-````             ````.-/sdNNNmNNNNNNNNmNNMMMNNNmdhyyyyyyssosoo+++//:::-.-//---:::/omNMMMMNNNNNNNNmNmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNMMMMMMMMMMMMMMMNNNNNNNmmmmddhhyyyyyymNMMMMNmNNNNNNNNNNNNNNmdyo/-.``                            `.:ddmddmNNNNNNmNNNNNmmdhhysooo++++++/+//+++/:--.....----//omNNMMNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNMMMMMMMMMMMMNNNNNNNNNNNNNmmmdddhhyydNMMMMMmNNNNNNNNNdyo/-``                                   `.+mmNmdNNNNNNmmNNmdhyyysoo+++++/:///+//:-...........----//odNNNMNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNMMMMMMMMMMNNNNNNNNNNNNNNNNmmmmmmmmNNMMMMMNNNNmmho/-``                                        .-sNNNNmNNNNNNmmdhyyyo++/////://++/:-..``````.........---:/odmNNNMNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNNMMMMMMMMMNNNNNNNNNNNNNNNmmmmmmmmmNNMMMMMNdy+-.`                                            `.:dNNNNmNNNNmdhhyss+::::----..--..``````````...........-::/+hmNNNMNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNNNMMMMMMMMNNNNNNNNNNNmNmmmmmmmmmmmNNNNmho-`                                                 `-+NNNNNmNmdhyysso+-..-:-....```` ````````````..........--::+ymNNNMNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNNNNNMMMMMMNNNNNNNNNNNNNmmmmmmmmmmmmhs:.`                                                 ` `.:sNNNNNmhyyysso+:.``.--.```    ````````````````.........-::/smNNNMNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNNNNNMMMMMMNNNNNNNNNNNNNmNmmmmmmdy+-`                                                       `.:dMNNmhsosyso/-.```````       ` `````````````````.......-://odNNNMNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNNNNNNMMMMMNNNNNNNNNNNNmNmmmmdy/.`                                                       `  `./mNdhso++o+:..``````     ` ` `   ``````````````````...---::/+hmNNMNNNmmmmmmmmmmmmmmNmNNNNNNNNNMMM
NNNNNNNNNNNNNNNNNMMMMNNNNNNNNNNNmmmdy+-`                                                            ``-omdoso++/-.```````````` `     `  ``````````````````....--::/+yNNNMMNNNNNNNNNNNMNNMMMMMMMMMMMMMMMM
NNNNNNNNNNNNNNNNNMMMMNNNNNNNNNNNmh+-`````                                                    ``  `  `.-dNyoooo:..`````````````````` `````````` ````````````...--:/+oyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MNNNNNNNNNNNNNNNMMMMMNNNNNNNNmdo-`````````                                                       ````.:Ndo/++:-..``````````````````````````````````````````...-:/oydNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMNds/.``` `  ``                                                       ``````.+Ny/:+:-.```````````````````````````   `````````````..::+shmNNdddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNmho/.`````` ``  ````                                                `````.``..-oyhoo/-`````````````````````````````       ```````.-:/syhhhdhyyyhdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MNNMMMNNMMMNMMMMMMNmho/-.``````````````` ``                                           `  ```````..`--:--hh+.```````````````````````````        ``````..-:/+osoooossssyhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMNMMMNNNMMNds/-......``````````````  ``                                       `  `` ```````.-`.:/--/+```````````` `````````````````   ````````..-:/++oooooosssssyhhdmNMMMMMMMMMMMMMMMMMMMMMMMMNMMMM
MMMMMMMMMMMMNds/.........````````````````  ``                                         ``````````--..:/:/:```````````````````````````````````````...-:/+++++ooooooossssssyhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMmy/-.....-......```````````````` ```                                         ``````...--:::/:......`````````````````````````````...--::///+++++++++++ooo+++oosymNNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMNMMdo:-----------.....``````````` ``` ````                                   ```..---:://+osyhdyo:-....--..............``````````.-:////++/::::://///++++++++++oshdNNmNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMd+:--------------....``````` ```` ``` ````                            ```.--:::///////+++oosyhmds:------------......```````....:+o++////////:::://///++++++++oshhdhhhdNMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMm+-------------------...`````     ``  `` `````                    ```......---:::://////++++oooosydh+/:------------..``````...--+so++oossyyyyysssssoo+++++++++ossyhhhhhhmMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMNs/:--:::--------------..``````     ``  ```````               ``...........-----::::://///++++++oooshhsso+++////::-:::---....`./sssoosysoo++++ooososooo++//++++syhddhhdddmMMMNMNNNNNMMMMMMMMMMMMMMMMM
MMMMNdy/:::::-------------.-.`````     `````````````       `..-----.-.............---::::///+++++++++oosyhddhsysso+++//++:::-..`.:osyssso++///::///++++++++++//+oshdmmNmhhmNmMMNNNNNNMMMMMMMMMMMMMMMMMMM
MMMMMNNms/:::::----------.-.-.````````````````````    `.:++//:::----.-.-........-----::::////++++++++ooossyoymNdyyssooo++////+++ssoosyo+//////++ooossssooooo++//oydsdmmmhydmmNMNNMNNMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMms:::::--------..-.....```````````````````-/+ysso+/::::::------..---------..--::::///+++++++ooooymNMMMNdysssssooshdddyssssoss++++++ososyhyyyyysssssoo++oshyyyyyyyhddmNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMNs/:/:::------------......``````````:+syyyysso+/:::::::::--.--:://+++++/::---::::::////+++++oosdMMMMNhyssoyNMMMMNNmhyssssoo++++osyhmNdmy//oso//+oosooosyhhhyyyyyhhdmMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMms//::::----:::----......````.:oydmmddhhyso//:::::::::--://///:://///+++ooo+//:::::::://+++ooyNMMMmoosyysdNNMNNNmhysssso+///+oyyyhdddsosssso+oosssooossydhhhhhhhhdMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMms+/::--::///::----....-/ohmdmdmmddhhys+/:::::/://::::::--..........::/+o+/++:----:::////++odMMMmoso//shdNNNNNmdhyssoo+////++++++/+++ooooo+oosossoooosydhyyhhhhdNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNh+/+++/++//::---:+ydmNmmdmmddddyyso/::::://////::---...............--//////------:::///+oymMMNos+//+osydNNNmdyyysso+//////////+++ooo++++oooosssssssshhyyyyhhhNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMNdysoo+++///+shmNNmmmdhhdddhyyso+/:::::://///::--.........--------....----------:://+oydmmNMMhs///:+ssydNNmhysssso++///////++o+o++++++/+osssyyysssssyyssyyhdNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNNdyssosydNNNNmmmddhddhddhhys+//:::::::///::-......--::///++//:---........---:::/+osydmNmMMNs+++::+s+odNmhyyyyso++///////////+++++///oyyssyyso+/oosyyssyhdNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMNdddNNNNNmmNmdddmdddddhyys++/::/:::////:-...-.-:://+///++oso/:---.......-:///+ooosssymNMMdso+o++s+/smmmhyyyyso++/+////:::::::///++sssoooss+/:+ooysssyhmMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmNNNNNmmmdddddhhhssso//::://////:-....--://++os+-``.:/+/---....`..-/++o++///+osdNMMMhooso++o++hmmdhhhyysoo+++/////::::://+++osssssyyyoosshhysyydNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNmmdddhhdyssso+////////::-.....--:/:sddhdy-..-::/-.........-/so+///+ossydMMMMMmyo+////+ymmddhhhhssoo++++++++///+++++//+oooooosssyhddhyyydNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNMNNNmmdddyhhysoso/////////:---.---::://oyyyhs-.-://:...-------:/ooooo/+shdhmMMMMMMMmhso+//odmmddhhhyssoo++oo++++++++o+/////+++++++oshhhddyhmMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMmdyysydmNmmddhyhhyysso+////////::----------::---://////++/:::::::::::/+sdmds::ohdNNMMMMMMMMNNmhyshmNmddhhhysooo+ooo++++++++//++////++++oosyhdddyhNMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMNh++/++///osyhdyydhysso++///////:::-----------...----::///+/::::::::::::/+sooooosyhNMMMMMMMMMMMMmhyymNNmddhhysso++osooo++o+++++++++ooooosssyhdmmdydMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMh/::///::/::+yhsyddhsoo++////::/:::--:::------.....---:::/::::::::::---::/+o+++++shNNNNNNNNNNNMMNmhydmNmmdhhhyso+++osoo++++++oosssyyyyyyyyhdddmdhhNMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMm/--:++:-./+::+++syddyoo+////://::::--------------------:::::::::::::---:::/+o++++ohNNNMMMMMMMMMMMmdhhmmmmdhhyyyso+//oo++/+++syyhhhyyyyyyhhhhhdmdhmMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMh:-:+o+/:////-::/+osyyo++//:////:::--------......---------------:-::::::::::/+oo++osNMMMMMMMMMMMMMNmdhhdmddhhyyysoo+/+o++//++ooosssssssssysyyhddmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMm/:/so/:----/://:/+osoo+//////////:------...........--------------::::///::::/++o++smMMMMMMMMMMMMMMmddhhddddhhyyyss+++++++/++ooo+++oooossssyyhhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMo/os/---:--///---:ooo+++/////+//+:---........``....---------...-//+///:::---::/+o+ohNNNNNNNNNNNNMMNmdhhhdddhhyyyyssooooo+++oooo+++++++ossyyyyhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMm+ss:::---:/+-.-.-/os++//////+//:---.-.......````....------...-//////:--.....-:/+++smNNNNmmNNNNNMMNmdhhyyhddhyyyyyssoooooooooooo+++++oossssyhhddMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMs+s///:---://:...-+so+/////////::--.......```````....-----...-//::--..--::---:/+/+omNNNNNNMMMMMMMNmdhyysyyhhhhyyyssssoooossoooo+++ooooosssyyhdmNNNNNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMmo+/:::///::/o-.../so+/////////::--.........``````....--------//:---:::/++///++///omNNNMMMMMMMMMNNNdhhyssssyyhhhyyssssoossssooooooooooosssyyhddyyyhhhhdmNMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMms/:::::-------..:oso////////::----.........``````....--------::::----/+++so/://+sNMMMMMMMMMMMMNNmdhhyssoosssyyhhhyssssssssssssssoooosssssyhmhyysyyyssyyhdNMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdo/::--......--:oso+//::::::::----...........```....--------------::oo/+s+/::/odMMMMMMMMMMMMNmmmdhyysssoooooosyyyyyyyyyssssyssssoosssssyhdhssyyssyyyyhhhhdmNMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmyo/:-......-:+so++//::::::------.............`....--..----------:/oo+oo+:/+hMMMMMMMMMMMMNmddddhyysooooo+o++ooossyyyhyyyysyssssssyyyyhhysssyhhhhyyssoossooymMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmdyo+:--...:+sso+//:::::/-------.--...................---------:/+s+os+/+hNNMMMMMMMMMMNmdhdhhhhysoooo+++++++++oooosyyhhyyyyyyyhhhhhsshhhhsooso+o++/+ooo+++ymMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdyso+///:--+sso+//::::---------...-...............```..--.----:/+ooos//sMMMMMMMMMMMMNmdhhyysyhysooo++++++++++++osoooosyyhddddmNyosys+++o+++oo/++////+o++/++dMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhyo/:--:+++sss++/::::----------..----........---.```.....---:/+oosss/oNMMMMMMNMMMMNmhhyyysssyysooo++++++++++++ooooooossyhhyhmNo/++////++/++o+/+///:/+o+///+dMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhys+/:--/o+osso+//::----:------------------------.......-:/++oosyyy/+hMMMMMMMNmhyddhyysssssssssoo+++++++/++++oooooooossyhyyhdh//+//:://+++o+o//+//:::/o+///oNMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhyso/:::/o++ooo+//::----------------------------:::://+osoo+:/++yho:sNMMMMNy+//sddhyssoooooooooo+++++///++++++oooooossyyyssyh/:///::::///+o+oo/++//:::/oo+osdMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdsso+/:::+o+++o+/::-----------------------------:/+ossooooooyhhhhs//dMMMMms:--..-//+oooooooo+++o++//////++++++oossssssssoo++::://::::::///+++oo+ooosyhhyshyssdMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhssoo//::++///++/::-----------------------------:/osoooooooooosyys/sMMMMm+:---....`.`.-://++++++////////++++++++oossso+/:---::/:/::::::://+syhhhdhhy+::::/+o+oNMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhsooo+/::////////:::-----------------------------:+sssooooooooooosydNMdo+/::-.......```````...--::::::::///////:/::--...-----::::::::/oyhhhss+/+oooo+/--:::/osdMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhyooso/::///::::/::--------------------------------:ossssooooooooosshy///::--.......``````````````````````..............-----:::::+shhs/://////:/++oso/:-:::/syMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhssooo//::/::-::::---.--:------------------.---------:/ossooooosssssyh+:::--.......````````..```````````````..........-------::oyys+::::::////////+++os+:--::++MMMMM
NNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMNysssoo+//:::----:------.....---------------------------://+oossyyyyyso/::----............./h:````....````.............-----/oyyo/::-:::::://::://://++ooo/:-:/+NMMMM
MMNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMNhssso+//:::----------:/.......---------....---.-----------:/+oyhddyo/:::-----------/////+++:-.-......................-:/oyys+:::-------::::::::://:::/++os+:::+mMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdysss+//::-----.-------........---------------------:-----::/+syhhs//::-----:+oooo+/--...........................-/osyso/:----------------::::::::::::+shhhyshyhMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmhsss+//::----....---.............-------------------::::://+ossys/:::-:+oss+/:--........```.................-/syyo/:----------------------:::::::/+shyo+/+osso+hMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmddyso+//:::---.....---............------------------::://++ossss/::/osso+:-..........`````````...........-/oyyo/--......--------------------:::/oyhy+/:::::/+oosymMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmdhdhso+///:::--......----.--..........---------------::::/+ossssooss+/:-........```````..```````.......:+syo/-........--..-----------------::+shyo/::::::::::+o++osdM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmdhyydyo+///::---.......-:-------.......------......-----:://++oso+/:-----.........````````````````..-/sys+:-............-..---------------:oyys+/::----:::::::/+++++sd
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhyysyhho+///:::--........-::::::--------------....--------::///oso:-----............````````````.-/osso:-....................-----------/oyys/:---::----::::::::/++//+o
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdyyysyyhs+///::---.........--:::////:::-----------....-----:/+//+o+-..................````..`.-:osso:-.......................--------:+syyo/:-------:---::::::::::/+++++
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmyssyssyyyo+//::--....-......---:://++++/:::--------...----:///::/+-......................-/+osso/-.```````.................-------/oyys/:-----------:---::::::::::/+hhyh
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhsssyssssys+//::--...........------:::::/+++//::::::-----::///////-...```.``....```..-/osss+/:-.....``````````..............---:+syy+/------------------:::::////oyhysooy
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdyssyyssssss+//::--..........--------------://+oooo++///////++++/:.....````````...-/oyys/-.`````......````````````..........-/oyys/:---------------------:::://oyhyo+//+sm
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNdhysssssooooso+/:---.........-------------------::/+sdmmdddhhhy+-.........````.-+syyo/-.````````````````...``````````....-:+sys+:-....-----------:-------::::+yhyo+/////++y
MMMMMMMNNNNNNNNNNNNNNNNNNNNmdhyyssssooo+ooo+/:---.........-----:::---..-----:::/ohNNNNdhs+:...```.......-:+yho:....```````````````````````````````.-/oyyo/-.........----------:--::-:::/shhs+/////+/+++o
MMMMMMNNmmmmmmmmmmmmmmmmmmmmdhyyssoooo+++o+/::---........-----:::::--.---::::/+ssdmmdd+:--....````````:syso/.````...```````````````````````````.-+sys/-..........-------------::::-:/oyhs+::/:////++++++
MMMMMNNmmmmmmmmmmmNmmmmmmmmmmmddhhyyssoo+o+/::---.......-----::://:------:::/+osymmmddd+--.-..````````/+-`....````....`````````````````````.-:oyyo:-............--------------:::/oyhs+:::::://///+++++/
MMMMNNNNNNNNmmmmmmmmddddmmmmmddddddddddhhhysso/::---....-----::///:-----::://osshmmmmdddo---...``````````..`...`````...`````````````````.:+sys/-.`..............-.------------/oyhs+::::::::::////+/+++/
MMNNNNNNNNNmmmmmmmdmmddhdmmmmmmddddddddddddhhhhhhhysoo+/::--:::///::--:::///+syyddmmmmddd+---..```````````````...````...````````````.-/syy+:.``````..............----------:+yhy+::::::::::::////++//+/+
MMNNNNNNNmmmmmmmmmmmmmdddhddmmmmdmdddddddddhhhhhhhhhhhhhhhysooo+++//////++osyhdddddmmmdddd+..--.``````````````````````....``````.-/oyyo:.````````````............-------:+yhy+::::::::::::://///+++/+oyd
MNNNNNmmmmmmmmmmmmddddddddhhhmmmmdddddddddddddhhhhhhhhhhhhhhhhhhhhhhhhhhhddddddddmddmmmdddh/..--..`````````````````````.-..`..:oyyo/.````````````````.............---:+shy+:--::::::::::::://///++oyhhs/
MNNNNmmmmmmmmmmmdmdddddddddddddhhhhhhhhdddddmmmddddhhhhhhhhhdhhhhhddddddddddddddddddddmddmdh:...--.```````````````.`````.-:+yyo/.````````````````````............--+yhy+:---:::::::::///////////ohhs////
NNNNmmmmmmmmmmmmddddddddhhhhhhhhhhhhhhhhhhhhddddmmddddhhhhhhhhhhhhdddddddddddddddddddddmddddh-.``.--.``````````````..``.:ods:.````````````````````````.`.......:+yhs/-------::::::::::///////+shyo/::///
NNNmmmmmmmmmmmddddhhhhhhhhhhhhhhhyyyyyyyyhyyhhhhhhdddddddddhhhhdddddddddddddddddddddddddmdmmdy-..-:/o/..`...``..-:/+h+ohho:--..`````````````````````````....:ohhs/-----------::::::::://///+ydy+///::://
NNmdmmmmmmmmddddhhhhhhhhhhhhhhhyhyyyyyyyyyhhhhhhyhhhhhhdddddddddddddddddddddddddddddddddmdmmdddyyss+//-/syyyosyys+/:-`......-..`````````````````````.``..:shyo:......-------::::::::::://+yds+/////::::/
Nmdmmmmmmmddddhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyhhhhyyhhhhhhhhhhhhhhhdhddhddddddddddddddddddmmmmmd+...`````-:-....`````````.....-...``````````````````..-+yhs/-........--------::-:::::://+yds////////::://
mdmmmmmmdddddhhhhhhhyhhhyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhyhhhhdddddddddddddhddddddddddddddddddmdmmd/..``.````.-.....```````......--..``````````````.-/shy+-............---------::--:::/+hds////////+/::://
]]--

INFANTRY_SLOTITEMS={{["blueprint"]="dp-28_light_machine_gun_package_moving_mp",["points"]=1},{["blueprint"]="obersoldaten_mg34_lmg_moving_mp",["points"]=1},{["blueprint"]="grenadier_mg42_lmg_moving_mp",["points"]=1},{["blueprint"]="bazooka_mp",["points"]=2,["movement_type"]="attack_move"},{["blueprint"]="panzershreck_mp",["points"]=2,["movement_type"]="attack_move"},}SURVIVAL_UNIT_LIST={["soviet"]={
{["blueprint"]="combat_engineer_squad_mp",["points"]=1,["items"]=INFANTRY_SLOTITEMS,["upgrades"]={{["blueprint"]="engineer_flamethrower_mp",["points"]=2},{["blueprint"]="engineer_minesweeper_mp",["points"]=2},}},{["blueprint"]="conscript_squad_mp",["points"]=2,["items"]=INFANTRY_SLOTITEMS},{["blueprint"]="partisans_lmg_mp",["points"]=2,["items"]=INFANTRY_SLOTITEMS},{["blueprint"]="partisans_panzerschreck_mp",["points"]=2,},{["blueprint"]="partisans_ptrs_mp",["points"]=2,},{["blueprint"]="partisans_rifle_mp",["points"]=2,},{["blueprint"]="partisans_smg_mp",["points"]=2,},{["blueprint"]="sniper_team_mp",["points"]=2,},{["blueprint"]="commissar_squad_mp",["points"]=1,["items"]=INFANTRY_SLOTITEMS},{["blueprint"]="guards_troops_mp",["points"]=3,["items"]=INFANTRY_SLOTITEMS},{["blueprint"]="penal_battalion_mp",["points"]=2,["items"]=INFANTRY_SLOTITEMS},{["blueprint"]="shock_troops_mp",["points"]=3,["items"]=INFANTRY_SLOTITEMS},
{["blueprint"]="is-2_mp",["points"]=20,["upgrades"]={{["blueprint"]="is2_top_gunner_mp",["points"]=3},}},{["blueprint"]="isu-152_mp",["points"]=15,["upgrades"]={{["blueprint"]="isu152_top_gunner_mp",["points"]=3},}},{["blueprint"]="katyusha_bm-13n_squad_mp",["points"]=4,},{["blueprint"]="kv-1_mp",["points"]=12,},{["blueprint"]="kv-2_mp",["points"]=20,},{["blueprint"]="kv-8_mp",["points"]=12,},{["blueprint"]="m3a1_scout_car_squad_mp",["points"]=4,},{["blueprint"]="m5_halftrack_squad_mp",["points"]=6,["upgrades"]={{["blueprint"]="m5_halftrack_72k_aa_gun_package_mp",["points"]=3},}},{["blueprint"]="soviet_76mm_sherman_mp",["points"]=12,["upgrades"]={{["blueprint"]="sherman_soviet_top_gunner",["points"]=3},}},{["blueprint"]="su-76m_mp",["points"]=8,},{["blueprint"]="su-85_mp",["points"]=8,},{["blueprint"]="t_34_76_squad_mp",["points"]=12,},{["blueprint"]="t_34_85_squad_mp",["points"]=12,},{["blueprint"]="t-70m_mp",["points"]=8,},
{["blueprint"]="m1937_53-k_45mm_at_gun_squad_mp",["points"]=7,["movement_type"]="attack_move"},{["blueprint"]="m1942_zis-3_76mm_at_gun_squad_mp",["points"]=8,["movement_type"]="attack_move"},{["blueprint"]="hm-120_38_mortar_squad_mp",["points"]=4,["movement_type"]="attack_move"},{["blueprint"]="pm-82_41_mortar_squad_mp",["points"]=4,["movement_type"]="attack_move"},{["blueprint"]="m1910_maxim_heavy_machine_gun_squad_mp",["points"]=4,["movement_type"]="attack_move"},{["blueprint"]="dshk_38_hmg_squad_mp",["points"]=4,["movement_type"]="attack_move"},},["aef"]={
{["blueprint"]="assault_engineer_squad_mp",["points"]=1,["items"]=INFANTRY_SLOTITEMS,["upgrades"]={{["blueprint"]="assault_engineer_flamethrower",["points"]=2},{["blueprint"]="minesweeper_upgrade_mp",["points"]=2},}},{["blueprint"]="captain_squad_mp",["points"]=2,["items"]=INFANTRY_SLOTITEMS},{["blueprint"]="lieutenant_squad_mp",["points"]=2,["items"]=INFANTRY_SLOTITEMS},{["blueprint"]="major_squad_mp",["points"]=2,["items"]=INFANTRY_SLOTITEMS},{["blueprint"]="paratrooper_squad_mp",["points"]=2,["items"]=INFANTRY_SLOTITEMS,["upgrades"]={{["blueprint"]="paratrooper_thompson_sub_machine_gun_upgrade_mp",["points"]=2},}},{["blueprint"]="pathfinder_squad_mp",["points"]=2,["items"]=INFANTRY_SLOTITEMS},{["blueprint"]="ranger_squad_mp",["points"]=2,["items"]=INFANTRY_SLOTITEMS},{["blueprint"]="rear_echelon_squad_mp",["points"]=2,["items"]=INFANTRY_SLOTITEMS},{["blueprint"]="riflemen_squad_mp",["points"]=2,["items"]=INFANTRY_SLOTITEMS,["upgrades"]={{["blueprint"]="riflemen_flamethrower",["points"]=3},}},
{["blueprint"]="dodge_wc51_50cal_squad_mp",["points"]=5,},{["blueprint"]="m10_tank_destroyer_squad_mp",["points"]=12,},{["blueprint"]="m20_utility_car_squad_mp",["points"]=6,["upgrades"]={{["blueprint"]="m20_side_skirts_mp",["points"]=3},}},{["blueprint"]="m15a1_aa_halftrack_squad_mp",["points"]=7,},{["blueprint"]="m36_tank_destroyer_squad_mp",["points"]=19,
},{["blueprint"]="m4a3_sherman_squad_mp",["points"]=18,["upgrades"]={{["blueprint"]="sherman_top_gunner_mp",["points"]=3},}},{["blueprint"]="m4a3e8_sherman_easy_8_squad_mp",["points"]=18,["upgrades"]={{["blueprint"]="sherman_top_gunner_mp",["points"]=3},}},{["blueprint"]="m4a3_76mm_sherman_bulldozer_squad_mp",["points"]=18,["upgrades"]={{["blueprint"]="sherman_top_gunner_mp",["points"]=3},}},{["blueprint"]="m5a1_stuart_squad_mp",["points"]=7,},
{["blueprint"]="m8_greyhound_squad_mp",["points"]=7,["upgrades"]={{["blueprint"]="m8_greyhound_side_skirts_mp",["points"]=2},{["blueprint"]="m8_top_gunner_mp",["points"]=3},}},{["blueprint"]="m8a1_hmc_squad_mp",["points"]=10,},
{["blueprint"]="m1_57mm_at_gun_squad_mp",["points"]=7,["movement_type"]="attack_move"},{["blueprint"]="m1_81mm_mortar_squad_mp",["points"]=4,["movement_type"]="attack_move"},{["blueprint"]="m1919a4_hmg_squad_mp",["points"]=4,["movement_type"]="attack_move"},{["blueprint"]="m2_60mm_mortar_squad_mp",["points"]=4,["movement_type"]="attack_move"},{["blueprint"]="m2hb_50cal_hmg_squad_mp",["points"]=4,["movement_type"]="attack_move"},},["german"]={
{["blueprint"]="pioneer_squad_mp",["points"]=1,["items"]=INFANTRY_SLOTITEMS,["upgrades"]={{["blueprint"]="pioneer_flamethrower_mp",["points"]=2},{["blueprint"]="pioneer_minesweeper_mp",["points"]=2},}},{["blueprint"]="ostruppen_squad_mp",["points"]=2,["items"]=INFANTRY_SLOTITEMS},{["blueprint"]="grenadier_squad_mp",["points"]=2,["items"]=INFANTRY_SLOTITEMS},{["blueprint"]="panzer_grenadier_squad_mp",["points"]=2,["items"]=INFANTRY_SLOTITEMS},{["blueprint"]="stormtrooper_squad_mp",["points"]=3,["items"]=INFANTRY_SLOTITEMS},{["blueprint"]="assault_officer_squad_mp",["points"]=1,["items"]=INFANTRY_SLOTITEMS},{["blueprint"]="sniper_squad_mp",["points"]=2},
{["blueprint"]="scoutcar_sdkfz222_mp",["points"]=7,["upgrades"]={{["blueprint"]="sdkfz_222_20mm_gun_mp",["points"]=2},}},{["blueprint"]="puma_east_german_mp",["points"]=11},{["blueprint"]="stug_iii_squad_mp",["points"]=9,["upgrades"]={{["blueprint"]="stug_top_gunner_mp",["points"]=3},}},{["blueprint"]="ostwind_squad_mp",["points"]=12},{["blueprint"]="panzer_iv_squad_mp",["points"]=13,["upgrades"]={{["blueprint"]="panzer_top_gunner_mp",["points"]=3},}},{["blueprint"]="panther_squad_mp",["points"]=20,["upgrades"]={{["blueprint"]="panther_top_gunner_mp",["points"]=3},}},{["blueprint"]="tiger_squad_mp",["points"]=21,["upgrades"]={{["blueprint"]="tiger_top_gunner_mp",["points"]=3},}},{["blueprint"]="tiger_ace_squad_mp",["points"]=22},{["blueprint"]="panzerwerfer_squad_mp",["points"]=6},{["blueprint"]="opel_blitz_supply_squad",["points"]=4},{["blueprint"]="mechanized_250_halftrack_grenadiers_mp",["points"]=6},{["blueprint"]="sdkfz_251_halftrack_squad_mp",["points"]=5,["upgrades"]={{["blueprint"]="sdkfz_251_halftrack_flammpanzerwagen_upgrade_mp",["points"]=3},}},{["blueprint"]="sdkfz_221_light_at_halftrack",["points"]=5},{["blueprint"]="elefant_tank_destroyer_squad_mp",["points"]=14,["modifiers"]={["speed"]=1.4}},{["blueprint"]="brummbar_squad_mp",["points"]=15,["upgrades"]={{["blueprint"]="brummbar_top_gunner_mp",["points"]=3},}},
{["blueprint"]="mg42_heavy_machine_gun_squad_mp",["points"]=4,["movement_type"]="attack_move"},{["blueprint"]="mortar_team_81mm_mp",["points"]=7,["movement_type"]="attack_move"},{["blueprint"]="pak40_75mm_at_gun_squad_mp",["points"]=7,["movement_type"]="attack_move"},},["west_german"]={
{["blueprint"]="assault_pioneer_squad_mp",["points"]=2,["items"]=INFANTRY_SLOTITEMS},{["blueprint"]="volksgrenadier_squad_mp",["points"]=2,["items"]=INFANTRY_SLOTITEMS},{["blueprint"]="fallschirmjager_squad_mp",["points"]=3,["items"]=INFANTRY_SLOTITEMS},{["blueprint"]="jaeger_light_infantry_recon_squad_mp",["points"]=2,["items"]=INFANTRY_SLOTITEMS},{["blueprint"]="panzerfusilier_squad_mp",["points"]=2,["items"]=INFANTRY_SLOTITEMS,["upgrades"]={{["blueprint"]="panzerfusilier_g43",["points"]=2},}},{["blueprint"]="obersoldaten_squad_mp",["points"]=3,["items"]=INFANTRY_SLOTITEMS,["upgrades"]={{["blueprint"]="waffen_infrared_stg44",["points"]=2},}},{["blueprint"]="urban_assault_light_infantry",["points"]=2,["items"]=INFANTRY_SLOTITEMS},{["blueprint"]="field_officer_squad_mp",["points"]=2,["items"]=INFANTRY_SLOTITEMS},
{["blueprint"]="kubelwagen_squad_mp",["points"]=4,},{["blueprint"]="king_tiger_squad_mp",["points"]=20,["modifiers"]={["speed"]=1.1},["upgrades"]={{["blueprint"]="king_tiger_top_gunner_mp",["points"]=3},{["blueprint"]="tank_commander",["points"]=2},}},{["blueprint"]="sdkfz_251_17_flak_halftrack_squad_mp",["points"]=5},{["blueprint"]="sdkfz_251_20_ir_searchlight_halftrack_squad_mp",["points"]=5},{["blueprint"]="mortar_250_halftrack_squad_westgerman_mp",["points"]=5},{["blueprint"]="jagdpanzer_tank_destroyer_squad_mp",["points"]=12},{["blueprint"]="jagdtiger_td_squad_mp",["points"]=15},{["blueprint"]="ostwind_squad_westgerman_mp",["points"]=12},{["blueprint"]="panther_commander_squad_mp",["points"]=22,["upgrades"]={{["blueprint"]="wg_panther_top_gunner_mp",["points"]=3},{["blueprint"]="tank_commander",["points"]=2},}},{["blueprint"]="panzer_ii_luchs_squad_mp",["points"]=8},{["blueprint"]="panzer_iv_ausf_j_battle_group_mp",["points"]=14,["upgrades"]={{["blueprint"]="panzer_iv_side_skirts_mp",["points"]=4},{["blueprint"]="tank_commander",["points"]=2},}},{["blueprint"]="armored_car_sdkfz_234_squad_mp",["points"]=11},{["blueprint"]="sturmtiger_squad_mp",["points"]=15},{["blueprint"]="sws_halftrack_squad_mp",["points"]=6},
{["blueprint"]="pak40_75mm_at_gun_squad_wg_mp",["points"]=7,["movement_type"]="attack_move"},{["blueprint"]="raketenwerfer43_88mm_puppchen_antitank_gun_squad_mp",["points"]=7,["movement_type"]="attack_move"},{["blueprint"]="grw34_81mm_mortar_squad_mp",["points"]=7,["movement_type"]="attack_move"},{["blueprint"]="le_ig_18_inf_support_gun_squad_mp",["points"]=7,["movement_type"]="attack_move"},{["blueprint"]="mg34_heavy_machine_gun_squad_mp",["points"]=4,["movement_type"]="attack_move"},{["blueprint"]="mg42_heavy_machine_gun_squad_wg_mp",["points"]=4,["movement_type"]="attack_move"},}}
