--[[
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN/``.-:/+shdmNNNNMNNMMMMMMMNNMMMNmmNNNmmNmmmmmmmmmmmmmdhhhhhddmNNMMMMMMMMMMMMMMMMMMMMMMMMMNNNNmmmmmmm
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmNNNNNNNMMMMMMMNNMMMMMMMNNNMMNmmmmNNNNNmdhyyyhyssyo/--:://oydNMMMMMMNNNNNNNNNNNNNNNNNNNmmmmmmmmmmm
MNMNMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNMMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmMMMMMMMNNNMMNmmmdhyso+/://///+++os+---:/++oymNMMMMNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmm
NNNNNMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNmmmmmmmNMMMMMMNNNNNNMMMMMMMMMMMMMMMMMMMMMMMNmdhysoooooooosyyhddmNNNMMMNMMMMMNNNNNhNMMMMMMNmNNNmhso++///////:---::::+s+::://:+smNMMMMNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmm
NNNNNNNNMMMMMMMMMMMMMMNNNNNNNmmNmmmmmmmmmdmmNMMMMMNNNNNNNNNNNMMMMMMMMMMMNmhyo+:-````             ````.-/sdNNNmNNNNNNNNmNNMMMNNNmdhyyyyyyssosoo+++//:::-.-//---:::/omNMMMMNNNNNNNNmNmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNMMMMMMMMMMMMMMMNNNNNNNmmmmddhhyyyyyymNMMMMNmNNNNNNNNNNNNNNmdyo/-.``                            `.:ddmddmNNNNNNmNNNNNmmdhhysooo++++++/+//+++/:--.....----//omNNMMNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNMMMMMMMMMMMMNNNNNNNNNNNNNmmmdddhhyydNMMMMMmNNNNNNNNNdyo/-``                                   `.+mmNmdNNNNNNmmNNmdhyyysoo+++++/:///+//:-...........----//odNNNMNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNMMMMMMMMMMNNNNNNNNNNNNNNNNmmmmmmmmNNMMMMMNNNNmmho/-``                                        .-sNNNNmNNNNNNmmdhyyyo++/////://++/:-..``````.........---:/odmNNNMNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNNMMMMMMMMMNNNNNNNNNNNNNNNmmmmmmmmmNNMMMMMNdy+-.`                                            `.:dNNNNmNNNNmdhhyss+::::----..--..``````````...........-::/+hmNNNMNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNNNMMMMMMMMNNNNNNNNNNNmNmmmmmmmmmmmNNNNmho-`                                                 `-+NNNNNmNmdhyysso+-..-:-....```` ````````````..........--::+ymNNNMNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNNNNNMMMMMMNNNNNNNNNNNNNmmmmmmmmmmmmhs:.`                                                 ` `.:sNNNNNmhyyysso+:.``.--.```    ````````````````.........-::/smNNNMNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNNNNNMMMMMMNNNNNNNNNNNNNmNmmmmmmdy+-`                                                       `.:dMNNmhsosyso/-.```````       ` `````````````````.......-://odNNNMNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNNNNNNMMMMMNNNNNNNNNNNNmNmmmmdy/.`                                                       `  `./mNdhso++o+:..``````     ` ` `   ``````````````````...---::/+hmNNMNNNmmmmmmmmmmmmmmNmNNNNNNNNNMMM
NNNNNNNNNNNNNNNNNMMMMNNNNNNNNNNNmmmdy+-`                                                            ``-omdoso++/-.```````````` `     `  ``````````````````....--::/+yNNNMMNNNNNNNNNNNMNNMMMMMMMMMMMMMMMM
NNNNNNNNNNNNNNNNNMMMMNNNNNNNNNNNmh+-`````                                                    ``  `  `.-dNyoooo:..`````````````````` `````````` ````````````...--:/+oyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MNNNNNNNNNNNNNNNMMMMMNNNNNNNNmdo-`````````                                                       ````.:Ndo/++:-..``````````````````````````````````````````...-:/oydNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMNds/.``` `  ``                                                       ``````.+Ny/:+:-.```````````````````````````   `````````````..::+shmNNdddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNmho/.`````` ``  ````                                                `````.``..-oyhoo/-`````````````````````````````       ```````.-:/syhhhdhyyyhdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MNNMMMNNMMMNMMMMMMNmho/-.``````````````` ``                                           `  ```````..`--:--hh+.```````````````````````````        ``````..-:/+osoooossssyhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMNMMMNNNMMNds/-......``````````````  ``                                       `  `` ```````.-`.:/--/+```````````` `````````````````   ````````..-:/++oooooosssssyhhdmNMMMMMMMMMMMMMMMMMMMMMMMMNMMMM
MMMMMMMMMMMMNds/.........````````````````  ``                                         ``````````--..:/:/:```````````````````````````````````````...-:/+++++ooooooossssssyhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMmy/-.....-......```````````````` ```                                         ``````...--:::/:......`````````````````````````````...--::///+++++++++++ooo+++oosymNNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMNMMdo:-----------.....``````````` ``` ````                                   ```..---:://+osyhdyo:-....--..............``````````.-:////++/::::://///++++++++++oshdNNmNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMd+:--------------....``````` ```` ``` ````                            ```.--:::///////+++oosyhmds:------------......```````....:+o++////////:::://///++++++++oshhdhhhdNMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMm+-------------------...`````     ``  `` `````                    ```......---:::://////++++oooosydh+/:------------..``````...--+so++oossyyyyysssssoo+++++++++ossyhhhhhhmMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMNs/:--:::--------------..``````     ``  ```````               ``...........-----::::://///++++++oooshhsso+++////::-:::---....`./sssoosysoo++++ooososooo++//++++syhddhhdddmMMMNMNNNNNMMMMMMMMMMMMMMMMM
MMMMNdy/:::::-------------.-.`````     `````````````       `..-----.-.............---::::///+++++++++oosyhddhsysso+++//++:::-..`.:osyssso++///::///++++++++++//+oshdmmNmhhmNmMMNNNNNNMMMMMMMMMMMMMMMMMMM
MMMMMNNms/:::::----------.-.-.````````````````````    `.:++//:::----.-.-........-----::::////++++++++ooossyoymNdyyssooo++////+++ssoosyo+//////++ooossssooooo++//oydsdmmmhydmmNMNNMNNMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMms:::::--------..-.....```````````````````-/+ysso+/::::::------..---------..--::::///+++++++ooooymNMMMNdysssssooshdddyssssoss++++++ososyhyyyyysssssoo++oshyyyyyyyhddmNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMNs/:/:::------------......``````````:+syyyysso+/:::::::::--.--:://+++++/::---::::::////+++++oosdMMMMNhyssoyNMMMMNNmhyssssoo++++osyhmNdmy//oso//+oosooosyhhhyyyyyhhdmMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMms//::::----:::----......````.:oydmmddhhyso//:::::::::--://///:://///+++ooo+//:::::::://+++ooyNMMMmoosyysdNNMNNNmhysssso+///+oyyyhdddsosssso+oosssooossydhhhhhhhhdMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMms+/::--::///::----....-/ohmdmdmmddhhys+/:::::/://::::::--..........::/+o+/++:----:::////++odMMMmoso//shdNNNNNmdhyssoo+////++++++/+++ooooo+oosossoooosydhyyhhhhdNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNh+/+++/++//::---:+ydmNmmdmmddddyyso/::::://////::---...............--//////------:::///+oymMMNos+//+osydNNNmdyyysso+//////////+++ooo++++oooosssssssshhyyyyhhhNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMNdysoo+++///+shmNNmmmdhhdddhyyso+/:::::://///::--.........--------....----------:://+oydmmNMMhs///:+ssydNNmhysssso++///////++o+o++++++/+osssyyysssssyyssyyhdNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNNdyssosydNNNNmmmddhddhddhhys+//:::::::///::-......--::///++//:---........---:::/+osydmNmMMNs+++::+s+odNmhyyyyso++///////////+++++///oyyssyyso+/oosyyssyhdNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMNdddNNNNNmmNmdddmdddddhyys++/::/:::////:-...-.-:://+///++oso/:---.......-:///+ooosssymNMMdso+o++s+/smmmhyyyyso++/+////:::::::///++sssoooss+/:+ooysssyhmMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmNNNNNmmmdddddhhhssso//::://////:-....--://++os+-``.:/+/---....`..-/++o++///+osdNMMMhooso++o++hmmdhhhyysoo+++/////::::://+++osssssyyyoosshhysyydNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNmmdddhhdyssso+////////::-.....--:/:sddhdy-..-::/-.........-/so+///+ossydMMMMMmyo+////+ymmddhhhhssoo++++++++///+++++//+oooooosssyhddhyyydNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNMNNNmmdddyhhysoso/////////:---.---::://oyyyhs-.-://:...-------:/ooooo/+shdhmMMMMMMMmhso+//odmmddhhhyssoo++oo++++++++o+/////+++++++oshhhddyhmMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMmdyysydmNmmddhyhhyysso+////////::----------::---://////++/:::::::::::/+sdmds::ohdNNMMMMMMMMNNmhyshmNmddhhhysooo+ooo++++++++//++////++++oosyhdddyhNMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMNh++/++///osyhdyydhysso++///////:::-----------...----::///+/::::::::::::/+sooooosyhNMMMMMMMMMMMMmhyymNNmddhhysso++osooo++o+++++++++ooooosssyhdmmdydMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMh/::///::/::+yhsyddhsoo++////::/:::--:::------.....---:::/::::::::::---::/+o+++++shNNNNNNNNNNNMMNmhydmNmmdhhhyso+++osoo++++++oosssyyyyyyyyhdddmdhhNMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMm/--:++:-./+::+++syddyoo+////://::::--------------------:::::::::::::---:::/+o++++ohNNNMMMMMMMMMMMmdhhmmmmdhhyyyso+//oo++/+++syyhhhyyyyyyhhhhhdmdhmMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMh:-:+o+/:////-::/+osyyo++//:////:::--------......---------------:-::::::::::/+oo++osNMMMMMMMMMMMMMNmdhhdmddhhyyysoo+/+o++//++ooosssssssssysyyhddmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMm/:/so/:----/://:/+osoo+//////////:------...........--------------::::///::::/++o++smMMMMMMMMMMMMMMmddhhddddhhyyyss+++++++/++ooo+++oooossssyyhhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMo/os/---:--///---:ooo+++/////+//+:---........``....---------...-//+///:::---::/+o+ohNNNNNNNNNNNNMMNmdhhhdddhhyyyyssooooo+++oooo+++++++ossyyyyhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMm+ss:::---:/+-.-.-/os++//////+//:---.-.......````....------...-//////:--.....-:/+++smNNNNmmNNNNNMMNmdhhyyhddhyyyyyssoooooooooooo+++++oossssyhhddMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMs+s///:---://:...-+so+/////////::--.......```````....-----...-//::--..--::---:/+/+omNNNNNNMMMMMMMNmdhyysyyhhhhyyyssssoooossoooo+++ooooosssyyhdmNNNNNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMmo+/:::///::/o-.../so+/////////::--.........``````....--------//:---:::/++///++///omNNNMMMMMMMMMNNNdhhyssssyyhhhyyssssoossssooooooooooosssyyhddyyyhhhhdmNMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMms/:::::-------..:oso////////::----.........``````....--------::::----/+++so/://+sNMMMMMMMMMMMMNNmdhhyssoosssyyhhhyssssssssssssssoooosssssyhmhyysyyyssyyhdNMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdo/::--......--:oso+//::::::::----...........```....--------------::oo/+s+/::/odMMMMMMMMMMMMNmmmdhyysssoooooosyyyyyyyyyssssyssssoosssssyhdhssyyssyyyyhhhhdmNMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmyo/:-......-:+so++//::::::------.............`....--..----------:/oo+oo+:/+hMMMMMMMMMMMMNmddddhyysooooo+o++ooossyyyhyyyysyssssssyyyyhhysssyhhhhyyssoossooymMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmdyo+:--...:+sso+//:::::/-------.--...................---------:/+s+os+/+hNNMMMMMMMMMMNmdhdhhhhysoooo+++++++++oooosyyhhyyyyyyyhhhhhsshhhhsooso+o++/+ooo+++ymMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdyso+///:--+sso+//::::---------...-...............```..--.----:/+ooos//sMMMMMMMMMMMMNmdhhyysyhysooo++++++++++++osoooosyyhddddmNyosys+++o+++oo/++////+o++/++dMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhyo/:--:+++sss++/::::----------..----........---.```.....---:/+oosss/oNMMMMMMNMMMMNmhhyyysssyysooo++++++++++++ooooooossyhhyhmNo/++////++/++o+/+///:/+o+///+dMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhys+/:--/o+osso+//::----:------------------------.......-:/++oosyyy/+hMMMMMMMNmhyddhyysssssssssoo+++++++/++++oooooooossyhyyhdh//+//:://+++o+o//+//:::/o+///oNMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhyso/:::/o++ooo+//::----------------------------:::://+osoo+:/++yho:sNMMMMNy+//sddhyssoooooooooo+++++///++++++oooooossyyyssyh/:///::::///+o+oo/++//:::/oo+osdMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdsso+/:::+o+++o+/::-----------------------------:/+ossooooooyhhhhs//dMMMMms:--..-//+oooooooo+++o++//////++++++oossssssssoo++::://::::::///+++oo+ooosyhhyshyssdMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhssoo//::++///++/::-----------------------------:/osoooooooooosyys/sMMMMm+:---....`.`.-://++++++////////++++++++oossso+/:---::/:/::::::://+syhhhdhhy+::::/+o+oNMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhsooo+/::////////:::-----------------------------:+sssooooooooooosydNMdo+/::-.......```````...--::::::::///////:/::--...-----::::::::/oyhhhss+/+oooo+/--:::/osdMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhyooso/::///::::/::--------------------------------:ossssooooooooosshy///::--.......``````````````````````..............-----:::::+shhs/://////:/++oso/:-:::/syMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhssooo//::/::-::::---.--:------------------.---------:/ossooooosssssyh+:::--.......````````..```````````````..........-------::oyys+::::::////////+++os+:--::++MMMMM
NNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMNysssoo+//:::----:------.....---------------------------://+oossyyyyyso/::----............./h:````....````.............-----/oyyo/::-:::::://::://://++ooo/:-:/+NMMMM
MMNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMNhssso+//:::----------:/.......---------....---.-----------:/+oyhddyo/:::-----------/////+++:-.-......................-:/oyys+:::-------::::::::://:::/++os+:::+mMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdysss+//::-----.-------........---------------------:-----::/+syhhs//::-----:+oooo+/--...........................-/osyso/:----------------::::::::::::+shhhyshyhMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmhsss+//::----....---.............-------------------::::://+ossys/:::-:+oss+/:--........```.................-/syyo/:----------------------:::::::/+shyo+/+osso+hMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmddyso+//:::---.....---............------------------::://++ossss/::/osso+:-..........`````````...........-/oyyo/--......--------------------:::/oyhy+/:::::/+oosymMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmdhdhso+///:::--......----.--..........---------------::::/+ossssooss+/:-........```````..```````.......:+syo/-........--..-----------------::+shyo/::::::::::+o++osdM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmdhyydyo+///::---.......-:-------.......------......-----:://++oso+/:-----.........````````````````..-/sys+:-............-..---------------:oyys+/::----:::::::/+++++sd
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhyysyhho+///:::--........-::::::--------------....--------::///oso:-----............````````````.-/osso:-....................-----------/oyys/:---::----::::::::/++//+o
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdyyysyyhs+///::---.........--:::////:::-----------....-----:/+//+o+-..................````..`.-:osso:-.......................--------:+syyo/:-------:---::::::::::/+++++
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmyssyssyyyo+//::--....-......---:://++++/:::--------...----:///::/+-......................-/+osso/-.```````.................-------/oyys/:-----------:---::::::::::/+hhyh
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhsssyssssys+//::--...........------:::::/+++//::::::-----::///////-...```.``....```..-/osss+/:-.....``````````..............---:+syy+/------------------:::::////oyhysooy
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdyssyyssssss+//::--..........--------------://+oooo++///////++++/:.....````````...-/oyys/-.`````......````````````..........-/oyys/:---------------------:::://oyhyo+//+sm
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNdhysssssooooso+/:---.........-------------------::/+sdmmdddhhhy+-.........````.-+syyo/-.````````````````...``````````....-:+sys+:-....-----------:-------::::+yhyo+/////++y
MMMMMMMNNNNNNNNNNNNNNNNNNNNmdhyyssssooo+ooo+/:---.........-----:::---..-----:::/ohNNNNdhs+:...```.......-:+yho:....```````````````````````````````.-/oyyo/-.........----------:--::-:::/shhs+/////+/+++o
MMMMMMNNmmmmmmmmmmmmmmmmmmmmdhyyssoooo+++o+/::---........-----:::::--.---::::/+ssdmmdd+:--....````````:syso/.````...```````````````````````````.-+sys/-..........-------------::::-:/oyhs+::/:////++++++
MMMMMNNmmmmmmmmmmmNmmmmmmmmmmmddhhyyssoo+o+/::---.......-----::://:------:::/+osymmmddd+--.-..````````/+-`....````....`````````````````````.-:oyyo:-............--------------:::/oyhs+:::::://///+++++/
MMMMNNNNNNNNmmmmmmmmddddmmmmmddddddddddhhhysso/::---....-----::///:-----::://osshmmmmdddo---...``````````..`...`````...`````````````````.:+sys/-.`..............-.------------/oyhs+::::::::::////+/+++/
MMNNNNNNNNNmmmmmmmdmmddhdmmmmmmddddddddddddhhhhhhhysoo+/::--:::///::--:::///+syyddmmmmddd+---..```````````````...````...````````````.-/syy+:.``````..............----------:+yhy+::::::::::::////++//+/+
MMNNNNNNNmmmmmmmmmmmmmdddhddmmmmdmdddddddddhhhhhhhhhhhhhhhysooo+++//////++osyhdddddmmmdddd+..--.``````````````````````....``````.-/oyyo:.````````````............-------:+yhy+::::::::::::://///+++/+oyd
MNNNNNmmmmmmmmmmmmddddddddhhhmmmmdddddddddddddhhhhhhhhhhhhhhhhhhhhhhhhhhhddddddddmddmmmdddh/..--..`````````````````````.-..`..:oyyo/.````````````````.............---:+shy+:--::::::::::::://///++oyhhs/
MNNNNmmmmmmmmmmmdmdddddddddddddhhhhhhhhdddddmmmddddhhhhhhhhhdhhhhhddddddddddddddddddddmddmdh:...--.```````````````.`````.-:+yyo/.````````````````````............--+yhy+:---:::::::::///////////ohhs////
NNNNmmmmmmmmmmmmddddddddhhhhhhhhhhhhhhhhhhhhddddmmddddhhhhhhhhhhhhdddddddddddddddddddddmddddh-.``.--.``````````````..``.:ods:.````````````````````````.`.......:+yhs/-------::::::::::///////+shyo/::///
NNNmmmmmmmmmmmddddhhhhhhhhhhhhhhhyyyyyyyyhyyhhhhhhdddddddddhhhhdddddddddddddddddddddddddmdmmdy-..-:/o/..`...``..-:/+h+ohho:--..`````````````````````````....:ohhs/-----------::::::::://///+ydy+///::://
NNmdmmmmmmmmddddhhhhhhhhhhhhhhhyhyyyyyyyyyhhhhhhyhhhhhhdddddddddddddddddddddddddddddddddmdmmdddyyss+//-/syyyosyys+/:-`......-..`````````````````````.``..:shyo:......-------::::::::::://+yds+/////::::/
Nmdmmmmmmmddddhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyhhhhyyhhhhhhhhhhhhhhhdhddhddddddddddddddddddmmmmmd+...`````-:-....`````````.....-...``````````````````..-+yhs/-........--------::-:::::://+yds////////::://
mdmmmmmmdddddhhhhhhhyhhhyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhyhhhhdddddddddddddhddddddddddddddddddmdmmd/..``.````.-.....```````......--..``````````````.-/shy+-............---------::--:::/+hds////////+/::://
]]--

POINTS_DISPLAY=true SURVIVAL_POINTS=0 SURVIVAL_POINTS_PLAYERS={}function AOD_Points_IncreaseTotalScore(points)SURVIVAL_POINTS=SURVIVAL_POINTS+points end function AOD_Points_DecreaseTotalScore(points)SURVIVAL_POINTS=SURVIVAL_POINTS-points end function AOD_Points_GetTotalScore()return SURVIVAL_POINTS end function AOD_Points_IncreaseTeamScore(ownerPlayer,points)local humanPlayers=Team_GetPlayers(0)local totalPlayers=#humanPlayers local ownerPoints=0 local otherPoints=0 if(totalPlayers>1)then ownerPoints=0.75*points otherPoints=0.25*points/(totalPlayers-1)else ownerPoints=points end for i,humanPlayer in ipairs(humanPlayers)do if(humanPlayer==ownerPlayer)then AOD_Points_IncreasePlayerScore(humanPlayer,ownerPoints)else AOD_Points_IncreasePlayerScore(humanPlayer,otherPoints)end
end end function AOD_Points_IncreasePlayerScore(player,points)
local playerId=Player_GetID(player)local playerPoints=SURVIVAL_POINTS_PLAYERS[playerId]or{["total"]=0,["available"]=0}playerPoints["total"]=playerPoints["total"]+points playerPoints["available"]=playerPoints["available"]+points SURVIVAL_POINTS_PLAYERS[playerId]=playerPoints end function AOD_Points_SpendPlayerScore(player,points)local playerId=Player_GetID(player)local playerPoints=SURVIVAL_POINTS_PLAYERS[playerId]or{["total"]=0,["available"]=0}playerPoints["available"]=playerPoints["available"]-points SURVIVAL_POINTS_PLAYERS[playerId]=playerPoints end function AOD_Points_GetPlayerScore(player)local playerId=Player_GetID(player)local playerPoints=SURVIVAL_POINTS_PLAYERS[playerId]or{["total"]=0,["available"]=0}return playerPoints["total"]end function AOD_Points_GetPlayerAvailableScore(player)local playerId=Player_GetID(player)local playerPoints=SURVIVAL_POINTS_PLAYERS[playerId]or{["total"]=0,["available"]=0}return playerPoints["available"]end function AOD_Points_InitScoreObjective()OBJECTIVES['aod_score']={OnStart=function()end,SetupUI=function()end,OnComplete=function()end,OnFail=function()end,IsComplete=function()return false end,Intel_Start=nil,Intel_Complete=nil,Intel_Fail=nil,Description=nil,TitleEnd=nil,TitleFail=nil,Type=OT_Primary,Title=Loc_FormatText(Util_CreateLocId(1337020),Loc_ConvertNumber(0))
}Objective_Register(OBJECTIVES['aod_score'])end function AOD_Points_UpdateScoreObjective(show,score)score=score or round(AOD_Points_GetTotalScore(),0)if(not Objective_IsStarted(OBJECTIVES["aod_score"]))then Objective_Start(OBJECTIVES['aod_score'],false)end Objective_UpdateText(OBJECTIVES["aod_score"],Loc_FormatText(Util_CreateLocId(1337020),Loc_ConvertNumber(score)),nil,show)
end AOD_POINT_CURRENT=1 function AOD_Points_ShowData()local i=1 local shown=false for playerId,playerPoints in pairs(SURVIVAL_POINTS_PLAYERS)do if(not shown and i==AOD_POINT_CURRENT)then local playerName=Player_GetDisplayName(Player_FromId(playerId))[1]
local eventCueText=Util_CreateLocString(playerName.." points available: "..round(playerPoints["available"],0).."/"..round(playerPoints["total"],0))
UI_CreateEventCue("Icons_abilities_ability_german_infantry_awareness","",eventCueText,eventCueText,5)AOD_POINT_CURRENT=AOD_POINT_CURRENT+1 shown=true end i=i+1 end if(AOD_POINT_CURRENT>=i)then AOD_POINT_CURRENT=1 end end
