--[[
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMN/``.-:/+shdmNNNNMNNMMMMMMMNNMMMNmmNNNmmNmmmmmmmmmmmmmdhhhhhddmNNMMMMMMMMMMMMMMMMMMMMMMMMMNNNNmmmmmmm
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmNNNNNNNMMMMMMMNNMMMMMMMNNNMMNmmmmNNNNNmdhyyyhyssyo/--:://oydNMMMMMMNNNNNNNNNNNNNNNNNNNmmmmmmmmmmm
MNMNMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNNNNNMMMMMMMMNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmMMMMMMMNNNMMNmmmdhyso+/://///+++os+---:/++oymNMMMMNNNNNNNNNNNNNNNNNNNmmmmmmmmmmmm
NNNNNMMMMMMMMMMMMMMMMMMMMNNNNNNNNNNNNmmmmmmmNMMMMMMNNNNNNMMMMMMMMMMMMMMMMMMMMMMMNmdhysoooooooosyyhddmNNNMMMNMMMMMNNNNNhNMMMMMMNmNNNmhso++///////:---::::+s+::://:+smNMMMMNNNNNNNNNNNNNNNmmmmmmmmmmmmmmmm
NNNNNNNNMMMMMMMMMMMMMMNNNNNNNmmNmmmmmmmmmdmmNMMMMMNNNNNNNNNNNMMMMMMMMMMMNmhyo+:-````             ````.-/sdNNNmNNNNNNNNmNNMMMNNNmdhyyyyyyssosoo+++//:::-.-//---:::/omNMMMMNNNNNNNNmNmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNMMMMMMMMMMMMMMMNNNNNNNmmmmddhhyyyyyymNMMMMNmNNNNNNNNNNNNNNmdyo/-.``                            `.:ddmddmNNNNNNmNNNNNmmdhhysooo++++++/+//+++/:--.....----//omNNMMNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNMMMMMMMMMMMMNNNNNNNNNNNNNmmmdddhhyydNMMMMMmNNNNNNNNNdyo/-``                                   `.+mmNmdNNNNNNmmNNmdhyyysoo+++++/:///+//:-...........----//odNNNMNNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNMMMMMMMMMMNNNNNNNNNNNNNNNNmmmmmmmmNNMMMMMNNNNmmho/-``                                        .-sNNNNmNNNNNNmmdhyyyo++/////://++/:-..``````.........---:/odmNNNMNmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNNMMMMMMMMMNNNNNNNNNNNNNNNmmmmmmmmmNNMMMMMNdy+-.`                                            `.:dNNNNmNNNNmdhhyss+::::----..--..``````````...........-::/+hmNNNMNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNNNMMMMMMMMNNNNNNNNNNNmNmmmmmmmmmmmNNNNmho-`                                                 `-+NNNNNmNmdhyysso+-..-:-....```` ````````````..........--::+ymNNNMNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNNNNNMMMMMMNNNNNNNNNNNNNmmmmmmmmmmmmhs:.`                                                 ` `.:sNNNNNmhyyysso+:.``.--.```    ````````````````.........-::/smNNNMNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNNNNNMMMMMMNNNNNNNNNNNNNmNmmmmmmdy+-`                                                       `.:dMNNmhsosyso/-.```````       ` `````````````````.......-://odNNNMNNmmmmmmmmmmmmmmmmmmmmmmmmmmmmm
NNNNNNNNNNNNNNNMMMMMNNNNNNNNNNNNmNmmmmdy/.`                                                       `  `./mNdhso++o+:..``````     ` ` `   ``````````````````...---::/+hmNNMNNNmmmmmmmmmmmmmmNmNNNNNNNNNMMM
NNNNNNNNNNNNNNNNNMMMMNNNNNNNNNNNmmmdy+-`                                                            ``-omdoso++/-.```````````` `     `  ``````````````````....--::/+yNNNMMNNNNNNNNNNNMNNMMMMMMMMMMMMMMMM
NNNNNNNNNNNNNNNNNMMMMNNNNNNNNNNNmh+-`````                                                    ``  `  `.-dNyoooo:..`````````````````` `````````` ````````````...--:/+oyNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MNNNNNNNNNNNNNNNMMMMMNNNNNNNNmdo-`````````                                                       ````.:Ndo/++:-..``````````````````````````````````````````...-:/oydNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMNds/.``` `  ``                                                       ``````.+Ny/:+:-.```````````````````````````   `````````````..::+shmNNdddmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMNmho/.`````` ``  ````                                                `````.``..-oyhoo/-`````````````````````````````       ```````.-:/syhhhdhyyyhdNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MNNMMMNNMMMNMMMMMMNmho/-.``````````````` ``                                           `  ```````..`--:--hh+.```````````````````````````        ``````..-:/+osoooossssyhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMNMMMNNNMMNds/-......``````````````  ``                                       `  `` ```````.-`.:/--/+```````````` `````````````````   ````````..-:/++oooooosssssyhhdmNMMMMMMMMMMMMMMMMMMMMMMMMNMMMM
MMMMMMMMMMMMNds/.........````````````````  ``                                         ``````````--..:/:/:```````````````````````````````````````...-:/+++++ooooooossssssyhmMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMmy/-.....-......```````````````` ```                                         ``````...--:::/:......`````````````````````````````...--::///+++++++++++ooo+++oosymNNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMNMMdo:-----------.....``````````` ``` ````                                   ```..---:://+osyhdyo:-....--..............``````````.-:////++/::::://///++++++++++oshdNNmNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMd+:--------------....``````` ```` ``` ````                            ```.--:::///////+++oosyhmds:------------......```````....:+o++////////:::://///++++++++oshhdhhhdNMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMm+-------------------...`````     ``  `` `````                    ```......---:::://////++++oooosydh+/:------------..``````...--+so++oossyyyyysssssoo+++++++++ossyhhhhhhmMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMNs/:--:::--------------..``````     ``  ```````               ``...........-----::::://///++++++oooshhsso+++////::-:::---....`./sssoosysoo++++ooososooo++//++++syhddhhdddmMMMNMNNNNNMMMMMMMMMMMMMMMMM
MMMMNdy/:::::-------------.-.`````     `````````````       `..-----.-.............---::::///+++++++++oosyhddhsysso+++//++:::-..`.:osyssso++///::///++++++++++//+oshdmmNmhhmNmMMNNNNNNMMMMMMMMMMMMMMMMMMM
MMMMMNNms/:::::----------.-.-.````````````````````    `.:++//:::----.-.-........-----::::////++++++++ooossyoymNdyyssooo++////+++ssoosyo+//////++ooossssooooo++//oydsdmmmhydmmNMNNMNNMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMms:::::--------..-.....```````````````````-/+ysso+/::::::------..---------..--::::///+++++++ooooymNMMMNdysssssooshdddyssssoss++++++ososyhyyyyysssssoo++oshyyyyyyyhddmNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMNs/:/:::------------......``````````:+syyyysso+/:::::::::--.--:://+++++/::---::::::////+++++oosdMMMMNhyssoyNMMMMNNmhyssssoo++++osyhmNdmy//oso//+oosooosyhhhyyyyyhhdmMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMms//::::----:::----......````.:oydmmddhhyso//:::::::::--://///:://///+++ooo+//:::::::://+++ooyNMMMmoosyysdNNMNNNmhysssso+///+oyyyhdddsosssso+oosssooossydhhhhhhhhdMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMms+/::--::///::----....-/ohmdmdmmddhhys+/:::::/://::::::--..........::/+o+/++:----:::////++odMMMmoso//shdNNNNNmdhyssoo+////++++++/+++ooooo+oosossoooosydhyyhhhhdNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMNh+/+++/++//::---:+ydmNmmdmmddddyyso/::::://////::---...............--//////------:::///+oymMMNos+//+osydNNNmdyyysso+//////////+++ooo++++oooosssssssshhyyyyhhhNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMNdysoo+++///+shmNNmmmdhhdddhyyso+/:::::://///::--.........--------....----------:://+oydmmNMMhs///:+ssydNNmhysssso++///////++o+o++++++/+osssyyysssssyyssyyhdNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMNNdyssosydNNNNmmmddhddhddhhys+//:::::::///::-......--::///++//:---........---:::/+osydmNmMMNs+++::+s+odNmhyyyyso++///////////+++++///oyyssyyso+/oosyyssyhdNMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMNdddNNNNNmmNmdddmdddddhyys++/::/:::////:-...-.-:://+///++oso/:---.......-:///+ooosssymNMMdso+o++s+/smmmhyyyyso++/+////:::::::///++sssoooss+/:+ooysssyhmMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmNNNNNmmmdddddhhhssso//::://////:-....--://++os+-``.:/+/---....`..-/++o++///+osdNMMMhooso++o++hmmdhhhyysoo+++/////::::://+++osssssyyyoosshhysyydNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNNNNNmmdddhhdyssso+////////::-.....--:/:sddhdy-..-::/-.........-/so+///+ossydMMMMMmyo+////+ymmddhhhhssoo++++++++///+++++//+oooooosssyhddhyyydNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNNNNMNNNmmdddyhhysoso/////////:---.---::://oyyyhs-.-://:...-------:/ooooo/+shdhmMMMMMMMmhso+//odmmddhhhyssoo++oo++++++++o+/////+++++++oshhhddyhmMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMmdyysydmNmmddhyhhyysso+////////::----------::---://////++/:::::::::::/+sdmds::ohdNNMMMMMMMMNNmhyshmNmddhhhysooo+ooo++++++++//++////++++oosyhdddyhNMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMNh++/++///osyhdyydhysso++///////:::-----------...----::///+/::::::::::::/+sooooosyhNMMMMMMMMMMMMmhyymNNmddhhysso++osooo++o+++++++++ooooosssyhdmmdydMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMh/::///::/::+yhsyddhsoo++////::/:::--:::------.....---:::/::::::::::---::/+o+++++shNNNNNNNNNNNMMNmhydmNmmdhhhyso+++osoo++++++oosssyyyyyyyyhdddmdhhNMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMm/--:++:-./+::+++syddyoo+////://::::--------------------:::::::::::::---:::/+o++++ohNNNMMMMMMMMMMMmdhhmmmmdhhyyyso+//oo++/+++syyhhhyyyyyyhhhhhdmdhmMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMh:-:+o+/:////-::/+osyyo++//:////:::--------......---------------:-::::::::::/+oo++osNMMMMMMMMMMMMMNmdhhdmddhhyyysoo+/+o++//++ooosssssssssysyyhddmmNMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMm/:/so/:----/://:/+osoo+//////////:------...........--------------::::///::::/++o++smMMMMMMMMMMMMMMmddhhddddhhyyyss+++++++/++ooo+++oooossssyyhhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMo/os/---:--///---:ooo+++/////+//+:---........``....---------...-//+///:::---::/+o+ohNNNNNNNNNNNNMMNmdhhhdddhhyyyyssooooo+++oooo+++++++ossyyyyhdmNMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMm+ss:::---:/+-.-.-/os++//////+//:---.-.......````....------...-//////:--.....-:/+++smNNNNmmNNNNNMMNmdhhyyhddhyyyyyssoooooooooooo+++++oossssyhhddMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMs+s///:---://:...-+so+/////////::--.......```````....-----...-//::--..--::---:/+/+omNNNNNNMMMMMMMNmdhyysyyhhhhyyyssssoooossoooo+++ooooosssyyhdmNNNNNMMMMMMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMmo+/:::///::/o-.../so+/////////::--.........``````....--------//:---:::/++///++///omNNNMMMMMMMMMNNNdhhyssssyyhhhyyssssoossssooooooooooosssyyhddyyyhhhhdmNMMMMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMms/:::::-------..:oso////////::----.........``````....--------::::----/+++so/://+sNMMMMMMMMMMMMNNmdhhyssoosssyyhhhyssssssssssssssoooosssssyhmhyysyyyssyyhdNMMMMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdo/::--......--:oso+//::::::::----...........```....--------------::oo/+s+/::/odMMMMMMMMMMMMNmmmdhyysssoooooosyyyyyyyyyssssyssssoosssssyhdhssyyssyyyyhhhhdmNMMMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmyo/:-......-:+so++//::::::------.............`....--..----------:/oo+oo+:/+hMMMMMMMMMMMMNmddddhyysooooo+o++ooossyyyhyyyysyssssssyyyyhhysssyhhhhyyssoossooymMMMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNNmdyo+:--...:+sso+//:::::/-------.--...................---------:/+s+os+/+hNNMMMMMMMMMMNmdhdhhhhysoooo+++++++++oooosyyhhyyyyyyyhhhhhsshhhhsooso+o++/+ooo+++ymMMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdyso+///:--+sso+//::::---------...-...............```..--.----:/+ooos//sMMMMMMMMMMMMNmdhhyysyhysooo++++++++++++osoooosyyhddddmNyosys+++o+++oo/++////+o++/++dMMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhyo/:--:+++sss++/::::----------..----........---.```.....---:/+oosss/oNMMMMMMNMMMMNmhhyyysssyysooo++++++++++++ooooooossyhhyhmNo/++////++/++o+/+///:/+o+///+dMMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhys+/:--/o+osso+//::----:------------------------.......-:/++oosyyy/+hMMMMMMMNmhyddhyysssssssssoo+++++++/++++oooooooossyhyyhdh//+//:://+++o+o//+//:::/o+///oNMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhyso/:::/o++ooo+//::----------------------------:::://+osoo+:/++yho:sNMMMMNy+//sddhyssoooooooooo+++++///++++++oooooossyyyssyh/:///::::///+o+oo/++//:::/oo+osdMMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdsso+/:::+o+++o+/::-----------------------------:/+ossooooooyhhhhs//dMMMMms:--..-//+oooooooo+++o++//////++++++oossssssssoo++::://::::::///+++oo+ooosyhhyshyssdMMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhssoo//::++///++/::-----------------------------:/osoooooooooosyys/sMMMMm+:---....`.`.-://++++++////////++++++++oossso+/:---::/:/::::::://+syhhhdhhy+::::/+o+oNMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhsooo+/::////////:::-----------------------------:+sssooooooooooosydNMdo+/::-.......```````...--::::::::///////:/::--...-----::::::::/oyhhhss+/+oooo+/--:::/osdMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhyooso/::///::::/::--------------------------------:ossssooooooooosshy///::--.......``````````````````````..............-----:::::+shhs/://////:/++oso/:-:::/syMMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhssooo//::/::-::::---.--:------------------.---------:/ossooooosssssyh+:::--.......````````..```````````````..........-------::oyys+::::::////////+++os+:--::++MMMMM
NNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMMMNysssoo+//:::----:------.....---------------------------://+oossyyyyyso/::----............./h:````....````.............-----/oyyo/::-:::::://::://://++ooo/:-:/+NMMMM
MMNNNNNNNMMMMMMMMMMMMMMMMMMMMMMMMMMNhssso+//:::----------:/.......---------....---.-----------:/+oyhddyo/:::-----------/////+++:-.-......................-:/oyys+:::-------::::::::://:::/++os+:::+mMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMdysss+//::-----.-------........---------------------:-----::/+syhhs//::-----:+oooo+/--...........................-/osyso/:----------------::::::::::::+shhhyshyhMMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmhsss+//::----....---.............-------------------::::://+ossys/:::-:+oss+/:--........```.................-/syyo/:----------------------:::::::/+shyo+/+osso+hMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmddyso+//:::---.....---............------------------::://++ossss/::/osso+:-..........`````````...........-/oyyo/--......--------------------:::/oyhy+/:::::/+oosymMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmdhdhso+///:::--......----.--..........---------------::::/+ossssooss+/:-........```````..```````.......:+syo/-........--..-----------------::+shyo/::::::::::+o++osdM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmdhyydyo+///::---.......-:-------.......------......-----:://++oso+/:-----.........````````````````..-/sys+:-............-..---------------:oyys+/::----:::::::/+++++sd
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNhyysyhho+///:::--........-::::::--------------....--------::///oso:-----............````````````.-/osso:-....................-----------/oyys/:---::----::::::::/++//+o
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdyyysyyhs+///::---.........--:::////:::-----------....-----:/+//+o+-..................````..`.-:osso:-.......................--------:+syyo/:-------:---::::::::::/+++++
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMNmyssyssyyyo+//::--....-......---:://++++/:::--------...----:///::/+-......................-/+osso/-.```````.................-------/oyys/:-----------:---::::::::::/+hhyh
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmhsssyssssys+//::--...........------:::::/+++//::::::-----::///////-...```.``....```..-/osss+/:-.....``````````..............---:+syy+/------------------:::::////oyhysooy
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMNdyssyyssssss+//::--..........--------------://+oooo++///////++++/:.....````````...-/oyys/-.`````......````````````..........-/oyys/:---------------------:::://oyhyo+//+sm
MMMMMMMMMMMMMMMMMMMMMMMMMMMMNdhysssssooooso+/:---.........-------------------::/+sdmmdddhhhy+-.........````.-+syyo/-.````````````````...``````````....-:+sys+:-....-----------:-------::::+yhyo+/////++y
MMMMMMMNNNNNNNNNNNNNNNNNNNNmdhyyssssooo+ooo+/:---.........-----:::---..-----:::/ohNNNNdhs+:...```.......-:+yho:....```````````````````````````````.-/oyyo/-.........----------:--::-:::/shhs+/////+/+++o
MMMMMMNNmmmmmmmmmmmmmmmmmmmmdhyyssoooo+++o+/::---........-----:::::--.---::::/+ssdmmdd+:--....````````:syso/.````...```````````````````````````.-+sys/-..........-------------::::-:/oyhs+::/:////++++++
MMMMMNNmmmmmmmmmmmNmmmmmmmmmmmddhhyyssoo+o+/::---.......-----::://:------:::/+osymmmddd+--.-..````````/+-`....````....`````````````````````.-:oyyo:-............--------------:::/oyhs+:::::://///+++++/
MMMMNNNNNNNNmmmmmmmmddddmmmmmddddddddddhhhysso/::---....-----::///:-----::://osshmmmmdddo---...``````````..`...`````...`````````````````.:+sys/-.`..............-.------------/oyhs+::::::::::////+/+++/
MMNNNNNNNNNmmmmmmmdmmddhdmmmmmmddddddddddddhhhhhhhysoo+/::--:::///::--:::///+syyddmmmmddd+---..```````````````...````...````````````.-/syy+:.``````..............----------:+yhy+::::::::::::////++//+/+
MMNNNNNNNmmmmmmmmmmmmmdddhddmmmmdmdddddddddhhhhhhhhhhhhhhhysooo+++//////++osyhdddddmmmdddd+..--.``````````````````````....``````.-/oyyo:.````````````............-------:+yhy+::::::::::::://///+++/+oyd
MNNNNNmmmmmmmmmmmmddddddddhhhmmmmdddddddddddddhhhhhhhhhhhhhhhhhhhhhhhhhhhddddddddmddmmmdddh/..--..`````````````````````.-..`..:oyyo/.````````````````.............---:+shy+:--::::::::::::://///++oyhhs/
MNNNNmmmmmmmmmmmdmdddddddddddddhhhhhhhhdddddmmmddddhhhhhhhhhdhhhhhddddddddddddddddddddmddmdh:...--.```````````````.`````.-:+yyo/.````````````````````............--+yhy+:---:::::::::///////////ohhs////
NNNNmmmmmmmmmmmmddddddddhhhhhhhhhhhhhhhhhhhhddddmmddddhhhhhhhhhhhhdddddddddddddddddddddmddddh-.``.--.``````````````..``.:ods:.````````````````````````.`.......:+yhs/-------::::::::::///////+shyo/::///
NNNmmmmmmmmmmmddddhhhhhhhhhhhhhhhyyyyyyyyhyyhhhhhhdddddddddhhhhdddddddddddddddddddddddddmdmmdy-..-:/o/..`...``..-:/+h+ohho:--..`````````````````````````....:ohhs/-----------::::::::://///+ydy+///::://
NNmdmmmmmmmmddddhhhhhhhhhhhhhhhyhyyyyyyyyyhhhhhhyhhhhhhdddddddddddddddddddddddddddddddddmdmmdddyyss+//-/syyyosyys+/:-`......-..`````````````````````.``..:shyo:......-------::::::::::://+yds+/////::::/
Nmdmmmmmmmddddhhhhhhhhhyyyyyyyyyyyyyyyyyyyyyyhhhhyyhhhhhhhhhhhhhhhdhddhddddddddddddddddddmmmmmd+...`````-:-....`````````.....-...``````````````````..-+yhs/-........--------::-:::::://+yds////////::://
mdmmmmmmdddddhhhhhhhyhhhyyyyyyyyyyyyyyyyyyyyyyhhhhhhhhyhhhhdddddddddddddhddddddddddddddddddmdmmd/..``.````.-.....```````......--..``````````````.-/shy+-............---------::--:::/+hds////////+/::://
]]--

import("winconditions/aod_lists.scar")SETTINGS={data={},initialized=false,IsInitialized=function()return SETTINGS.initialized end,AddSettings=function(settings_table,gamemodes)if(not SETTINGS.initialized)then SETTINGS.Init(AOD_GAMEMODE)SETTINGS.initialized=true end if(type(gamemodes)~="table")then gamemodes={gamemodes}end local function CheckTableOnlyValues(source)if(type(source)~="table")then return false end for key,value in pairs(source)do if(type(value)=="table"or type(key)~="number")then return false end end return true end local function SolveTable(source,target)if(type(source)=="table")then if(target==nil or type(target)~="table")then return source else for key,value in pairs(source)do targetValue=nil if(target[key]~=nil)then targetValue=target[key]end if(CheckTableOnlyValues(target[key]))then target[key]=source[key]else target[key]=SolveTable(source[key],target[key])end end return target end else return source end end for i,gamemode in pairs(gamemodes)do if(gamemode==AOD_GAMEMODE or gamemode=="any")then for key,setting in pairs(settings_table)do SETTINGS.data=SolveTable(settings_table,SETTINGS.data)end end end end,GetSetting=function(setting_name)if(SETTINGS.data~=nil and SETTINGS.data[setting_name]~=nil)then return SETTINGS.data[setting_name]end
return nil end,GetSettingCount=function(setting_name)if(SETTINGS.data~=nil and SETTINGS.data[setting_name]~=nil and type(SETTINGS.data[setting_name])=="table")then return#SETTINGS.data[setting_name]end return 0 end,Init=function(gamemode)local default_data={["WAVE_DEFAULT_INTERVAL"]=10,["START_TIME"]=60,["BOMB_FRIENDLY_SQUADS_ABILITY"]="off_map_arty_single_shot_instant",["BOMB_FRIENDLY_ENTITIES_ABILITY"]="off_map_arty_single_shot_instant",["HURT_FRIENDLY_SQUADS_SOUND"]="speech/mp/soviet/cn2/events/pinned/sb_cn2_pin_gengen_lt_s",["BOMB_FRIENDLY_SQUADS_SOUND"]="speech/mp/aef/ech/events/warning/ab_ech_wrn_astgen_lt_s",["INVULNERABLE_PLANES"]=ALL_AIRCRAFT,["AI_PATHS"]={},["AI_FAIL_POSITIONS"]={},["LOSE_CONDITION"]="overrun",["DIFFICULTY"]={["starting_resources"]={["manpower"]={1500,1500,1400,1000},["fuel"]={200,200,150,80},["ammo"]={300,300,200,100},["command"]={10,10,5,0}},["resource_multipliers"]={["manpower"]={1.4,1.4,1.3,1.2},["fuel"]={1.4,1.4,1.3,1.2},["ammo"]={1.4,1.4,1.3,1.2},["upkeep"]={0.5,0.5,0.5,0.6}},["wave"]={["autofire"]={false,true,true,true},["armor"]={0.9,1.0,1.1,1.2},["speed"]={0.9,0.9,1.0,1.0},["veterancy"]={0,0,1,2},["received_suppression"]={0.7,0.3,0,0},["received_damage"]={1.0,1.0,1.0,0.9},["damage"]={1.0,1.0,1.0,1.0},},["hurt_units_on_route"]={["time_without_damage"]={3,3,3,2},["time_till_max_damage"]={5,4,4,3},["max_damage_per_second"]={0.1,0.1,0.1,0.15}},["popcap"]={250,225,200,150},["fow"]={true,true,true,true},["sight"]={1.3,1.2,1.1,1.0},["experience"]={0.9,0.8,0.8,0.7},["units_allowed_to_pass"]={1,21,11,0},["remove_entities_only_defences"]={true,true,true,false},["karma_only_vehicles"]={true,true,true,false},["karma_between_waves"]={["hurt_moving_friendly_squads_on_route"]={false,false,false,true},["hurt_friendly_squads_on_route"]={false,false,false,true},["bomb_friendly_squads_on_route"]={false,false,false,true},}}}if(gamemode=="classic")then default_data["WAVE_SETUP"]={}elseif(gamemode=="survival")then default_data["SURVIVAL"]={["wait_until_everybody_dead"]=false,["delay_after_wave"]=40,["bomb_friendly_squads_on_route"]=false,["hurt_friendly_squads_on_route"]=false,["hurt_moving_friendly_squads_on_route"]=true,["kill_friendly_entities_on_route"]=true,["bomb_friendly_entities_on_route"]=false,["starting_points"]=3,["points_multiplier_per_wave"]=2.4,["factions"]={"soviet","aef","german","west_german"},["spawn_interval"]=nil,["expensive_unit_spawn_chance_multiplier"]=3,["wave_pause_interval"]=5,["wave_pause_length"]=60,}end SETTINGS.data=default_data end}function AOD_Setup(setup,gamemode)gamemode=gamemode or"any"SETTINGS.AddSettings(setup,gamemode)end