function CCM_DataInit()
	
	g_ccm_category_ability = {
		{
			ability = CCM_GetAbilityBleprint("category_01"), 
			actions = {
				{ability = CCM_GetAbilityBleprint("category_01_action_01"), action = CCM_AddInfiniteResourcesPopcap},
				{ability = CCM_GetAbilityBleprint("category_01_action_02"), action = CCM_ToggleInstantProduction},
				{ability = CCM_GetAbilityBleprint("category_01_action_03"), action = CCM_ToggleFOW},
				{ability = CCM_GetAbilityBleprint("category_01_action_04"), action = CCM_ToggleGlobalAI},
				{ability = CCM_GetAbilityBleprint("category_01_action_05"), action = CCM_CopySelection},
				{ability = CCM_GetAbilityBleprint("category_01_action_06"), action = CCM_PasteSelection},
				{ability = CCM_GetAbilityBleprint("category_01_action_07"), action = CCM_ActionKillSelection},
				{ability = CCM_GetAbilityBleprint("category_01_action_08"), action = CCM_ActionDeleteSelection},
				{ability = CCM_GetAbilityBleprint("category_01_action_09"), action = CCM_ToggleSelectionInvulnerability},
				{ability = CCM_GetAbilityBleprint("category_01_action_10"), action = CCM_ToggleSelectionOwner},
			},
		},
		{
			ability = CCM_GetAbilityBleprint("category_02"), 
			actions = {
				{ability = CCM_GetAbilityBleprint("category_02_action_01"), action = CCM_ActionTeleportSelection},
				{ability = CCM_GetAbilityBleprint("category_02_action_02"), action = CCM_ActionIncreaseSelectionVeterancy},
				{ability = CCM_GetAbilityBleprint("category_02_action_03"), action = CCM_ActionIncreaseSelectionHealth},
				{ability = CCM_GetAbilityBleprint("category_02_action_04"), action = CCM_ActionDecreaseSelectionHealth},
				{ability = CCM_GetAbilityBleprint("category_02_action_05"), action = CCM_ActionAbandonSelected},--
				{ability = CCM_GetAbilityBleprint("category_02_action_06"), action = CCM_ToggleEngineOrPostureState},--
				{ability = CCM_GetAbilityBleprint("category_02_action_07"), action = CCM_ToggleDisableWeapons},--
				{ability = CCM_GetAbilityBleprint("category_02_action_08"), action = CCM_ActionRemoveCriticals},
				{ability = CCM_GetAbilityBleprint("category_02_action_09"), action = CCM_ActionDropSlotItems},--
				{ability = CCM_GetAbilityBleprint("category_02_action_10"), action = CCM_ActionInstantReinforce},
			},
		},
		{
			ability = CCM_GetAbilityBleprint("category_03"), 
			actions = {
				{ability = CCM_GetAbilityBleprint("category_03_action_01"), action = CCM_ActionAddPreciseManpower},
				{ability = CCM_GetAbilityBleprint("category_03_action_02"), action = CCM_ActionAddPreciseFuel},
				{ability = CCM_GetAbilityBleprint("category_03_action_03"), action = CCM_ActionAddPreciseMunition},
				{ability = CCM_GetAbilityBleprint("category_03_action_04"), action = CCM_ActionSpawnGermanSpawner},
				{ability = CCM_GetAbilityBleprint("category_03_action_05"), action = CCM_ActionSpawnSovietSpawner},
				{ability = CCM_GetAbilityBleprint("category_03_action_06"), action = CCM_ActionSpawnWestGermanSpawner},
				{ability = CCM_GetAbilityBleprint("category_03_action_07"), action = CCM_ActionSpawnAEFSpawner},
				{ability = CCM_GetAbilityBleprint("category_03_action_08"), action = CCM_ActionSpawnUKFSpawner},
				{ability = CCM_GetAbilityBleprint("category_03_action_09"), action = CCM_ActionKillOneEntity},
				{ability = CCM_GetAbilityBleprint("category_03_action_10"), action = CCM_ActionDeleteOneEntity},
			},
		},
		{
			ability = CCM_GetAbilityBleprint("category_04"), 
			actions = {
				{ability = CCM_GetAbilityBleprint("category_04_action_01"), action = CCM_ActionAddFullHealth},
				{ability = CCM_GetAbilityBleprint("category_04_action_02"), action = CCM_ActionSpawnGermanMiscSpawner},
				{ability = CCM_GetAbilityBleprint("category_04_action_03"), action = CCM_ActionSpawnSovietMiscSpawner},
				{ability = CCM_GetAbilityBleprint("category_04_action_04"), action = CCM_ActionSpawnWestGermanMiscSpawner},
				{ability = CCM_GetAbilityBleprint("category_04_action_05"), action = CCM_ActionSpawnAEFMiscSpawner},
				{ability = CCM_GetAbilityBleprint("category_04_action_06"), action = CCM_ActionSpawnUKFMiscSpawner},
				{ability = CCM_GetAbilityBleprint("category_04_action_07"), action = CCM_ToggleHealthMonitor},

			},
		},
		--[[{
			ability = CCM_GetAbilityBleprint("category_05"), 
			actions = {

			},
		},
		{
			ability = CCM_GetAbilityBleprint("category_06"), 
			actions = {

			},
		},
		{
			ability = CCM_GetAbilityBleprint("category_07"), 
			actions = {

			},
		},
		{
			ability = CCM_GetAbilityBleprint("category_08"), 
			actions = {

			},
		},
		{
			ability = CCM_GetAbilityBleprint("category_09"), 
			actions = {
	--
			},
		},
		{
			ability = CCM_GetAbilityBleprint("category_10"), 
			actions = {
		
			},
		},--]]
	}
	colorUnPacker = {
		__call = function(t)
			return unpack(t)
		end
	}
	
	Colors = {
		addedHealth = { 255, 255, 255 , 255},
		removedHealth = { 255, 255, 255 , 255},
	}
	
	for key, _t in pairs(Colors) do
		setmetatable(_t, colorUnPacker)
	end

	spawner_page_ability = {
		{abp = CCM_GetAbilityBleprint("spawner_page_01"), abilityRange = {1, 10}},
		{abp = CCM_GetAbilityBleprint("spawner_page_02"), abilityRange = {11, 20}},
		{abp = CCM_GetAbilityBleprint("spawner_page_03"), abilityRange = {21, 30}},
		{abp = CCM_GetAbilityBleprint("spawner_page_04"), abilityRange = {31, 40}},
	}
	misc_spawner_page_ability = {
		{abp = CCM_GetAbilityBleprint("spawner_page_01"), abilityRange = {1, 10}},
		{abp = CCM_GetAbilityBleprint("spawner_page_02"), abilityRange = {11, 20}},
		{abp = CCM_GetAbilityBleprint("spawner_page_03"), abilityRange = {21, 30}},
		{abp = CCM_GetAbilityBleprint("spawner_page_04"), abilityRange = {31, 40}},
	}
	 
	spawner_spawn_ability = {
		[0] = {
			{ability = CCM_GetAbilityBleprint("spawner_german_01"), sbp = "pioneer_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_02"), sbp = "grenadier_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_03"), sbp = "mg42_heavy_machine_gun_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_04"), sbp = "mortar_team_81mm_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_05"), sbp = "sniper_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_06"), sbp = "scoutcar_sdkfz222_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_07"), sbp = "sdkfz_251_halftrack_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_08"), sbp = "pak40_75mm_at_gun_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_09"), sbp = "panzer_grenadier_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_10"), sbp = "stug_iii_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_11"), sbp = "ostwind_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_12"), sbp = "panzer_iv_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_13"), sbp = "panther_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_14"), sbp = "brummbar_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_15"), sbp = "panzerwerfer_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_16"), sbp = "assault_grenadier_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_17"), sbp = "stormtrooper_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_18"), sbp = "ostruppen_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_19"), sbp = "assault_officer_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_20"), sbp = "howitzer_105mm_le_fh18_artillery_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_21"), sbp = "pak43_88mm_at_gun_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_22"), sbp = "opel_blitz_supply_squad", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_23"), sbp = "mortar_250_halftrack_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_24"), sbp = "mechanized_250_halftrack_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_25"), sbp = "stug_iii_e_commander_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_26"), sbp = "panzer_iv_command_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_27"), sbp = "tiger_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_28"), sbp = "elefant_tank_destroyer_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_29"), sbp = "tiger_ace_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_30"), sbp = "urban_assault_panzer_grenadier_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_31"), sbp = "panzer_iv_stubby_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_32"), sbp = "ccm_panzer_grenadier_squad_pb_mp", special = true},
			{ability = CCM_GetAbilityBleprint("spawner_german_33"), sbp = "puma_east_german_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_34"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_35"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_36"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_37"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_38"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_39"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_german_40"), sbp = "", special = nil},
		},
		[1] = {
			{ability = CCM_GetAbilityBleprint("spawner_soviet_01"), sbp = "combat_engineer_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_02"), sbp = "conscript_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_03"), sbp = "penal_battalion_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_04"), sbp = "m3a1_scout_car_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_05"), sbp = "sniper_team_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_06"), sbp = "m1910_maxim_heavy_machine_gun_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_07"), sbp = "pm-82_41_mortar_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_08"), sbp = "m1942_zis-3_76mm_at_gun_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_09"), sbp = "t-70m_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_10"), sbp = "m5_halftrack_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_11"), sbp = "t_34_76_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_12"), sbp = "su-76m_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_13"), sbp = "su-85_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_14"), sbp = "katyusha_bm-13n_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_15"), sbp = "shock_troops_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_16"), sbp = "guards_troops_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_17"), sbp = "tow_partisan_squad_lmg_squad", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_18"), sbp = "partisans_rifle_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_19"), sbp = "partisans_panzerschreck_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_20"), sbp = "guards_troops_assault_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_21"), sbp = "dshk_38_hmg_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_22"), sbp = "m1937_53-k_45mm_at_gun_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_23"), sbp = "hm-120_38_mortar_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_24"), sbp = "m1937_152mm_ml_20_artillery_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_25"), sbp = "m1931_203mm_b-4_howitzer_artillery_commander_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_26"), sbp = "m5_halftrack__assault_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_27"), sbp = "soviet_76mm_sherman_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_28"), sbp = "t_34_85_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_29"), sbp = "kv-1_commander_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_30"), sbp = "kv-2_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_31"), sbp = "kv-8_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_32"), sbp = "is-2_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_33"), sbp = "isu-152_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_34"), sbp = "zis_6_transport_truck_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_35"), sbp = "commissar_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_36"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_37"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_38"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_39"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_soviet_40"), sbp = "", special = nil},
		},
		[2] = {
			{ability = CCM_GetAbilityBleprint("spawner_west_german_01"), sbp = "assault_pioneer_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_02"), sbp = "sws_halftrack_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_03"), sbp = "volksgrenadier_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_04"), sbp = "kubelwagen_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_05"), sbp = "raketenwerfer43_88mm_puppchen_antitank_gun_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_06"), sbp = "king_tiger_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_07"), sbp = "le_ig_18_inf_support_gun_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_08"), sbp = "jagdpanzer_tank_destroyer_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_09"), sbp = "sdkfz_251_20_ir_searchlight_halftrack_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_10"), sbp = "armored_car_sdkfz_234_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_11"), sbp = "sdkfz_251_17_flak_halftrack_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_12"), sbp = "sdkfz_251_wurfrahmen_40_halftrack_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_13"), sbp = "obersoldaten_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_14"), sbp = "panzer_ii_luchs_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_15"), sbp = "panther_ausf_g_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_16"), sbp = "sturmtiger_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_17"), sbp = "mg34_heavy_machine_gun_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_18"), sbp = "panzerfusilier_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_19"), sbp = "fallschirmjager_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_20"), sbp = "jaeger_light_infantry_recon_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_21"), sbp = "terror_officer_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_22"), sbp = "pak43_88mm_at_gun_squad_westgerman_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_23"), sbp = "flak_emplacement", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_24"), sbp = "ostwind_squad_westgerman_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_25"), sbp = "panzer_iv_ausf_j_battle_group_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_26"), sbp = "panther_commander_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_27"), sbp = "jagdtiger_td_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_28"), sbp = "hetzer_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_29"), sbp = "goliath_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_30"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_31"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_32"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_33"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_34"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_35"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_36"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_37"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_38"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_39"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_west_german_40"), sbp = "", special = nil},
		},
		[3] = {
			{ability = CCM_GetAbilityBleprint("spawner_aef_01"), sbp = "rear_echelon_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_02"), sbp = "riflemen_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_03"), sbp = "dodge_wc51_ambulance_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_04"), sbp = "vehicle_crew_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_05"), sbp = "usf_medic_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_06"), sbp = "lieutenant_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_07"), sbp = "m2hb_50cal_hmg_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_08"), sbp = "m20_utility_car_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_09"), sbp = "m15a1_aa_halftrack_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_10"), sbp = "captain_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_11"), sbp = "m1_57mm_at_gun_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_12"), sbp = "m1_75mm_pack_howitzer_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_13"), sbp = "m5a1_stuart_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_14"), sbp = "major_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_15"), sbp = "m8a1_hmc_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_16"), sbp = "m4a3_sherman_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_17"), sbp = "m36_tank_destroyer_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_18"), sbp = "assault_engineer_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_19"), sbp = "pathfinder_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_20"), sbp = "paratrooper_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_21"), sbp = "paratrooper_squad_support_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_22"), sbp = "pathfinder_squad_recon_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_23"), sbp = "dodge_wc51_50cal_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_24"), sbp = "m8_greyhound_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_25"), sbp = "m3_halftrack_squad_assault_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_26"), sbp = "m21_mortar_halftrack_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_27"), sbp = "m4a3e8_sherman_easy_8_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_28"), sbp = "m4a3_76mm_sherman_bulldozer_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_29"), sbp = "m10_tank_destroyer_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_30"), sbp = "m7b1_priest_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_31"), sbp = "m4a3_76mm_sherman_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_32"), sbp = "riflemen_squad_veteran_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_33"), sbp = "ranger_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_34"), sbp = "m1919a4_hmg_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_35"), sbp = "m2_60mm_mortar_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_36"), sbp = "m1_81mm_mortar_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_37"), sbp = "ranger_squad_commander_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_38"), sbp = "m26_pershing_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_39"), sbp = "t34_calliope_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_aef_40"), sbp = "aef_halftrack_squad_mp", special = nil},
		},
		[4] = {
			{ability = CCM_GetAbilityBleprint("spawner_ukf_01"), sbp = "tommy_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_02"), sbp = "british_machine_gun_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_03"), sbp = "universal_carrier_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_04"), sbp = "sapper_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_05"), sbp = "sniper_british_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_06"), sbp = "brit_6_pounder_at_gun_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_07"), sbp = "aec_armoured_car_squad_mp", special = nil},	
			{ability = CCM_GetAbilityBleprint("spawner_ukf_08"), sbp = "centaur_aa_mk2_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_09"), sbp = "cromwell_mk4_75mm_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_10"), sbp = "sherman_firefly_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_11"), sbp = "comet_tank_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_12"), sbp = "churchill_default_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_13"), sbp = "churchill_crocodile_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_14"), sbp = "churchill_avre_squad_mp", special = nil},	
			{ability = CCM_GetAbilityBleprint("spawner_ukf_15"), sbp = "commando_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_16"), sbp = "commando_squad_piat_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_17"), sbp = "air_support_officer_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_18"), sbp = "valentine_observation_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_19"), sbp = "sexton_spg_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_20"), sbp = "sapper_squad_demolition_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_21"), sbp = "sapper_squad_recovery_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_22"), sbp = "m3_halftrack_squad__resupply_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_23"), sbp = "brit_land_mattress_launcher_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_24"), sbp = "infiltration_commando_squad_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_25"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_26"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_27"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_28"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_29"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_30"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_31"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_32"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_33"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_34"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_35"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_36"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_37"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_38"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_39"), sbp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("spawner_ukf_40"), sbp = "", special = nil},
		},
	}
	
	spawner_misc_spawn_ability = {
		[0] = {
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_01"), slot_item = "pioneer_flamethrower_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_02"), slot_item = "grenadier_mg42_lmg_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_03"), slot_item = "panzershreck_slot1_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_04"), slot_item = "panzerbusche_39_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_05"), ebp = "mg42_hmg_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_06"), ebp = "granatewerfer_34_81mm_mortar_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_07"), ebp = "pak40_75mm_at_gun_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_08"), ebp = "pak43_88mm_at_gun_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_09"), ebp = "howitzer_105mm_le_fh18_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_10"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_11"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_12"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_13"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_14"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_15"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_16"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_17"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_18"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_19"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_20"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_21"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_22"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_23"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_24"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_25"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_26"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_27"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_28"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_29"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_30"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_31"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_32"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_33"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_34"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_35"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_36"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_37"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_38"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_39"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_german_40"), ebp = "", special = nil},
		},
		[1] = {
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_01"), slot_item = "flamethrower_roks3_item_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_02"), slot_item = "dp-28_light_machine_gun_package_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_03"), slot_item = "ptrs_41_anti_tank_rifle_guard_troop_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_04"), ebp = "m1910_maxim_heavy_machine_gun_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_05"), ebp = "pm41_82mm_mortar_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_06"), ebp = "m1942_76mm_divisional_gun_zis-3_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_07"), ebp = "hm-120_38_mortar_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_08"), ebp = "m1937_152mm_ml_20_artillery_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_09"), ebp = "artillery_203mm_b4", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_10"), ebp = "dhsk_38_machine_gun_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_11"), ebp = "m1937_53-k_45mm_at_gun_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_12"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_13"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_14"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_15"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_16"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_17"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_18"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_19"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_20"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_21"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_22"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_23"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_24"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_25"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_26"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_27"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_28"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_29"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_30"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_31"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_32"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_33"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_34"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_35"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_36"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_37"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_38"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_39"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_soviet_40"), ebp = "", special = nil},
		},
		[2] = {
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_01"), slot_item = "panzershreck_slot1_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_02"), slot_item = "obersoldaten_mg34_lmg_moving_no_prone_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_03"), ebp = "raketenwerfer43_88mm_puppchen_antitank_gun_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_04"), ebp = "le_ig_18_inf_support_gun_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_05"), ebp = "pak43_88mm_at_gun_westgerman_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_06"), ebp = "mg34_hmg_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_07"), ebp = "flak_emplacement", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_08"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_09"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_10"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_11"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_12"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_13"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_14"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_15"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_16"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_17"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_18"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_19"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_20"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_21"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_22"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_23"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_24"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_25"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_26"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_27"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_28"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_29"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_30"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_31"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_32"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_33"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_34"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_35"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_36"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_37"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_38"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_39"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_west_german_40"), ebp = "", special = nil},
		},
		[3] = {
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_01"), slot_item = "riflemen_m1918_bar_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_02"), slot_item = "bazooka_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_03"), slot_item = "riflemen_30_cal", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_04"), slot_item = "assault_engineer_flamethrower", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_05"), slot_item = "paratrooper_m1919a6_lmg_moving_no_prone_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_06"), ebp = "m2hb_50cal_machine_gun_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_07"), ebp = "m1_57mm_antitank_gun_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_08"), ebp = "m1_75mm_pack_howitzer_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_09"), ebp = "m2_60mm_mortar_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_10"), ebp = "m1_81mm_mortar_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_11"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_12"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_13"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_14"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_15"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_16"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_17"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_18"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_19"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_20"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_21"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_22"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_23"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_24"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_25"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_26"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_27"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_28"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_29"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_30"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_31"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_32"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_33"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_34"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_35"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_36"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_37"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_38"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_39"), ebp = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_aef_40"), ebp = "", special = nil},
		},		
		[4] = {
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_01"), slot_item = "tommy_bren_light_machine_gun_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_02"), slot_item = "piat_spigot_mortar_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_03"), ebp = "brit_6_pounder_at_gun_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_04"), ebp = "brit_17_pounder_gun_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_05"), ebp = "brit_25_pounder_howitzer_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_06"), ebp = "brit_3_inch_mortar_emplacement", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_07"), ebp = "brit_bofors_40mm_autocannon_mp", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_08"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_09"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_10"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_11"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_12"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_13"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_14"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_15"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_16"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_17"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_18"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_19"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_20"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_21"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_22"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_23"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_24"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_25"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_26"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_27"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_28"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_29"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_30"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_31"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_32"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_33"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_34"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_35"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_36"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_37"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_38"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_39"), slot_item = "", special = nil},
			{ability = CCM_GetAbilityBleprint("misc_spawner_ukf_40"), slot_item = "", special = nil},
		},
	
	}
	
	g_building_ebp = {
{ebp = "armored_rifle_command_mp"},
{ebp = "armored_rifle_command_sp"},
{ebp = "armor_command_mp"},
{ebp = "armor_command_sp"},
{ebp = "company_weapons_pool_mp"},
{ebp = "company_weapons_pool_sp"},
{ebp = "rifle_command_mp"},
{ebp = "rifle_command_sp"},
{ebp = "armored_rifle_command_wreck_mp"},
{ebp = "armor_command_wreck_mp"},
{ebp = "company_weapons_pool_wreck_mp"},
{ebp = "rifle_command_wreck_mp"},
{ebp = "aef_barbed_wire_fence_mp"},
{ebp = "aef_mg_nest"},
{ebp = "aef_mg_nest_aef_base"},
{ebp = "aef_mg_nest_perimeter_mp"},
{ebp = "aef_mine_mp"},
{ebp = "aef_mine_riflemen_mp"},
{ebp = "aef_sandbags"},
{ebp = "aef_sandbag_fence"},
{ebp = "aef_tank_trap_impassable_mp"},
{ebp = "aef_tank_trap_mp"},
{ebp = "airborne_beacon_mp"},
{ebp = "invisi_heal_station_mp"},
{ebp = "invisi_repair_station_mp"},
{ebp = "m20_m6_at_mine_mp"},
{ebp = "major_retreat_point_mp"},
{ebp = "sherman_barrier_deform_mp"},
{ebp = "fighting_position_mp"},
{ebp = "fighting_position_riflemen_mp"},
{ebp = "observation_post_fuel_aef_mp"},
{ebp = "observation_post_munition_aef_mp"},
{ebp = "aef_weapon_rack_bazooka_mp"},
{ebp = "aef_weapon_rack_browning_automatic_rifle_mp"},
{ebp = "aef_weapon_rack_m1919_lmg"},
{ebp = "aef_weapon_rack_m1c_garand"},
{ebp = "pm_armor_command_bazooka_rack"},
{ebp = "pm_armor_command_lmg_rack"},
{ebp = "aef_airdropped_mine_contact_mp"},
{ebp = "aef_airdropped_mine_mp"},
{ebp = "aef_sandbagwall_cover_specialization"},
{ebp = "pm_aef_fighting_position_teamweapons"},
{ebp = "british_building_1_mp"},
{ebp = "british_building_1_unbuilt_mp"},
{ebp = "british_building_1_wreck_mp"},
{ebp = "british_building_2_mp"},
{ebp = "british_building_2_unbuilt_mp"},
{ebp = "british_building_2_wreck_mp"},
{ebp = "british_hq_truck_mp"},
{ebp = "british_hq_truck_wreck_mp"},
{ebp = "hq_field_artillery_mp"},
{ebp = "british_bunker_starting_position_mp"},
{ebp = "british_hq_sandbags_01_mp"},
{ebp = "british_radio_beacon"},
{ebp = "british_sandbag_fence_mp"},
{ebp = "brit_barbed_wire_fence_mp"},
{ebp = "brit_emplacement_small"},
{ebp = "brit_forward_hq_mp"},
{ebp = "brit_fwd_hq_weapon_rack_bren_lmg_mp"},
{ebp = "brit_fwd_hq_weapon_rack_piat_launcher_mp"},
{ebp = "brit_mine_mp"},
{ebp = "brit_retreat_point_mp"},
{ebp = "brit_sandbag_fence"},
{ebp = "brit_weapon_rack_bren_lmg_mp"},
{ebp = "brit_weapon_rack_piat_launcher_mp"},
{ebp = "slit_trench_mp"},
{ebp = "brit_17_pounder_pit_mp"},
{ebp = "brit_25_pounder_howitzer_mp"},
{ebp = "brit_3_inch_mortar_emplacement"},
{ebp = "brit_bofors_40mm_autocannon_mp"},
{ebp = "invisible_flame_mortar_icon"},
{ebp = "brit_25_pounder_howitzer_temp_mp"},
{ebp = "bereich_festung"},
{ebp = "bereich_festung_mp"},
{ebp = "dolch_aktionen"},
{ebp = "dolch_aktionen_mp"},
{ebp = "hintere_panzerwerk"},
{ebp = "hintere_panzerwerk_mp"},
{ebp = "schweres_kriegswerk"},
{ebp = "schweres_kriegswerk_mp"},
{ebp = "german_hq"},
{ebp = "german_hq_mp"},
{ebp = "german_hq_wreck"},
{ebp = "german_hq_wreck_mp"},
{ebp = "antitank_88mm_pak43_sandbags"},
{ebp = "german_mine"},
{ebp = "german_mine_mp"},
{ebp = "halftrack_riegel_43_mine_mp"},
{ebp = "mine_field"},
{ebp = "mine_field_mp"},
{ebp = "riegel_43_mine"},
{ebp = "riegel_43_mine_mp"},
{ebp = "slit_trench_german"},
{ebp = "slit_trench_german_mp"},
{ebp = "sniper_cover"},
{ebp = "sniper_digin_cover_mp"},
{ebp = "tank_trap"},
{ebp = "axis_bunker_starting_position"},
{ebp = "axis_bunker_starting_position_mp"},
{ebp = "bunker"},
{ebp = "bunker_mp"},
{ebp = "bunker_of_death_mp"},
{ebp = "invisible_retreat_point"},
{ebp = "fuel_post_german"},
{ebp = "fuel_post_german_mp"},
{ebp = "munition_post_german"},
{ebp = "munition_post_german_mp"},
{ebp = "howitzer_105mm_dummy"},
{ebp = "pak43_88mm_at_gun"},
{ebp = "pak43_88mm_at_gun_mp"},
{ebp = "howitzer_105mm_le_fh18"},
{ebp = "howitzer_105mm_le_fh18_mp"},
{ebp = "hintere_panzerwerk_voronezh"},
{ebp = "barracks"},
{ebp = "barracks_mp"},
{ebp = "motorpool"},
{ebp = "motorpool_mp"},
{ebp = "tank_depot"},
{ebp = "tank_depot_mp"},
{ebp = "weapon_support_center"},
{ebp = "weapon_support_center_mp"},
{ebp = "hq"},
{ebp = "hq_invisible_sp"},
{ebp = "hq_mp"},
{ebp = "hq_no_wreck"},
{ebp = "hq_wreck"},
{ebp = "hq_wreck_mp"},
{ebp = "anti_personnel_mines"},
{ebp = "barbed_wire_fence"},
{ebp = "barbed_wire_fence_mp"},
{ebp = "barbed_wire_field"},
{ebp = "barbed_wire_field_mp"},
{ebp = "light_anti_vehicle_mines"},
{ebp = "machine_gun_nest"},
{ebp = "machine_gun_nest_mp"},
{ebp = "repair_station_mp"},
{ebp = "sand_bag_soviet"},
{ebp = "sand_bag_soviet_mp"},
{ebp = "sand_bag_soviet_tutorial"},
{ebp = "soviet_mine"},
{ebp = "soviet_mine_mp"},
{ebp = "soviet_mine_tow"},
{ebp = "tanktrap"},
{ebp = "wire_field"},
{ebp = "wire_field_mp"},
{ebp = "observation_post_fuel"},
{ebp = "observation_post_fuel_mp"},
{ebp = "observation_post_munition"},
{ebp = "observation_post_munition_mp"},
{ebp = "soviet_mine_sp"},
{ebp = "hq_wreck_m06"},
{ebp = "forward_hq"},
{ebp = "soviet_mine_m08"},
{ebp = "artillery_203mm_b4"},
{ebp = "m1931_203mm_b-4_howitzer_artillery"},
{ebp = "m1931_203mm_b-4_howitzer_artillery_commander_mp"},
{ebp = "m1931_203mm_b-4_howitzer_artillery_mp"},
{ebp = "m1937_152mm_ml_20_artillery"},
{ebp = "m1937_152mm_ml_20_artillery_mp"},
{ebp = "heavy_armor_support_mp"},
{ebp = "infantry_support_mp"},
{ebp = "light_armor_support_mp"},
{ebp = "west_german_hq_mp"},
{ebp = "west_german_hq_wreck_mp"},
{ebp = "assault_pioneers_heavy_mine_mp"},
{ebp = "base_flak_sandbags"},
{ebp = "flak_emplacement"},
{ebp = "med_supply_stash"},
{ebp = "mine_field_westgerman_mp"},
{ebp = "reinforced_barbed_wire_fence_mp"},
{ebp = "reinforced_barbed_wire_tank_trap_mp"},
{ebp = "schu_mine_42_mp"},
{ebp = "siphon_structure"},
{ebp = "west_german_invisi_repair_station_mp"},
{ebp = "wg_barbed_wire_fence_mp"},
{ebp = "wg_sandbag_fence_mp"},
{ebp = "bunker_westgerman_mp"},
{ebp = "heavy_armor_support_preplaced"},
{ebp = "infantry_support_preplaced"},
{ebp = "light_armor_support_preplaced"},
{ebp = "howitzer_105mm_le_fh18_minichallenge"},
{ebp = "howitzer_105mm_long_range"},
{ebp = "pak43_88mm_at_gun_westgerman_mp"},



	}
	
end