-------------------------------------------------------------------------
-------------------------------------------------------------------------
-- Encounter Intent compositions used by the Encounter System
-- Each entry in the table corresponds to an encounter intent. Within 
-- each intent, each item is a variation of that intent.
--
-- When the Encounter System loads an intent, it will randomly choose one 
-- of the variations for the given intent, and add those units into the 
-- encounter's unit list.
--
-- Encounter intent can be defined with the parameter 'intent'.
-------------------------------------------------------------------------
-------------------------------------------------------------------------


ENC_INTENT = {
	__scardoc_enum = true,
	
	-- generic small infantry encounter
	basicInfantry = {
		{	
			--Each of these table entries correspond to an encounter unit, and respect all associated parameters.
			{
				sbp = SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			},
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
		},
		{	
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
		},
		{	
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
		},
		{	
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
		},
		{	
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
		},
		{	
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
		},
		{	
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
		},
	},
	
	medInfantry = {
		-- larger generic infantry encounter
		{	
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
		},
		{	
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
		},
		{	
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
		},
		{	
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP
		},
		{	
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
		},
		{	
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
		},
	},
	
	scoutForce = {
		{
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.GERMAN.SCOUTCAR_SDKFZ222_MP
		},
		{
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
			SBP.GERMAN.SNIPER_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.KUBELWAGEN_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.KUBELWAGEN_SQUAD_MP,
			SBP.WEST_GERMAN.KUBELWAGEN_SQUAD_MP,
		},
	},
	
	smallAntiInfantryDefense = {
		{
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
			SBP.WEST_GERMAN.FALLSCHIRMJAGER_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.KUBELWAGEN_SQUAD_MP,
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
		},
	},
	
	medAntiInfantryDefense = {
		{
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.FALLSCHIRMJAGER_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.FALLSCHIRMJAGER_SQUAD_MP,
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.OBERSOLDATEN_SQUAD_MP,
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.KUBELWAGEN_SQUAD_MP,
			SBP.WEST_GERMAN.KUBELWAGEN_SQUAD_MP,
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
		},
	},
	
	smallAntiTankDefense = {
		{
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.WEST_GERMAN.PAK40_75MM_AT_GUN_SQUAD_WG_MP,
		},
		{
			{
				sbp = SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
				upgrades = {UPG.WEST_GERMAN.ASSAULT_PIONEER_COMBAT_UPGRADE},
			},
		},
		{
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.RAKETENWERFER43_88MM_PUPPCHEN_ANTITANK_GUN_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.WEST_GERMAN.RAKETENWERFER43_88MM_PUPPCHEN_ANTITANK_GUN_SQUAD_MP,
		},
		{
			{
				sbp = SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
				upgrades = {UPG.WEST_GERMAN.ASSAULT_PIONEER_COMBAT_UPGRADE},
			},
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
		},
	},
	
	medAntiTankDefense = {
		{
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.RAKETENWERFER43_88MM_PUPPCHEN_ANTITANK_GUN_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.WEST_GERMAN.PAK40_75MM_AT_GUN_SQUAD_WG_MP,
		},
		{
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.WEST_GERMAN.RAKETENWERFER43_88MM_PUPPCHEN_ANTITANK_GUN_SQUAD_MP,
		},
		{
			{
				sbp = SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
				upgrades = {UPG.WEST_GERMAN.ASSAULT_PIONEER_COMBAT_UPGRADE},
			},
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP
		},
		{
			{
				sbp = SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
				upgrades = {UPG.WEST_GERMAN.ASSAULT_PIONEER_COMBAT_UPGRADE},
			},
			{
				sbp = SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
				upgrades = {UPG.WEST_GERMAN.ASSAULT_PIONEER_COMBAT_UPGRADE},
			},
		},
	},
	
	basicHMG = {
		-- hmg with at most one additional squad
		{
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
		},
	},
	
	medDefense = {
		-- hmg with additional infantry
		{
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.FALLSCHIRMJAGER_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
		},
	},

	heavyDefense = {
		-- mixed encounters
		{
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
			SBP.WEST_GERMAN.PAK40_75MM_AT_GUN_SQUAD_WG_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
			SBP.WEST_GERMAN.RAKETENWERFER43_88MM_PUPPCHEN_ANTITANK_GUN_SQUAD_MP,
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
			{
				sbp = SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
				upgrades = {UPG.WEST_GERMAN.ASSAULT_PIONEER_COMBAT_UPGRADE},
			},
		},
		{
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
			{
				sbp = SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
				upgrades = {UPG.WEST_GERMAN.ASSAULT_PIONEER_COMBAT_UPGRADE},
			},
		},
		{
			SBP.WEST_GERMAN.RAKETENWERFER43_88MM_PUPPCHEN_ANTITANK_GUN_SQUAD_MP,
			SBP.WEST_GERMAN.FALLSCHIRMJAGER_SQUAD_MP,
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
		},
		{
			{
				sbp = SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
				upgrades = {UPG.WEST_GERMAN.ASSAULT_PIONEER_COMBAT_UPGRADE},
			},
			SBP.WEST_GERMAN.OBERSOLDATEN_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
		},
		{
			
			SBP.WEST_GERMAN.OBERSOLDATEN_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.RAKETENWERFER43_88MM_PUPPCHEN_ANTITANK_GUN_SQUAD_MP,
		},
	},
	
	smallArtillery = {
		-- infantry support gun or mortar, with some extra regular infantry as support
		{
			SBP.WEST_GERMAN.LE_IG_18_INF_SUPPORT_GUN_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.GRW34_81MM_MORTAR_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.GRW34_81MM_MORTAR_SQUAD_MP,
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
		},
	},
	
	medArtillery = {
		-- infantry support gun or mortar with supporting infantry
		{
			SBP.WEST_GERMAN.LE_IG_18_INF_SUPPORT_GUN_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.LE_IG_18_INF_SUPPORT_GUN_SQUAD_MP,
			{
				sbp = SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
				upgrades = {UPG.WEST_GERMAN.ASSAULT_PIONEER_COMBAT_UPGRADE},
			},
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.GRW34_81MM_MORTAR_SQUAD_MP,
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
		},
	},
	
	lightArmour = {
		-- light armour and some infantry
		{
			SBP.WEST_GERMAN.ARMORED_CAR_SDKFZ_234_SQUAD_MP,
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.PANZER_II_LUCHS_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.PANZER_II_LUCHS_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.SDKFZ_251_17_FLAK_HALFTRACK_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.ARMORED_CAR_SDKFZ_234_SQUAD_MP,
			SBP.WEST_GERMAN.ARMORED_CAR_SDKFZ_234_SQUAD_MP,
		},
	},
	
	
	mediumArmour = {
		-- panzers and stugs
		{
			SBP.GERMAN.PANZER_IV_SQUAD_MP,
		},
		{
			SBP.GERMAN.STUG_III_SQUAD,
		},
		{
			SBP.GERMAN.STUG_III_E_SQUAD,
		},
		{
			SBP.WEST_GERMAN.JAGDPANZER_TANK_DESTROYER_SQUAD_MP,
		},
	},
	
	heavyArmour = {
		-- tiger, panther
		{
			SBP.WEST_GERMAN.KING_TIGER_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.STURMTIGER_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.JAGDTIGER_TD_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.PANTHER_AUSF_G_SQUAD_MP,
		},
	},
	
	
	-- Battle specific intents
	-- Advise not using these on regular missions
	battleBaseDefenses = {
		{
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
			SBP.WEST_GERMAN.RAKETENWERFER43_88MM_PUPPCHEN_ANTITANK_GUN_SQUAD_MP,
		},
	},
	
	battleCPDefenses = {
		{
			SBP.WEST_GERMAN.FALLSCHIRMJAGER_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.OBERSOLDATEN_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.WEST_GERMAN.LE_IG_18_INF_SUPPORT_GUN_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.RAKETENWERFER43_88MM_PUPPCHEN_ANTITANK_GUN_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			{
				sbp = SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
				upgrades = {UPG.WEST_GERMAN.ASSAULT_PIONEER_COMBAT_UPGRADE},
			},
		},
	},
	
	battleReverseHardpointAttack = {
		{
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.GERMAN.SCOUTCAR_SDKFZ222_MP
		},
		{
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP
		},
		{
			SBP.WEST_GERMAN.OBERSOLDATEN_SQUAD_MP,
			SBP.WEST_GERMAN.OBERSOLDATEN_SQUAD_MP,
			SBP.GERMAN.SCOUTCAR_SDKFZ222_MP,
		},
	},
	
	battleTotalDominationPhase1Attack = {
	
		{
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
		},	
		{
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.GERMAN.SCOUTCAR_SDKFZ222_MP
		},	
	},
	battleTotalDominationPhase2Attack = {
	
		{			
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.PANZER_II_LUCHS_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,			
			SBP.WEST_GERMAN.PANZER_II_LUCHS_SQUAD_MP,
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
			SBP.WEST_GERMAN.LE_IG_18_INF_SUPPORT_GUN_SQUAD_MP,
		},	
		{
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,			
			SBP.WEST_GERMAN.GRW34_81MM_MORTAR_SQUAD_MP,
		},	
	},
	
	battleTotalDominationPhase3Attack = {
	
		{
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.PANZER_II_LUCHS_SQUAD_MP,
			SBP.WEST_GERMAN.MORTAR_250_HALFTRACK_SQUAD_WESTGERMAN_MP,			
		},
		{
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.GERMAN.PANZER_IV_SQUAD_MP,
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
		},
		{
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.SCOUTCAR_223_SQUAD,
			SBP.WEST_GERMAN.MORTAR_250_HALFTRACK_SQUAD_WESTGERMAN_MP,
			SBP.WEST_GERMAN.VOLKSGRENADIER_SQUAD_MP,
		},	
		{
			SBP.WEST_GERMAN.PANZERFUSILIER_SQUAD_MP,
			SBP.WEST_GERMAN.ASSAULT_PIONEER_SQUAD_MP,
			SBP.WEST_GERMAN.GRW34_81MM_MORTAR_SQUAD_MP,
			SBP.WEST_GERMAN.MG34_HEAVY_MACHINE_GUN_SQUAD_MP,
		},	
	},
	
}

