--
-- PREFABS UTILITY SCRIPTS
--
-- Utilities for dealing with PREFAB data that comes from the World Builder.
--
-- 2015 Relic Entertainment
--



--? @group scardoc;Prefab System



-- Initialize ALL prefab instances from the PrefabData table generated by the WorldBuilder. 
-- Also distributes instance data from a single global data table into seperate instance tables with the instance's names.
function Prefab_InitAll()

	local inScenref = true
	if scartype(_WorldBuilder_PrefabData_reference) ~= ST_TABLE then
		-- not in scenref (or scenref prefabdata deleted)
		inScenref = false
	end

	if scartype(_WorldBuilder_PrefabData) ~= ST_TABLE then
		_WorldBuilder_PrefabData = {}
	end
	if scartype(_MissionScript_PrefabData) ~= ST_TABLE then
		_MissionScript_PrefabData = {}
	end
	
	for name, data in pairs(_WorldBuilder_PrefabData) do 
		if not inScenref or data.inScenRef then
			local newInstance = Clone(data)
			_G[name] = newInstance
		
			Prefab_Init(newInstance)
		end
	
	end

	if scartype(_WorldBuilder_PrefabData_reference) ~= ST_TABLE then
		_WorldBuilder_PrefabData_reference = {}
	end
	
	for name, data in pairs(_WorldBuilder_PrefabData_reference) do 
		local newInstance = Clone(data)
		local i = 2
		local basename = name
		while (_G[name] == ST_TABLE) do
			name = basename..tostring(i)
			i = i + 1
		end
		_G[name] = newInstance
		
		Prefab_Init(newInstance)
	
	end
	
end

Scar_AddInit(Prefab_InitAll)



--? @args Table/String instance_data
--? @result String name
--? @shortdesc Initialize a specific prefab instance. In many cases, this is all you need to do (see the documentation for the specific prefab for details)
function Prefab_Init(instance)
	
	-- if the prefab script/schema has not been loaded yet, load it now
	Prefab_Load(instance.prefabName)
	
	--  make sure this instance has a backup, so it can be reset, etc
	local instanceName = instance.instanceName
	
	-- check to see if the instance is script-built (i.e. not from the World Builder)
	if instanceName == nil or (_WorldBuilder_PrefabData[instanceName] == nil and _MissionScript_PrefabData[instanceName] == nil and _WorldBuilder_PrefabData_reference[instanceName] == nil) then
		
		-- generate a unique name for this instance
		instanceName = Prefab_GenerateUniqueInstanceName(instance)
		instance.instanceName = instanceName
	
		-- add this instance data to the MissionScript table so it can be retrieved again (i.e. for a reset)
		_MissionScript_PrefabData[instanceName] = Clone(instance)
		_G[instanceName] = instance
	
	end
	
	Prefab_ApplyDefaults(instance)

	local initFunction = _G[instance.prefabName.."_Init"]
	initFunction(instance)

	return instanceName
	
end



--? @args Table/String instance_data,  Table prefab_schema
--? @shortdesc Applies the defaults listed in the prefab schema to the instance data. Any items NOT included explicitly in the instance data will have default values pulled from the schema.
function Prefab_ApplyDefaults(instance)

	local prefabSchema = _G[string.lower(instance.prefabName.."_schema")]						-- find the schema for this prefab instance
	Prefab_ApplySchemaToDataTable(prefabSchema.itemSchema, instance)	-- apply the schema to the instance data
	
end



--? @args Table/String instance
--? @result InstanceData
--? @shortdesc Returns the instance data for a given instance, specified by a number of methods.
--? @extdesc This normalizes your instance data. You can pass in the instance name as a string, a data table with an instance subtable (i.e. the input params from an event function) or a real instance data table, and it normalizes the format and returns you the instance data table.
function Prefab_GetInstance(input)

	if scartype(input) == ST_STRING then
		
		return _G[input]								-- we got the instance name as a string, so look up the global variable for the instance data
		
	elseif scartype(input) == ST_TABLE then
		
		if input.instance ~= nil then
			
			return input.instance						-- we got a data table from an event, the data we want is in the instance field, so return that
			
		else
			
			return input									-- we got a different kind of table... assume it was an instance data table anyway, so return it as is
			
		end
		
	end

end



--? @args Table/String instance_data
--? @shortdesc Stops a prefab instance from continuing to run. 
--? @extdesc If the prefab has a prefabName_Stop() function, that will be called. Also, all events with the instance as the data parameter will be removed.
function Prefab_Stop(data)

	local instance = Prefab_GetInstance(data)
	
	local instanceName = instance.instanceName
	local prefabName = instance.prefabName
	
	-- call the prefab's Stop function if there is one
	local stop = _G[prefabName.."_Stop"]
	if scartype(stop) == ST_FUNCTION then
		stop(instance)
	end
	
	-- kill any events associated with this instance
	for index, event in ipairs(__Event_eventTable) do
		if scartype(event.data.instance) == ST_TABLE and event.data.instance.instanceName == instanceName then
			Event_Remove(event.eventID)
		end
	end
	
end



--? @args Table/String instance_data
--? @shortdesc Stop and restart a prefab instance, pulling a fresh set of the instance data from the WB-exported prefabs. This is meant for testing and debug purposes, rather than use in mission scripts.
function Prefab_Reset(data)

	local instance = Prefab_GetInstance(data)

	local instanceName = instance.instanceName
	local prefabName = instance.prefabName
	
	-- stop the old instance running
	Prefab_Stop(instance)
	
	-- move a fresh copy of the instance data from the instance prefab data table into the variable 
	local newInstance = nil
	if scartype(_WorldBuilder_PrefabData) == ST_TABLE and _WorldBuilder_PrefabData[instanceName] ~= nil then
		newInstance = Clone(_WorldBuilder_PrefabData[instanceName])
	elseif scartype(_MissionScript_PrefabData) == ST_TABLE and _MissionScript_PrefabData[instanceName] ~= nil then
		newInstance = Clone(_MissionScript_PrefabData[instanceName])
	else
		return
	end
	
	_G[instanceName] = newInstance
	
	-- run Init on the new instance
	Prefab_Init(newInstance)
	
end



--? @args Table/String instance_data, String actionName
--? @shortdesc Calls an action function with a given name on an instance, making sure it calls the right version for the type of Prefab. Instance can be a string, this will convert it.
--? @extdesc Example: Calling the "Trigger" action on an instance that is a PlaneCrash prefab will look for a function called "PlaneCrash_Trigger"
function Prefab_DoAction(data, actionName)

	local instance = Prefab_GetInstance(data)
	
	if scartype(instance) == ST_TABLE then
	
		local prefabName = instance.prefabName
		
		if scartype(prefabName) == ST_STRING and scartype(actionName) == ST_STRING  then
			
			local prefabFunctionName = prefabName.."_"..actionName
			local prefabFunction = _G[prefabFunctionName]
			
			if scartype(prefabFunction) == ST_FUNCTION then
				
				return prefabFunction(instance)
				
			else
				
				print(prefabFunctionName.."() does not exist")
				
			end
			
		end
		
	else
		
		if scartype(data) == ST_STRING then
			print("Prefab_DoAction: No instance named "..data.." found")
		else
			print("Prefab_DoAction: No instance found")
		end
		
	end
	
end







--
-- INTERNAL FUNCTIONS 
--




-- generate a unique instance name for this instance
-- will be of the form <prefabName>_Instance<number>
function Prefab_GenerateUniqueInstanceName(data)

	local instance = Prefab_GetInstance(data)
	
	if _Prefabs_NewInstanceNumber == nil then
		_Prefabs_NewInstanceNumber = 1
	else
		_Prefabs_NewInstanceNumber = _Prefabs_NewInstanceNumber + 1
	end
	
	return instance.prefabName.."_Instance".._Prefabs_NewInstanceNumber

end



-- The WorldBuilder reset button hooks up to this function
-- This is because it only knows the the instance by it's name, rather than as an instance data table. 
-- This function converts it, and then calls the real Prefab_Restart function
function Prefab_ResetFromWorldBuilder(data)

	--
	-- To-do: reload the WorldBuilder-exported prefab data table
	--
	
	local instance = Prefab_GetInstance(data)
	
	if scartype(instance) == ST_TABLE and instance.instanceName == instanceName then
		Prefab_Restart(instance)
	end
	
end



-- Applies a schema to one level of a data table
-- Calls itself recursively to deal with deep tables
function Prefab_ApplySchemaToDataTable(schemaTable, data)

	-- loop through items _in the schema_
	for index, schema in pairs(schemaTable) do
		
		-- if the data has no matching item for this key, insert the default (if there is one!)
		if data[schema.name] == nil then
			if schema.default ~= nil then
				data[schema.name] = schema.default
			end
		end
		
		-- swap data elements from strings to real items according to their schema type
		data[schema.name] = Prefab_ReplaceDataWithProperType(data[schema.name], schema)
		
		-- if the item is a table, run this function on that sub-set of the schema and data
		if schema.type == ST_TABLE and scartype(data[schema.name]) == ST_TABLE and scartype(schema.itemSchema) == ST_TABLE then
		
			if schema.multiplicity == "multiple" then
				for subindex, subitem in pairs(data[schema.name]) do
					Prefab_ApplySchemaToDataTable(schema.itemSchema, subitem)
				end
			elseif schema.multiplicity == "single" then
				Prefab_ApplySchemaToDataTable(schema.itemSchema, data[schema.name])
			end

		end
		
	end
	
end



-- Items come in/out of the worldbuilder as strings in the data table. 
-- This function converts a string representation of a player, marker, etc, to a proper type.
function Prefab_ReplaceDataWithProperType(data, schema)

	if scartype(data) == ST_STRING and schema.type ~= ST_STRING then
		
		if schema.type == ST_PLAYER then
			
			if string.sub(data, 0, 6) == "Player" then
				if string.sub(data, 7, 7) == " " then
					return World_GetPlayerAt(tonumber(string.sub(data, 8, 8))) -- get the player index by just grabbing the X in "Player X"
				else
					return World_GetPlayerAt(tonumber(string.sub(data, 7, 7)))
				end
			elseif data.name == "World" then
				return nil
			end

		elseif schema.type == ST_PBG and data ~= "" then
			
			if schema.blueprintType == "squad" then
				return BP_GetSquadBlueprint(data)
			elseif schema.blueprintType == "entity" then
				return BP_GetEntityBlueprint(data)
			elseif schema.blueprintType == "upgrade" then
				return BP_GetUpgradeBlueprint(data)
			elseif schema.blueprintType == "ability" then
				return BP_GetAbilityBlueprint(data)
			end
			
		elseif schema.type == ST_EGROUP and data ~= "" then
			
			return EGroup_CreateIfNotFound(data)
			
		elseif schema.type == ST_SGROUP and data ~= "" then
			
			return SGroup_CreateIfNotFound(data)
			
		elseif schema.type == "ST_LOCSTRING"	then
			
			if string.sub(data, 0, 1) == "$" then
				return string.sub(data, 1)
			else
				return LOC(data)
			end
			
		end
		
	elseif schema.type == ST_MARKER and type(data) == 'table' then
		return Marker_Create(data.name, "Prefab", World_Pos(data.posx, data.posy, data.posz), World_Pos(data.dirx, data.diry, data.dirz), data.rad)
	end
	
	-- default
	return data

end





-- 
function Prefab_Load(prefabName)

	if scartype(_G[string.lower(prefabName.."_schema")]) ~= ST_TABLE then
		
		import("Prefabs/"..prefabName..".scar")
		import("Prefabs/"..prefabName.."_schema.scar")
		
		if _Prefabs_UsedPrefabList == nil then
			_Prefabs_UsedPrefabList = {prefabName}
		else
			table.insert(_Prefabs_UsedPrefabList, prefabName)
		end
		
	end

end

function Prefab_ReloadAll()

	if scartype(_Prefabs_UsedPrefabList) == ST_TABLE then
		
		for index, prefabName in pairs(_Prefabs_UsedPrefabList) do
			
			print("Reloading prefab "..prefabName)
			
			import("Prefabs/"..prefabName..".scar")
			import("Prefabs/"..prefabName.."_schema.scar")
			
		end
		
	end
	
end

Prefab_ReloadAll()	-- reload prefabs when you hit the reload scripts button







--
-- HELPER FUNCTIONS 
--



--? @args Table/String instance_data
--? @shortdesc Add this helper function to your prefab's Init function to cover standard trigger zone functionality. 
--? @extdesc It will call a Trigger function in your prefab when appropriate. Your schema needs to include the standard elements: trigger_enable, ignore_planes, trigger_player, trigger_zone and delay
function PrefabHelper_StandardTriggerSystem(data)

	local instance = Prefab_GetInstance(data)

	if instance.trigger_enable ~= false then
		
		local event_data = {instance = instance}
		
		if instance.ignore_planes == true then
			event_data.filterlist = LIST.AIRCRAFT
			event_data.filtertype = FILTER_REMOVE
		end
		
		Event_Proximity(PrefabHelper_StandardTriggerSystem_Trigger, event_data, instance.trigger_player, instance.trigger_zone, Marker_GetProximityRadius(instance.trigger_zone), ANY, instance.delay)
		
	end
	
end

function PrefabHelper_StandardTriggerSystem_Trigger(data)

	local instance = Prefab_GetInstance(data)

	Prefab_DoAction(instance, "Trigger")
	
end
