function TC_DataInit()
	g_mine_ebps_data = {
		["axis_mine_visual"] = {icon = "", name = ""},
		["aef_mine_mp"] = {icon = "Icons_symbols_building_aef_m7_light_at_mine_symbol", name = "M7 Light Anti-Tank Mine", article = "an"},
		["aef_mine_riflemen_mp"] = {icon = "Icons_symbols_building_aef_m7_light_at_mine_symbol", name = "M7 Light Anti-Tank Mine", article = "an"},
		["m20_m6_at_mine_mp"] = {icon = "Icons_symbols_ability_aef_m6_at_mines_symbol", name = "M6 Anti-Tank Mine", article = "an"},
		["aef_airdropped_mine_mp"] = {icon = "Icons_symbols_building_aef_m7_light_at_mine_symbol", name = "M83 Cluster Bomb", article = "an"},
		["german_mine_mp"] = {icon = "Icons_symbols_building_german_mines_symbol", name = "Teller Mines", article = ""},
		["halftrack_riegel_43_mine_mp"] = {icon = "Icons_symbols_building_german_mines_symbol", name = "Riegel 43 Anti-tank Mine", article = "a"},
		["mine_field_mine_mp"] = {icon = "Icons_symbols_building_german_mine_field_symbol", name = "S-Mine Field", article = "an"},
		["mine_field_mp"] = {icon = "Icons_symbols_building_german_mine_field_symbol", name = "S-Mine Field", article = "an"},
		["riegel_43_mine_mp"] = {icon = "Icons_symbols_building_german_mines_symbol", name = "Riegel 43 Anti-tank Mine", article = "a"},
		["anti_personnel_mines"] = {icon = "Icons_symbols_cmdr_german_mine_pmd6_symbol", name = "PMD-6 Anti-Personnel Mine", article = "a"},
		["flare_mine"] = {icon = "Icons_symbols_ability_soviet_tm35_mines_symbol", name = "POMZ Flare Trip Mine", article = "a"},
		["flare_mine_mp"] = {icon = "Icons_symbols_ability_soviet_tm35_mines_symbol", name = "POMZ Flare Trip Mine", article = "a"},
		["light_anti_vehicle_mines"] = {icon = "Icons_symbols_building_soviet_at_mine_symbol", name = "PMD-6M Light Anti-Vehicle Mines", article = ""},
		["soviet_mine"] = {icon = "Icons_symbols_ability_soviet_tm35_mines_symbol", name = "TM-35 Mine", article = "a"},
		["soviet_mine_mp"] = {icon = "Icons_symbols_ability_soviet_tm35_mines_symbol", name = "TM-35 Mine", article = "a"},
		["assault_pioneers_heavy_mine_mp"] = {icon = "Icons_symbols_building_german_mines_symbol", name = "Riegel 43 Anti-tank Mine", article = "a"},
		["mine_field_westgerman_mp"] = {icon = "Icons_symbols_building_german_mine_field_symbol", name = "S-Mine Field", article = "an"},
		["schu_mine_42_mp"] = {icon = "Icons_symbols_building_west_german_schu_mine_symbol", name = "Schu-Mine 42", article = "a"},
	}	
	g_sbps_data = {
		 ["m4a3_sherman_squad_demo_burnout"] = {icon = "Icons_symbols_vehicle_aef_m4a3_sherman_symbol", name = ""},
		 ["pm_riflemen_squad_omcg"] = {icon = "Icons_symbols_unit_aef_cavalry_riflemen", name = "Cavalry Riflemen"},
		 ["aef_attack_plane_squad"] = {icon = "Icons_symbols_vehicle_soviet_il2_symbol", name = ""},
		 ["pm_m3_halftrack_squad_omcg"] = {icon = "Icons_symbols_vehicle_aef_halftrack_m3_symbol", name = "M3 Half-track"},
		 ["pm_aef_airborne_paratroopers_plane_paras"] = {icon = "", name = ""},
		 ["pm_aef_airborne_paratroopers_plane_strafe"] = {icon = "", name = ""},
		 ["aef_air_support_recon"] = {icon = "Icons_symbols_vehicle_soviet_il2_symbol", name = ""},
		 ["aef_air_support_rocket"] = {icon = "Icons_symbols_vehicle_soviet_il2_symbol", name = ""},
		 ["aef_air_support_rocket_elite"] = {icon = "Icons_symbols_vehicle_soviet_il2_symbol", name = ""},
		 ["aef_air_support_strafe"] = {icon = "Icons_symbols_vehicle_soviet_il2_symbol", name = ""},
		 ["aef_air_support_strafe_elite"] = {icon = "Icons_symbols_vehicle_soviet_il2_symbol", name = ""},
		 ["p47_flyby"] = {icon = "Icons_minimap_aef_p47_36x36", name = ""},
		 ["p47_mg_strafe"] = {icon = "Icons_minimap_aef_p47_36x36", name = ""},
		 ["p47_rockets_strafe"] = {icon = "Icons_minimap_aef_p47_36x36", name = ""},
		 ["pm_aef_airborne_supply_drop_plane"] = {icon = "", name = ""},
		 ["jackson_squad"] = {icon = "Icons_symbols_unit_aef_officer_major_symbol", name = "Capt. Jackson"},
		 ["assault_engineer_squad_5_man_mp"] = {icon = "Icons_symbols_unit_aef_assault_engineers_symbol", name = ""},
		 ["assault_engineer_squad_mp"] = {icon = "Icons_symbols_unit_aef_assault_engineers_symbol", name = "Assault Engineer Squad"},
		 ["captain_squad_mp"] = {icon = "Icons_symbols_unit_aef_officer_captain_symbol", name = "Captain"},
		 ["lieutenant_squad_mp"] = {icon = "Icons_symbols_unit_aef_officer_lieutenant_symbol", name = "Lieutenant"},
		 ["major_squad_mp"] = {icon = "Icons_symbols_unit_aef_officer_major_symbol", name = "Major"},
		 ["paratrooper_combat_group_squad_mp"] = {icon = "Icons_symbols_unit_aef_paratroopers_symbol", name = "Paratroopers"},
		 ["paratrooper_squad_mp"] = {icon = "Icons_symbols_unit_aef_paratroopers_symbol", name = "Paratroopers"},
		 ["paratrooper_squad_support_mp"] = {icon = "Icons_symbols_unit_aef_paratroopers_symbol", name = "Paratrooper Support Squad"},
		 ["pathfinder_squad_mp"] = {icon = "Icons_symbols_unit_aef_pathfinders_symbol", name = "Pathfinders"},
		 ["pathfinder_squad_recon_mp"] = {icon = "Icons_symbols_unit_aef_pathfinders_i_and_r_symbol", name = "I&R Pathfinders"},
		 ["ranger_squad_mp"] = {icon = "Icons_symbols_unit_aef_rangers_symbol", name = "Rangers"},
		 ["rear_echelon_squad_mp"] = {icon = "Icons_symbols_unit_aef_rear_echelon_troops_symbol", name = "Rear Echelon Troops"},
		 ["riflemen_squad_mp"] = {icon = "Icons_symbols_unit_aef_riflemen_symbol", name = "Riflemen"},
		 ["riflemen_squad_veteran_mp"] = {icon = "Icons_symbols_unit_aef_riflemen_symbol", name = "Veteran Riflemen"},
		 ["usf_medic_squad_mp"] = {icon = "Icons_symbols_unit_aef_medic_symbol", name = "Medics"},
		 ["m20_assault_engy_antitank_squad_mp"] = {icon = "Icons_symbols_unit_aef_vehicle_crew_symbol", name = "Vehicle Crew"},
		 ["vehicle_crew_bazooka_squad_mp"] = {icon = "Icons_symbols_unit_aef_vehicle_crew_symbol", name = "M20 Vehicle Crew"},
		 ["vehicle_crew_squad_mp"] = {icon = "Icons_symbols_unit_aef_vehicle_crew_symbol", name = "Vehicle Crew"},
		 ["m1919a4_hmg_squad_mp"] = {icon = "Icons_symbols_unit_soviet_mg_symbol", name = "M1919A4 .30 cal Machine Gun"},
		 ["m1_57mm_at_gun_squad_bob"] = {icon = "Icons_symbols_vehicle_aef_57mm_at_gun_symbol", name = "M1 57mm Anti-Tank Gun"},
		 ["m1_57mm_at_gun_squad_mp"] = {icon = "Icons_symbols_vehicle_aef_57mm_at_gun_symbol", name = "M1 57mm Anti-Tank Gun"},
		 ["m1_75mm_pack_howitzer_squad_mp"] = {icon = "Icons_symbols_vehicle_aef_pack_howitzer_symbol", name = "M1 75mm Pack Howitzer"},
		 ["m1_81mm_mortar_squad_mp"] = {icon = "Icons_symbols_unit_soviet_mortar_symbol", name = "M1 81mm Mortar Team"},
		 ["m2hb_50cal_hmg_squad_mp"] = {icon = "Icons_symbols_vehicle_aef_browning_m2_50cal_hmg_symbol", name = "M2HB .50 cal Machine Gun Team"},
		 ["m2_60mm_mortar_squad_mp"] = {icon = "Icons_symbols_unit_german_granatwerfer_34_mortar_symbol", name = "M2 60mm Mortar Team"},
		 ["dodge_wc51_50cal_squad_mp"] = {icon = "Icons_symbols_vehicle_aef_wc51_50cal_symbol", name = "WC51 Military Truck w/ .50 cal HMG"},
		 ["dodge_wc51_ambulance_squad_mp"] = {icon = "Icons_symbols_vehicle_aef_wc51_ambulance_symbol", name = "WC54 ¾ Ton Ambulance"},
		 ["dodge_wc51_pathfinder_squad_mp"] = {icon = "Icons_symbols_vehicle_aef_wc51_50cal_symbol", name = "WC51 Military Truck"},
		 ["dodge_wc51_squad_mp"] = {icon = "Icons_symbols_vehicle_aef_wc51_50cal_symbol", name = "WC51 Military Truck w/ .50 cal HMG"},
		 ["m10_tank_destroyer_squad_mp"] = {icon = "Icons_symbols_vehicle_aef_m10_tank_destroyer_symbol", name = "M10 'Wolverine' Tank Destroyer"},
		 ["m20_utility_car_squad_mp"] = {icon = "Icons_symbols_vehicle_aef_m20_utility_car_symbol", name = "M20 Utility Car"},
		 ["m36_tank_destroyer_squad_mp"] = {icon = "Icons_symbols_vehicle_aef_m36_jackson_symbol", name = "M36 'Jackson' Tank Destroyer"},
		 ["m15a1_aa_halftrack_squad_mp"] = {icon = "Icons_symbols_vehicle_aef_halftrack_m15a1_aa_symbol", name = "M15A1 AA Half-track"},
		 ["m21_mortar_halftrack_squad_mp"] = {icon = "Icons_symbols_vehicle_aef_halftrack_m21_mortar_symbol", name = "M21 Mortar Half-track"},
		 ["m3_halftrack_squad_assault_mp"] = {icon = "Icons_symbols_vehicle_aef_halftrack_m3_symbol", name = "M3 Half-track"},
		 ["m3_halftrack_squad_mp"] = {icon = "Icons_symbols_vehicle_aef_halftrack_m3_symbol", name = "M3 Half-track"},
		 ["m4a3e8_sherman_easy_8_squad_mp"] = {icon = "Icons_symbols_vehicle_aef_m4a3e8_sherman_symbol", name = "M4A3E8 Sherman 'Easy Eight'"},
		 ["m4a3_76mm_sherman_bulldozer_squad_mp"] = {icon = "Icons_symbols_vehicle_aef_m4a3_sherman_symbol", name = "105mm Bulldozer Sherman"},
		 ["m4a3_76mm_sherman_squad_mp"] = {icon = "Icons_symbols_vehicle_aef_m4a3_sherman_symbol", name = "M4A3(76) Sherman Medium Tank"},
		 ["m4a3_sherman_squad_mp"] = {icon = "Icons_symbols_vehicle_aef_m4a3_sherman_symbol", name = "M4A3 Sherman Medium Tank"},
		 ["m5a1_stuart_squad_mp"] = {icon = "Icons_symbols_vehicle_aef_m5a1_stuart_symbol", name = "M5A1 Stuart"},
		 ["m7b1_priest_squad_mp"] = {icon = "Icons_symbols_vehicle_aef_m7b1_priest_symbol", name = "M7B1 'Priest' Howitzer Motor Carriage"},
		 ["m8a1_hmc_squad_mp"] = {icon = "Icons_symbols_vehicle_aef_m8a1_hmc_symbol", name = "M8A1 Howitzer Motor Carriage"},
		 ["m8_greyhound_squad_mp"] = {icon = "Icons_symbols_vehicle_aef_m8_greyhound_symbol", name = "M8 Greyhound"},
		 ["paratroopers_combat_group_plane"] = {icon = "Icons_minimap_aef_c47_skytrain_36x36", name = ""},
		 ["paratroopers_plane"] = {icon = "Icons_minimap_aef_c47_skytrain_36x36", name = ""},
		 ["paratroopers_plane_atgun"] = {icon = "Icons_minimap_aef_c47_skytrain_36x36", name = ""},
		 ["paratroopers_plane_hmg"] = {icon = "Icons_minimap_aef_c47_skytrain_36x36", name = ""},
		 ["paratroopers_plane_paras"] = {icon = "Icons_minimap_aef_c47_skytrain_36x36", name = ""},
		 ["p47_recon"] = {icon = "Icons_minimap_aef_p47_36x36", name = ""},
		 ["p47_recon_plane_sweep"] = {icon = "Icons_minimap_aef_p47_36x36", name = ""},
		 ["p47_recon_tracking"] = {icon = "Icons_minimap_aef_p47_36x36", name = ""},
		 ["p47_rockets"] = {icon = "Icons_minimap_aef_p47_36x36", name = ""},
		 ["p47_strafes"] = {icon = "Icons_minimap_aef_p47_36x36", name = ""},
		 ["m01_mg42_heavy_machine_gun_squad_single"] = {icon = "Icons_symbols_unit_german_m1910_hmg_symbol", name = "MG42 Heavy Machine Gun"},
		 ["m01_stuka_dogfight"] = {icon = "", name = ""},
		 ["m01_stuka_ground_attack_squad_fast"] = {icon = "", name = "JU-87 Stuka"},
		 ["stuka_ground_attack_squad_long"] = {icon = "", name = "JU-87 Stuka"},
		 ["partisan_squad_m13"] = {icon = "Icons_symbols_unit_german_grenadier_symbol", name = "Partisan Squad"},
		 ["howitzer_105mm_dummy_squad"] = {icon = "Icons_symbols_vehicle_german_howitzer_symbol", name = ""},
		 ["grenadier_squad_m14"] = {icon = "Icons_symbols_unit_german_grenadier_symbol", name = "Grenadier"},
		 ["ostruppen_squad_m14"] = {icon = "Icons_symbols_unit_german_grenadier_symbol", name = "Osttruppen"},
		 ["panzer_grenadier_squad_m14"] = {icon = "Icons_symbols_unit_german_panzer_grenadier_symbol", name = ""},
		 ["panzer_iv_squad_tutorial"] = {icon = "Icons_symbols_vehicle_german_panzer_iv_symbol", name = ""},
		 ["opel_blitz_squad"] = {icon = "Icons_symbols_vehicle_german_opel_blitz_symbol", name = "Opel Blitz Cargo Truck"},
		 ["assault_grenadier_squad_mp"] = {icon = "Icons_symbols_unit_german_assault_grenadier_symbol", name = "Assault Grenadiers"},
		 ["grenadier_squad"] = {icon = "Icons_symbols_unit_german_grenadier_symbol", name = "Grenadiers"},
		 ["grenadier_squad_mg42lmg_mp"] = {icon = "Icons_symbols_unit_german_grenadier_symbol", name = "Grenadiers"},
		 ["grenadier_squad_mp"] = {icon = "Icons_symbols_unit_german_grenadier_symbol", name = "Grenadiers"},
		 ["grenadier_squad_sp"] = {icon = "Icons_symbols_unit_german_grenadier_symbol", name = "Grenadiers"},
		 ["mg42_heavy_machine_gun_squad"] = {icon = "Icons_symbols_unit_german_m1910_hmg_symbol", name = "MG42 Heavy Machine Gun Team"},
		 ["mg42_heavy_machine_gun_squad_mp"] = {icon = "Icons_symbols_unit_german_m1910_hmg_symbol", name = "MG42 Heavy Machine Gun Team"},
		 ["mortar_team_81mm"] = {icon = "Icons_symbols_unit_german_granatwerfer_34_mortar_symbol", name = "GrW 34 Mortar Team"},
		 ["mortar_team_81mm_mp"] = {icon = "Icons_symbols_unit_german_granatwerfer_34_mortar_symbol", name = "GrW 34 Mortar Team"},
		 ["assault_officer_squad"] = {icon = "Icons_symbols_unit_german_officer_symbol", name = "Artillery Field Officer"},
		 ["assault_officer_squad_mp"] = {icon = "Icons_symbols_unit_german_officer_symbol", name = "Artillery Field Officer"},
		 ["command_officer_squad_tow"] = {icon = "Icons_symbols_unit_german_officer_symbol", name = "Mechanized Assault Commander"},
		 ["luftwaffe_officer_squad_tow"] = {icon = "Icons_symbols_unit_german_officer_symbol", name = "Luftwaffe Field Officer"},
		 ["officer_squad"] = {icon = "Icons_symbols_unit_german_officer_symbol", name = "German Officer"},
		 ["officer_squad_mp"] = {icon = "Icons_symbols_unit_german_officer_symbol", name = "German Officer"},
		 ["ostruppen_squad"] = {icon = "Icons_symbols_unit_german_ostruppen_symbol", name = "Osttruppen Squad"},
		 ["ostruppen_squad_mp"] = {icon = "Icons_symbols_unit_german_ostruppen_symbol", name = "Osttruppen Squad"},
		 ["ostruppen_squad_reserves_mp"] = {icon = "Icons_symbols_unit_german_ostruppen_symbol", name = "Osttruppen Squad"},
		 ["panzer_grenadier_squad"] = {icon = "Icons_symbols_unit_german_panzer_grenadier_symbol", name = "Panzergrenadiers"},
		 ["panzer_grenadier_squad_mp"] = {icon = "Icons_symbols_unit_german_panzer_grenadier_symbol", name = "Panzergrenadiers"},
		 ["urban_assault_panzer_grenadier_squad_mp"] = {icon = "Icons_symbols_unit_german_urban_assault_panzer_grenadier_symbol", name = "Urban Assault Panzergrenadiers"},
		 ["convoy_pioneer_squad"] = {icon = "Icons_symbols_unit_german_pioneer_symbol", name = "Pioneer Squad"},
		 ["hack_invisi_pioneer_squad_mp"] = {icon = "", name = ""},
		 ["pioneer_squad"] = {icon = "Icons_symbols_unit_german_pioneer_symbol", name = "Pioneer Squad"},
		 ["pioneer_squad_mp"] = {icon = "Icons_symbols_unit_german_pioneer_symbol", name = "Pioneer Squad"},
		 ["pioneer_squad_tow"] = {icon = "Icons_symbols_unit_german_pioneer_symbol", name = "Pioneer Squad"},
		 ["sniper_squad"] = {icon = "Icons_symbols_unit_german_sniper_symbol", name = "Sniper"},
		 ["sniper_squad_mp"] = {icon = "Icons_symbols_unit_german_sniper_symbol", name = "Sniper"},
		 ["stormtrooper_squad_mp"] = {icon = "Icons_symbols_unit_german_stormtroopers_symbol", name = "Stormtroopers"},
		 ["pak40_75mm_at_gun_squad"] = {icon = "Icons_symbols_vehicle_german_pak_40_75mm_at_gun_symbol", name = "Pak 40 7.5cm Anti-tank Gun"},
		 ["pak40_75mm_at_gun_squad_mp"] = {icon = "Icons_symbols_vehicle_german_pak_40_75mm_at_gun_symbol", name = "Pak 40 7.5cm Anti-tank Gun"},
		 ["pak43_88mm_at_gun_squad"] = {icon = "Icons_symbols_vehicle_german_pak_43_at_gun_symbol", name = "Pak 43 88mm Anti-tank gun"},
		 ["pak43_88mm_at_gun_squad_mp"] = {icon = "Icons_symbols_vehicle_german_pak_43_at_gun_symbol", name = "Pak 43 88mm Anti-tank gun"},
		 ["brummbar_squad"] = {icon = "Icons_symbols_vehicle_german_sturmpanzer_symbol", name = "Sturmpanzer IV \"Brummbär\""},
		 ["brummbar_squad_mp"] = {icon = "Icons_symbols_vehicle_german_sturmpanzer_symbol", name = "Sturmpanzer IV \"Brummbär\""},
		 ["elefant_tank_destroyer_squad"] = {icon = "Icons_symbols_vehicle_german_elefant_tank_destroyer_symbol", name = "Elefant Heavy Tank Destroyer"},
		 ["elefant_tank_destroyer_squad_mp"] = {icon = "Icons_symbols_vehicle_german_elefant_tank_destroyer_symbol", name = "Elefant Heavy Tank Destroyer"},
		 ["mechanized_250_halftrack_grenadiers_mp"] = {icon = "Icons_symbols_vehicle_german_250_halftrack_symbol", name = "SdKfz 250 Half-track"},
		 ["mechanized_250_halftrack_mp"] = {icon = "Icons_symbols_vehicle_german_250_halftrack_symbol", name = "SdKfz 250 Half-track"},
		 ["mechanized_250_halftrack_tow"] = {icon = "Icons_symbols_vehicle_german_250_halftrack_symbol", name = "SdKfz 250 Half-track"},
		 ["mortar_250_halftrack_squad"] = {icon = "Icons_symbols_vehicle_german_251_mortar_halftrack_symbol", name = "SdKfz 250/7 Mortar Half-track"},
		 ["mortar_250_halftrack_squad_mp"] = {icon = "Icons_symbols_vehicle_german_251_mortar_halftrack_symbol", name = "SdKfz 250/7 Mortar Half-track"},
		 ["sdkfz_221_light_at_halftrack"] = {icon = "Icons_symbols_vehicle_german_251_mortar_halftrack_symbol", name = ""},
		 ["sdkfz_251_halftrack_squad"] = {icon = "Icons_symbols_vehicle_german_251_halftrack_symbol", name = "SdKfz 251 Half-track"},
		 ["sdkfz_251_halftrack_squad_mp"] = {icon = "Icons_symbols_vehicle_german_251_halftrack_symbol", name = "SdKfz 251 Half-track"},
		 ["howitzer_105mm_le_fh18_artillery"] = {icon = "Icons_symbols_vehicle_german_howitzer_symbol", name = "10.5cm leFH 18 Artillery"},
		 ["howitzer_105mm_le_fh18_artillery_mp"] = {icon = "Icons_symbols_vehicle_german_howitzer_symbol", name = "10.5cm leFH 18 Artillery"},
		 ["opel_blitz_supply_squad"] = {icon = "Icons_symbols_vehicle_german_opel_blitz_symbol", name = "Opel Blitz Cargo Truck"},
		 ["ostwind_squad"] = {icon = "Icons_symbols_vehicle_german_ostwind_flak_panzer_symbol", name = "Flakpanzer IV Ostwind"},
		 ["ostwind_squad_mp"] = {icon = "Icons_symbols_vehicle_german_ostwind_flak_panzer_symbol", name = "Flakpanzer IV Ostwind"},
		 ["panther_squad"] = {icon = "Icons_symbols_vehicle_german_panther_symbol", name = "Panther PzKpfw V Medium Tank"},
		 ["panther_squad_mp"] = {icon = "Icons_symbols_vehicle_german_panther_symbol", name = "Panther PzKpfw V Medium Tank"},
		 ["panzerwerfer_squad"] = {icon = "Icons_symbols_vehicle_german_panzerwerfer_symbol", name = "Panzerwerfer 42 Multiple Rocket Launcher"},
		 ["panzerwerfer_squad_mp"] = {icon = "Icons_symbols_vehicle_german_panzerwerfer_symbol", name = "Panzerwerfer 42 Multiple Rocket Launcher"},
		 ["panzer_iv_command_squad"] = {icon = "Icons_symbols_vehicle_german_panzer_iv_command_tank_symbol", name = "Panzer IV Command Tank"},
		 ["panzer_iv_command_squad_mp"] = {icon = "Icons_symbols_vehicle_german_panzer_iv_command_tank_symbol", name = "Panzer IV Command Tank"},
		 ["panzer_iv_squad"] = {icon = "Icons_symbols_vehicle_german_panzer_iv_symbol", name = "Panzer IV Medium Tank"},
		 ["panzer_iv_squad_mp"] = {icon = "Icons_symbols_vehicle_german_panzer_iv_symbol", name = "Panzer IV Medium Tank"},
		 ["panzer_iv_stubby_squad"] = {icon = "Icons_symbols_vehicle_german_panzer_iv_f1_symbol", name = "Panzer IV Ausf F1"},
		 ["panzer_iv_stubby_squad_mp"] = {icon = "Icons_symbols_vehicle_german_panzer_iv_f1_symbol", name = "Panzer IV Ausf F1"},
		 ["panzer_mg_squad"] = {icon = "Icons_symbols_vehicle_german_panzer_iv_symbol", name = "Panzer IV Medium Tank"},
		 ["puma_east_german_mp"] = {icon = "Icons_symbols_vehicle_west_german_234_puma_armored_car_symbol", name = "Sdkfz 234 'Puma' Armored Car"},
		 ["scoutcar_sdkfz222"] = {icon = "Icons_symbols_vehicle_german_222_armored_car_symbol", name = "SdKfz 221 Scout Car"},
		 ["scoutcar_sdkfz222_mp"] = {icon = "Icons_symbols_vehicle_german_222_armored_car_symbol", name = "SdKfz 221 Scout Car"},
		 ["stug_iii_e_commander_squad_mp"] = {icon = "Icons_symbols_vehicle_german_stug_iii_e_symbol", name = "StuG III Ausf. E Assault Gun"},
		 ["stug_iii_e_squad"] = {icon = "Icons_symbols_vehicle_german_stug_iii_e_symbol", name = "StuG III Ausf. E Assault Gun"},
		 ["stug_iii_e_squad_mp"] = {icon = "Icons_symbols_vehicle_german_stug_iii_e_symbol", name = "StuG III Ausf. E Assault Gun"},
		 ["stug_iii_squad"] = {icon = "Icons_symbols_vehicle_german_stug_iii_g_symbol", name = "StuG III Ausf. G Assault Gun"},
		 ["stug_iii_squad_mp"] = {icon = "Icons_symbols_vehicle_german_stug_iii_g_symbol", name = "StuG III Ausf. G Assault Gun"},
		 ["cargo_plane"] = {icon = "Icons_symbols_vehicle_german_stuka_symbol", name = ""},
		 ["cargo_plane_fuel"] = {icon = "Icons_symbols_vehicle_german_stuka_symbol", name = ""},
		 ["cargo_plane_munitions"] = {icon = "Icons_symbols_vehicle_german_stuka_symbol", name = ""},
		 ["stuka_air_cap_squad"] = {icon = "Icons_symbols_vehicle_german_stuka_symbol", name = ""},
		 ["stuka_air_cap_squad_mp"] = {icon = "Icons_symbols_vehicle_german_stuka_symbol", name = ""},
		 ["stuka_ground_anti_tank_squad"] = {icon = "Icons_symbols_vehicle_german_stuka_symbol", name = ""},
		 ["stuka_ground_anti_tank_squad_m06"] = {icon = "Icons_symbols_vehicle_german_stuka_symbol", name = ""},
		 ["stuka_ground_anti_tank_squad_mp"] = {icon = "Icons_symbols_vehicle_german_stuka_symbol", name = ""},
		 ["stuka_ground_anti_tank_squad_superiority"] = {icon = "Icons_symbols_vehicle_german_stuka_symbol", name = ""},
		 ["stuka_ground_attack_squad"] = {icon = "Icons_symbols_vehicle_german_stuka_symbol", name = ""},
		 ["stuka_ground_attack_squad_m09"] = {icon = "Icons_symbols_vehicle_german_stuka_symbol", name = ""},
		 ["stuka_ground_attack_squad_mp"] = {icon = "Icons_symbols_vehicle_german_stuka_symbol", name = ""},
		 ["stuka_ground_attack_west_germans_squad"] = {icon = "Icons_symbols_vehicle_german_stuka_symbol", name = ""},
		 ["stuka_ground_fragmentation_squad"] = {icon = "Icons_symbols_vehicle_german_stuka_symbol", name = ""},
		 ["stuka_ground_fragmentation_squad_mp"] = {icon = "Icons_symbols_vehicle_german_stuka_symbol", name = ""},
		 ["stuka_incendiary_bomb_squad"] = {icon = "Icons_symbols_vehicle_german_stuka_symbol", name = ""},
		 ["stuka_incendiary_bomb_victory_squad"] = {icon = "Icons_symbols_vehicle_german_stuka_symbol", name = ""},
		 ["stuka_smoke_squad"] = {icon = "Icons_symbols_vehicle_german_stuka_symbol", name = ""},
		 ["stuka_smoke_squad_mp"] = {icon = "Icons_symbols_vehicle_german_stuka_symbol", name = ""},
		 ["tactical_bombers"] = {icon = "Icons_symbols_vehicle_german_stuka_symbol", name = ""},
		 ["tactical_bombers_accurate"] = {icon = "Icons_symbols_vehicle_german_stuka_symbol", name = ""},
		 ["tiger_ace_squad_mp"] = {icon = "Icons_symbols_vehicle_german_tiger_ace_symbol", name = "Tiger Ace PzKpfw VI"},
		 ["tiger_squad"] = {icon = "Icons_symbols_vehicle_german_tiger_symbol", name = "Tiger PzKpfw VI"},
		 ["tiger_squad_mp"] = {icon = "Icons_symbols_vehicle_german_tiger_symbol", name = "Tiger PzKpfw VI"},
		 ["tiger_squad_sp_a2_m02"] = {icon = "Icons_symbols_vehicle_german_tiger_symbol", name = "Tiger PzKpfw VI"},
		 ["tiger_squad_tow"] = {icon = "Icons_symbols_vehicle_german_tiger_symbol", name = "Tiger PzKpfw VI"},
		 ["proxy_hmg_squad_mp"] = {icon = "Icons_symbols_unit_soviet_conscript_03_symbol", name = ""},
		 ["proxy_mech_squad_mp"] = {icon = "Icons_symbols_unit_soviet_conscript_03_symbol", name = ""},
		 ["proxy_riflemen_squad_mp"] = {icon = "", name = ""},
		 ["proxy_sniper_squad_mp"] = {icon = "Icons_symbols_unit_soviet_conscript_03_symbol", name = ""},
		 ["boat_01"] = {icon = "", name = "Assault Boat."},
		 ["steam_train"] = {icon = "Icons_symbols_vehicle_soviet_kv1_heavy_tank_symbol", name = "Steam Train"},
		 ["m01_conscript_squad_docks"] = {icon = "Icons_symbols_unit_soviet_conscript_01_symbol", name = ""},
		 ["m01_conscript_squad_harmless"] = {icon = "Icons_symbols_unit_soviet_conscript_01_symbol", name = "Conscript Infantry"},
		 ["m01_conscript_squad_harmless_durable"] = {icon = "Icons_symbols_unit_soviet_conscript_01_symbol", name = "Conscript Infantry"},
		 ["m01_conscript_squad_wounded"] = {icon = "Icons_symbols_unit_soviet_conscript_01_symbol", name = "Conscript Infantry"},
		 ["m01_il-2_sturmovik_rocket_squad"] = {icon = "Icons_symbols_vehicle_soviet_il2_symbol", name = ""},
		 ["m01_il2_dogfight"] = {icon = "", name = ""},
		 ["m01_medic"] = {icon = "Icons_symbols_unit_soviet_sniper_symbol", name = "Medic"},
		 ["m02_combat_engineer_squad"] = {icon = "Icons_symbols_unit_soviet_engineer_symbol", name = "Combat Engineer Squad"},
		 ["m02_refugee_squad"] = {icon = "Icons_symbols_unit_soviet_conscript_01_symbol", name = "Refugee"},
		 ["m08_combat_engineer_squad"] = {icon = "Icons_symbols_unit_soviet_engineer_symbol", name = "Combat Engineer Squad"},
		 ["m08_tank_buster_conscript_squad"] = {icon = "Icons_symbols_unit_soviet_penal_battalion_symbol", name = "Anti-Tank Conscript Squad"},
		 ["guards_troops_m08"] = {icon = "Icons_symbols_unit_soviet_guards_symbol", name = "Guards Rifle Infantry"},
		 ["m11_ania_sniper_squad"] = {icon = "Icons_symbols_unit_soviet_ania_symbol", name = "Ania"},
		 ["m11_isakovich_squad"] = {icon = "Icons_symbols_unit_soviet_officer_symbol", name = "Isakovich"},
		 ["m11_sniper_team"] = {icon = "Icons_symbols_unit_soviet_sniper_symbol", name = "Partisan Snipers"},
		 ["shock_troops_m11"] = {icon = "Icons_symbols_unit_soviet_shock_symbol", name = ""},
		 ["tow_cold_weather_guards_troops"] = {icon = "Icons_symbols_unit_soviet_guards_symbol", name = "Guards Troops"},
		 ["m11_partisan_squad_kar98k_rifle"] = {icon = "Icons_symbols_unit_soviet_partisan_anti_infantry_symbol", name = "Partisans"},
		 ["m11_partisan_squad_nagant_rifle"] = {icon = "Icons_symbols_unit_soviet_partisan_anti_vehicle_symbol", name = "Partisans"},
		 ["m11_partisan_squad_noweapon"] = {icon = "Icons_symbols_unit_soviet_partisan_anti_infantry_symbol", name = "Partisans"},
		 ["m08_t_34_76_squad_smallpath"] = {icon = "Icons_symbols_vehicle_soviet_t34_76_heavy_tank_symbol", name = ""},
		 ["us6_truck_squad"] = {icon = "Icons_symbols_vehicle_soviet_su6_truck_symbol", name = "ZiS-6 Cargo Truck"},
		 ["combat_engineer_squad"] = {icon = "Icons_symbols_unit_soviet_engineer_symbol", name = "Combat Engineer Squad"},
		 ["combat_engineer_squad_mp"] = {icon = "Icons_symbols_unit_soviet_engineer_symbol", name = "Combat Engineer Squad"},
		 ["base_conscript_squad"] = {icon = "Icons_symbols_unit_soviet_conscript_02_symbol", name = "Fresh Conscript Squad"},
		 ["base_conscript_squad_mp"] = {icon = "Icons_symbols_unit_soviet_conscript_01_symbol", name = "Conscript Infantry Squad"},
		 ["conscript_squad"] = {icon = "Icons_symbols_unit_soviet_conscript_03_symbol", name = "Conscript Infantry Squad"},
		 ["conscript_squad_mp"] = {icon = "Icons_symbols_unit_soviet_conscript_03_symbol", name = "Conscript Infantry Squad"},
		 ["conscript_squad_tutorial"] = {icon = "Icons_symbols_unit_soviet_conscript_03_symbol", name = "Conscript Infantry Squad"},
		 ["dshk_38_hmg_squad"] = {icon = "Icons_symbols_unit_soviet_mg_symbol", name = "DShK 38 Heavy Machine Gun"},
		 ["dshk_38_hmg_squad_mp"] = {icon = "Icons_symbols_vehicle_soviet_dshk_38_50_cal_hmg_symbol", name = "DShK 38 Heavy Machine Gun"},
		 ["m1910_maxim_heavy_machine_gun_squad"] = {icon = "Icons_symbols_unit_soviet_mg_symbol", name = "M1910 Maxim Heavy Machine Gun"},
		 ["m1910_maxim_heavy_machine_gun_squad_mp"] = {icon = "Icons_symbols_unit_soviet_mg_symbol", name = "M1910 Maxim Heavy Machine Gun"},
		 ["hm-120_38_mortar_squad"] = {icon = "Icons_symbols_unit_soviet_mortar_symbol", name = "HM-38 120mm Mortar Squad"},
		 ["hm-120_38_mortar_squad_mp"] = {icon = "Icons_symbols_unit_soviet_mortar_symbol", name = "HM-38 120mm Mortar Squad"},
		 ["pm-82_41_mortar_squad"] = {icon = "Icons_symbols_unit_soviet_mortar_symbol", name = "PM-41 82mm Mortar Squad"},
		 ["pm-82_41_mortar_squad_mp"] = {icon = "Icons_symbols_unit_soviet_mortar_symbol", name = "PM-41 82mm Mortar Squad"},
		 ["partisans_lmg_mp"] = {icon = "Icons_symbols_unit_soviet_partisan_anti_infantry_symbol", name = "Partisan Troops - LMG"},
		 ["partisans_panzerschreck_mp"] = {icon = "Icons_symbols_unit_soviet_partisan_anti_vehicle_symbol", name = "Partisan Tank Hunters - Panzerschreck"},
		 ["partisans_ptrs_mp"] = {icon = "Icons_symbols_unit_soviet_partisan_anti_vehicle_symbol", name = "Partisan Tank Hunters - PTRS"},
		 ["partisans_rifle_mp"] = {icon = "Icons_symbols_unit_soviet_partisan_anti_infantry_symbol", name = "Partisan Troops - Rifles"},
		 ["partisans_smg_mp"] = {icon = "Icons_symbols_unit_soviet_partisan_anti_infantry_symbol", name = "Partisan Troops - Sub-Machineguns"},
		 ["partisan_squad_granatewerfer_34_81mm_mortar"] = {icon = "Icons_symbols_unit_soviet_mortar_symbol", name = "Partisan Granatewerfer 81mm Mortar Squad"},
		 ["partisan_squad_granatewerfer_34_81mm_mortar_mp"] = {icon = "Icons_symbols_unit_soviet_mortar_symbol", name = "Partisan Granatewerfer 81mm Mortar Squad"},
		 ["partisan_squad_kar98k_rifle"] = {icon = "Icons_symbols_unit_soviet_partisan_anti_infantry_symbol", name = "Partisan Squad"},
		 ["partisan_squad_kar98k_rifle_mp"] = {icon = "Icons_symbols_unit_soviet_partisan_anti_infantry_symbol", name = "Partisan Squad"},
		 ["partisan_squad_maxim_hmg"] = {icon = "Icons_symbols_unit_soviet_partisan_anti_infantry_symbol", name = "Partisan M1910 Maxim HMG Squad"},
		 ["partisan_squad_maxim_hmg_mp"] = {icon = "Icons_symbols_unit_soviet_partisan_anti_infantry_symbol", name = "Partisan M1910 Maxim HMG Squad"},
		 ["partisan_squad_mg42_hmg"] = {icon = "Icons_symbols_unit_soviet_partisan_anti_infantry_symbol", name = "Partisan MG42 HMG Squad"},
		 ["partisan_squad_mg42_hmg_mp"] = {icon = "Icons_symbols_unit_soviet_partisan_anti_infantry_symbol", name = "Partisan MG42 HMG Squad"},
		 ["partisan_squad_nagant_rifle"] = {icon = "Icons_symbols_unit_soviet_partisan_anti_infantry_symbol", name = "Partisan Squad"},
		 ["partisan_squad_nagant_rifle_mp"] = {icon = "Icons_symbols_unit_soviet_partisan_anti_infantry_symbol", name = "Partisan Squad"},
		 ["partisan_squad_pm-82_41_mortar"] = {icon = "Icons_symbols_unit_soviet_partisan_anti_infantry_symbol", name = "Partisan PM-41 82mm Mortar Squad"},
		 ["partisan_squad_pm-82_41_mortar_mp"] = {icon = "Icons_symbols_unit_soviet_partisan_anti_infantry_symbol", name = "Partisan PM-41 82mm Mortar Squad"},
		 ["tow_bridge_partisan_squad_at"] = {icon = "Icons_symbols_unit_soviet_partisan_anti_vehicle_symbol", name = "Partisan Anti-tank Rifle Squad"},
		 ["tow_bridge_partisan_squad_base"] = {icon = "Icons_symbols_unit_soviet_partisan_anti_infantry_symbol", name = "Partisan Squad"},
		 ["tow_bridge_partisan_squad_maxim"] = {icon = "Icons_symbols_unit_soviet_partisan_mg_symbol", name = "Partisan Heavy Machine Gun Squad"},
		 ["tow_bridge_partisan_squad_mortar"] = {icon = "Icons_symbols_unit_soviet_partisan_mortar_symbol", name = "Partisan PM-41 82mm Mortar Squad"},
		 ["tow_partisan_squad_kar98k_rifle_mp"] = {icon = "Icons_symbols_unit_soviet_partisan_anti_infantry_symbol", name = "Partisan Anti-tank Rifle Squad"},
		 ["tow_partisan_squad_lmg_squad"] = {icon = "Icons_symbols_unit_soviet_partisan_anti_infantry_symbol", name = "Soviet Irregular Light Machinegun Squad"},
		 ["tow_partisan_squad_maxim_hmg_mp"] = {icon = "Icons_symbols_unit_soviet_partisan_anti_infantry_symbol", name = "Partisan Heavy Machine Gun Squad."},
		 ["sniper_team"] = {icon = "Icons_symbols_unit_soviet_sniper_symbol", name = "Scout Sniper Squad"},
		 ["sniper_team_male"] = {icon = "Icons_symbols_unit_soviet_sniper_symbol", name = ""},
		 ["sniper_team_mp"] = {icon = "Icons_symbols_unit_soviet_sniper_symbol", name = "Scout Sniper Squad"},
		 ["commissar_227"] = {icon = "Icons_symbols_unit_soviet_officer_symbol", name = ""},
		 ["commissar_squad_battle"] = {icon = "Icons_symbols_unit_soviet_officer_symbol", name = "Commissar Squad"},
		 ["commissar_squad_mp"] = {icon = "Icons_symbols_unit_soviet_officer_symbol", name = "Commissar Squad"},
		 ["commissar_squad_tow"] = {icon = "Icons_symbols_unit_soviet_officer_symbol", name = ""},
		 ["soviet_officer_squad"] = {icon = "Icons_symbols_unit_soviet_officer_symbol", name = "Officer"},
		 ["soviet_officer_squad_mp"] = {icon = "Icons_symbols_unit_soviet_officer_symbol", name = "Officer"},
		 ["guards_troops"] = {icon = "Icons_symbols_unit_soviet_guards_symbol", name = "Guards Rifle Infantry"},
		 ["guards_troops_assault_mp"] = {icon = "Icons_symbols_unit_soviet_guards_symbol", name = "Guards Rifle Infantry"},
		 ["guards_troops_mp"] = {icon = "Icons_symbols_unit_soviet_guards_symbol", name = "Guards Rifle Infantry"},
		 ["penal_battalion"] = {icon = "Icons_symbols_unit_soviet_penal_battalion_symbol", name = "Penal Battalion"},
		 ["penal_battalion_mp"] = {icon = "Icons_symbols_unit_soviet_penal_battalion_symbol", name = "Penal Battalion"},
		 ["shock_troops"] = {icon = "Icons_symbols_unit_soviet_shock_symbol", name = "Shock Troops"},
		 ["shock_troops_mp"] = {icon = "Icons_symbols_unit_soviet_shock_symbol", name = "Shock Troops"},
		 ["il-2_stumovik_squad"] = {icon = "Icons_symbols_vehicle_soviet_il2_symbol", name = "IL-2 Sturmovik"},
		 ["il-2_stumovik_squad_advanced_mp"] = {icon = "Icons_symbols_vehicle_soviet_il2_symbol", name = ""},
		 ["il-2_stumovik_squad_mp"] = {icon = "Icons_symbols_vehicle_soviet_il2_symbol", name = "IL-2 Sturmovik"},
		 ["il-2_sturmovik_anti_tank_bomb_squad_mp"] = {icon = "Icons_symbols_vehicle_soviet_il2_symbol", name = ""},
		 ["il-2_sturmovik_mark_vehicle_squad_mp"] = {icon = "Icons_symbols_vehicle_soviet_il2_symbol", name = "IL-2 Sturmovik"},
		 ["il-2_sturmovik_recon_squad"] = {icon = "Icons_symbols_vehicle_soviet_il2_symbol", name = "IL-2 Sturmovik"},
		 ["il-2_sturmovik_recon_squad_mp"] = {icon = "Icons_symbols_vehicle_soviet_il2_symbol", name = "IL-2 Sturmovik"},
		 ["il-2_sturmovik_recon_squad_sp"] = {icon = "Icons_symbols_vehicle_soviet_il2_symbol", name = "IL-2 Sturmovik"},
		 ["il-2_sturmovik_rocket_sp_squad"] = {icon = "Icons_symbols_vehicle_soviet_il2_symbol", name = "IL-2 Sturmovik"},
		 ["il-2_sturmovik_rocket_sp_squad_mp"] = {icon = "Icons_symbols_vehicle_soviet_il2_symbol", name = "IL-2 Sturmovik"},
		 ["il-2_sturmovik_rocket_squad"] = {icon = "Icons_symbols_vehicle_soviet_il2_symbol", name = "IL-2 Sturmovik"},
		 ["il-2_sturmovik_rocket_squad_mp"] = {icon = "Icons_symbols_vehicle_soviet_il2_symbol", name = "IL-2 Sturmovik"},
		 ["is-2"] = {icon = "Icons_symbols_vehicle_soviet_is2_symbol", name = "IS-2 Heavy Tank"},
		 ["is-2_mp"] = {icon = "Icons_symbols_vehicle_soviet_is2_symbol", name = "IS-2 Heavy Tank"},
		 ["is-2_tow"] = {icon = "Icons_symbols_vehicle_soviet_is2_symbol", name = ""},
		 ["isu-152"] = {icon = "Icons_symbols_vehicle_soviet_isu152_symbol", name = "ISU-152 Heavy Assault Gun"},
		 ["isu-152_mp"] = {icon = "Icons_symbols_vehicle_soviet_isu152_symbol", name = "ISU-152 Heavy Assault Gun"},
		 ["katyusha_bm-13n_squad"] = {icon = "Icons_symbols_vehicle_soviet_katyush_rocket_truck_symbol", name = "BM-13 Katyusha Rocket Truck"},
		 ["katyusha_bm-13n_squad_mp"] = {icon = "Icons_symbols_vehicle_soviet_katyush_rocket_truck_symbol", name = "BM-13 Katyusha Rocket Truck"},
		 ["kv-1"] = {icon = "Icons_symbols_vehicle_soviet_kv1_heavy_tank_symbol", name = "KV-1 Heavy Tank"},
		 ["kv-1_commander_mp"] = {icon = "Icons_symbols_vehicle_soviet_kv1_heavy_tank_symbol", name = "KV-1 Heavy Tank"},
		 ["kv-1_mp"] = {icon = "Icons_symbols_vehicle_soviet_kv1_heavy_tank_symbol", name = "KV-1 Heavy Tank"},
		 ["kv-1_sp"] = {icon = "Icons_symbols_vehicle_soviet_kv1_heavy_tank_symbol", name = "KV-1 Heavy Tank"},
		 ["kv-2"] = {icon = "Icons_symbols_vehicle_soviet_kv2_heavy_tank_symbol", name = "KV-2 Heavy Assault Tank"},
		 ["kv-2_mp"] = {icon = "Icons_symbols_vehicle_soviet_kv2_heavy_tank_symbol", name = "KV-2 Heavy Assault Tank"},
		 ["kv-2_tow"] = {icon = "Icons_symbols_vehicle_soviet_kv2_heavy_tank_symbol", name = "KV-2 Heavy Assault Tank"},
		 ["kv-2_tow_battle"] = {icon = "Icons_symbols_vehicle_soviet_kv2_heavy_tank_symbol", name = "KV-2 Heavy Assault Tank"},
		 ["kv-8"] = {icon = "Icons_symbols_vehicle_soviet_kv8_symbol", name = "KV-8 Heavy Flamethrower Tank"},
		 ["kv-8_mp"] = {icon = "Icons_symbols_vehicle_soviet_kv8_symbol", name = "KV-8 Heavy Flamethrower Tank"},
		 ["m1931_203mm_b-4_howitzer_artillery"] = {icon = "Icons_symbols_vehicle_soviet_b4_artillery_gun_symbol", name = "B-4 203mm Super Heavy Artillery"},
		 ["m1931_203mm_b-4_howitzer_artillery_commander_mp"] = {icon = "Icons_symbols_vehicle_soviet_b4_artillery_gun_symbol", name = "B-4 203mm Howitzer"},
		 ["m1931_203mm_b-4_howitzer_artillery_mp"] = {icon = "Icons_symbols_vehicle_soviet_b4_artillery_gun_symbol", name = "B-4 203mm Super Heavy Artillery"},
		 ["m1937_152mm_ml_20_artillery"] = {icon = "Icons_symbols_vehicle_soviet_ml20_artillery_gun_symbol", name = "ML-20 152mm Gun-Howitzer"},
		 ["m1937_152mm_ml_20_artillery_mp"] = {icon = "Icons_symbols_vehicle_soviet_ml20_artillery_gun_symbol", name = "ML-20 152mm Gun-Howitzer"},
		 ["m3a1_scout_car_squad"] = {icon = "Icons_symbols_vehicle_soviet_m3a1_armored_personnel_carrier_symbol", name = "M3A1 Light Scout Car"},
		 ["m3a1_scout_car_squad_mp"] = {icon = "Icons_symbols_vehicle_soviet_m3a1_armored_personnel_carrier_symbol", name = "M3A1 Light Scout Car"},
		 ["m5_halftrack_squad"] = {icon = "Icons_symbols_vehicle_soviet_m5_halftrack_symbol", name = "M5 Half-track Transport"},
		 ["m5_halftrack_squad_mp"] = {icon = "Icons_symbols_vehicle_soviet_m5_halftrack_symbol", name = "M5 Half-track Transport"},
		 ["m5_halftrack__assault_squad_mp"] = {icon = "Icons_symbols_vehicle_soviet_m5_halftrack_symbol", name = "M5 Half-track Transport"},
		 ["cargo_plane_soviet"] = {icon = "Icons_symbols_vehicle_german_stuka_symbol", name = ""},
		 ["soviet_allied_cargo_plane"] = {icon = "Icons_symbols_vehicle_soviet_il2_symbol", name = ""},
		 ["soviet_76mm_sherman_mp"] = {icon = "Icons_symbols_vehicle_aef_m4a3_sherman_76mm_symbol", name = "M4C Sherman"},
		 ["m1937_53-k_45mm_at_gun_squad"] = {icon = "Icons_symbols_vehicle_soviet_m1942_at_gun_symbol", name = "M-42 45mm Anti-tank Gun"},
		 ["m1937_53-k_45mm_at_gun_squad_mp"] = {icon = "Icons_symbols_vehicle_soviet_m1942_at_gun_symbol", name = "M-42 45mm Anti-tank Gun"},
		 ["m1942_zis-3_76mm_at_gun_squad"] = {icon = "Icons_symbols_vehicle_soviet_m1942_76mm_at_gun_symbol", name = "ZiS-3 76mm Divisional Field Gun"},
		 ["m1942_zis-3_76mm_at_gun_squad_mp"] = {icon = "Icons_symbols_vehicle_soviet_m1942_76mm_at_gun_symbol", name = "ZiS-3 76mm Divisional Field Gun"},
		 ["su-76m"] = {icon = "Icons_symbols_vehicle_soviet_su76m_assault_gun_symbol", name = "SU-76M Assault Gun"},
		 ["su-76m_mp"] = {icon = "Icons_symbols_vehicle_soviet_su76m_assault_gun_symbol", name = "SU-76M Assault Gun"},
		 ["su-76m_tow"] = {icon = "Icons_symbols_vehicle_soviet_su76m_assault_gun_symbol", name = ""},
		 ["su-85"] = {icon = "Icons_symbols_vehicle_soviet_su85_tank_destroyer_symbol", name = "SU-85 Medium Tank Destroyer"},
		 ["su-85_mp"] = {icon = "Icons_symbols_vehicle_soviet_su85_tank_destroyer_symbol", name = "SU-85 Medium Tank Destroyer"},
		 ["t-70m"] = {icon = "Icons_symbols_vehicle_soviet_t70m_light_tank_symbol", name = "T-70 Light Tank"},
		 ["t-70m_mp"] = {icon = "Icons_symbols_vehicle_soviet_t70m_light_tank_symbol", name = "T-70 Light Tank"},
		 ["t_34_76_squad"] = {icon = "Icons_symbols_vehicle_soviet_t34_76_heavy_tank_symbol", name = "T-34/76 Medium Tank"},
		 ["t_34_76_squad_mp"] = {icon = "Icons_symbols_vehicle_soviet_t34_76_heavy_tank_symbol", name = "T-34/76 Medium Tank"},
		 ["t_34_85_advanced_squad_mp"] = {icon = "Icons_symbols_vehicle_soviet_t34_85_symbol", name = "T-34/85 Medium Tank"},
		 ["t_34_85_squad"] = {icon = "Icons_symbols_vehicle_soviet_t34_76_heavy_tank_symbol", name = "T-34/85 Medium Tanks"},
		 ["t_34_85_squad_mp"] = {icon = "Icons_symbols_vehicle_soviet_t34_85_symbol", name = "T-34/85 Medium Tanks"},
		 ["zis_6_transport_truck"] = {icon = "Icons_symbols_vehicle_soviet_su6_truck_symbol", name = "ZiS-6 Transport Truck"},
		 ["zis_6_transport_truck_mp"] = {icon = "Icons_symbols_vehicle_soviet_su6_truck_symbol", name = "ZiS-6 Transport Truck"},
		 ["howitzer_105mm_le_fh18_artillery_minichallenge"] = {icon = "Icons_symbols_vehicle_german_howitzer_symbol", name = ""},
		 ["howitzer_105mm_long_range"] = {icon = "Icons_symbols_vehicle_german_howitzer_symbol", name = "10.5cm leFH 18 Artillery"},
		 ["scoutcar_223_squad"] = {icon = "Icons_symbols_vehicle_german_222_armored_car_symbol", name = "SdKfz 223 Scout Car"},
		 ["assault_pioneer_squad_mp"] = {icon = "Icons_symbols_unit_west_german_sturmpioneers_symbol", name = "Sturmpioneer Squad"},
		 ["fallschirmjager_squad_mp"] = {icon = "Icons_symbols_unit_west_german_fallschirmjager_symbol", name = "Fallschirmjäger"},
		 ["field_officer_squad_mp"] = {icon = "Icons_symbols_unit_west_german_field_officer_symbol", name = "Field Officer"},
		 ["terror_officer_squad_mp"] = {icon = "Icons_symbols_unit_west_german_terror_officer_symbol", name = "Sturm Offizier"},
		 ["jaeger_light_infantry_recon_squad_mp"] = {icon = "Icons_symbols_unit_west_german_jaeger_light_infantry_symbol", name = "Jaeger Light Infantry Recon Squad"},
		 ["obersoldaten_squad_mp"] = {icon = "Icons_symbols_unit_west_german_waffen_honor_guard_symbol", name = "Obersoldaten"},
		 ["panzerfusilier_squad_mp"] = {icon = "Icons_symbols_unit_west_german_panzerfusilier_symbol", name = "Panzerfüsilier"},
		 ["urban_assault_light_infantry"] = {icon = "Icons_symbols_unit_german_jaeger_light_infantry_symbol", name = ""},
		 ["volksgrenadier_squad_mp"] = {icon = "Icons_symbols_unit_west_german_volksgrenadiers_symbol", name = "Volksgrenadiers"},
		 ["pak40_75mm_at_gun_squad_wg_mp"] = {icon = "Icons_symbols_vehicle_german_pak_40_75mm_at_gun_symbol", name = "Pak 40 Anti-Tank Gun"},
		 ["raketenwerfer43_88mm_puppchen_antitank_gun_squad_mp"] = {icon = "Icons_symbols_vehicle_west_german_raketenwerfer_43_at_gun_symbol", name = "Raketenwerfer 43 Anti-Tank Rocket Launcher"},
		 ["flak_emplacement"] = {icon = "Icons_symbols_building_west_german_flak_emplacement_symbol", name = "2cm Flak 38 Emplacement"},
		 ["flak_emplacement_base"] = {icon = "Icons_symbols_building_west_german_flak_emplacement_symbol", name = "Flak Emplacement"},
		 ["grw34_81mm_mortar_squad_mp"] = {icon = "Icons_symbols_unit_german_granatwerfer_34_mortar_symbol", name = "Granatwerfer 42 8cm Light Mortar"},
		 ["le_ig_18_inf_support_gun_squad_mp"] = {icon = "Icons_symbols_vehicle_west_german_ig18_infantry_support_gun_symbol", name = "7.5cm le.IG 18 Infantry Support Gun"},
		 ["mg34_heavy_machine_gun_squad_mp"] = {icon = "Icons_symbols_unit_german_m1910_hmg_symbol", name = "MG34 Heavy Machine Gun Team"},
		 ["mg42_heavy_machine_gun_squad_wg_mp"] = {icon = "Icons_symbols_unit_german_m1910_hmg_symbol", name = "MG 42 Heavy Machine Gun"},
		 ["pak43_88mm_at_gun_squad_westgerman_mp"] = {icon = "Icons_symbols_vehicle_german_pak_43_at_gun_symbol", name = "Pak 43 88mm Anti-tank gun"},
		 ["mortar_250_halftrack_squad_westgerman_mp"] = {icon = "Icons_symbols_vehicle_german_251_mortar_halftrack_symbol", name = "SdKfz 250/7 Mortar Half-track"},
		 ["sdkfz_251_17_flak_halftrack_squad_mp"] = {icon = "Icons_symbols_vehicle_west_german_halftrack_251_flak_symbol", name = "SdKfz 251/17 Flak Half-track"},
		 ["sdkfz_251_20_ir_searchlight_halftrack_squad_mp"] = {icon = "Icons_symbols_vehicle_west_german_halftrack_251_infrared_symbol", name = "SdKfz 251/20 Half-track w/ Infrared Searchlight"},
		 ["sdkfz_251_20_ir_searchlight_halftrack_squad_sp"] = {icon = "Icons_symbols_vehicle_west_german_halftrack_251_infrared_symbol", name = "SdKfz 251/20 Half-track w/ Infrared Searchlight"},
		 ["sdkfz_251_halftrack_squad_mp_2"] = {icon = "Icons_symbols_vehicle_german_251_halftrack_symbol", name = ""},
		 ["sdkfz_251_wurfrahmen_40_halftrack_squad_mp"] = {icon = "Icons_symbols_vehicle_west_german_halftrack_251_walking_stuka_symbol", name = "SdKfz 251 \"Stuka zu Fuß\" Half-track"},
		 ["jagdpanzer_tank_destroyer_squad_mp"] = {icon = "Icons_symbols_vehicle_west_german_jagdpanzer_symbol", name = "Jagdpanzer IV/70 (V)"},
		 ["jagdtiger_td_squad_mp"] = {icon = "Icons_symbols_vehicle_west_german_jagdtiger_symbol", name = "\"Jagdtiger\" Panzerjäger Tiger Ausf. B"},
		 ["command_king_tiger_squad_mp"] = {icon = "Icons_symbols_vehicle_west_german_king_tiger_symbol", name = ""},
		 ["king_tiger_squad_mp"] = {icon = "Icons_symbols_vehicle_west_german_king_tiger_symbol", name = "Tiger B 'Königstiger'"},
		 ["kubelwagen_squad_mp"] = {icon = "Icons_symbols_vehicle_west_german_kubelwagen_symbol", name = "Kübelwagen"},
		 ["ostwind_squad_westgerman_mp"] = {icon = "Icons_symbols_vehicle_german_ostwind_flak_panzer_symbol", name = "Flakpanzer IV Ostwind"},
		 ["panther_ausf_g_squad_mp"] = {icon = "Icons_symbols_vehicle_west_german_panther_symbol", name = "Panther PzKpfw V 'Medium' Tank"},
		 ["panther_commander_squad_mp"] = {icon = "Icons_symbols_vehicle_west_german_panther_command_tank_symbol", name = "Panther PzKpfw V Command Tank"},
		 ["panzer_ii_luchs_squad_mp"] = {icon = "Icons_symbols_vehicle_west_german_panzer_ii_luchs_symbol", name = "Panzer II Ausf. L 'Luchs' Light Tank"},
		 ["panzer_iv_ausf_j_battle_group_mp"] = {icon = "Icons_symbols_vehicle_german_panzer_iv_symbol", name = "Panzer IV Ausf J. Medium Tank"},
		 ["ju52_paratrooper_plane"] = {icon = "Icons_symbols_vehicle_german_stuka_symbol", name = ""},
		 ["armored_car_sdkfz_234_squad_mp"] = {icon = "Icons_symbols_vehicle_west_german_234_puma_armored_car_symbol", name = "SdKfz 234 'Puma' Heavy Armored Car"},
		 ["sturmtiger_squad_mp"] = {icon = "Icons_symbols_vehicle_west_german_sturmtiger_symbol", name = "Sturmtiger"},
		 ["sws_halftrack_squad_mp"] = {icon = "Icons_symbols_vehicle_west_german_halftrack_sws_symbol", name = "sWS Supply Half-track"},
		 ["sws_halftrack_squad_sp"] = {icon = "Icons_symbols_vehicle_west_german_halftrack_sws_symbol", name = "sWS Supply Half-track"},
	}

end